### PR TITLE
fix(classifier): surveyTask.alwaysShowThumbnails must be a boolean

### LINKED ISSUE #6084: Missing tasks in Offal Watching survey workflow
## Package
_Choose from the list:_
- [ ] app-content-pages
- [ ] app-project
- [x] lib-classifier
- [ ] lib-panoptes-js
- [ ] lib-react-components
- [ ] unknown

## Describe the bug

https://www.zooniverse.org/projects/embeller/offal-wildlife-watching/classify/workflow/25727

Choose Both or All Unknown for the second question, then press Next. The task area will be empty, but you can still submit a classification by pressing Done. 

## Screenshots

https://github.com/zooniverse/front-end-monorepo/assets/59547/b0851052-00a9-402f-9064-c2c857af2030

## Expected behavior
There's a final survey task that should show up. Apparently it loads if you view this workflow in PFE. 

## Additional context

https://www.zooniverse.org/talk/2354/3326062?comment=5485133&page=5

### PR DESCRIPTION
**Pull request by eatyourgreens**
Quick fix for a bug where the survey task won't display when `task.alwaysShowThumbnails` is a string. In that case, the snapshot preprocessor will coerce it to a boolean.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
- lib-classifier/plugins/tasks/survey

## Linked Issue and/or Talk Post
- fixes #6084.

## How to Review
Task T0 for Offal Watching should be displayed in the classifier now.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

File: packages/lib-classifier/src/plugins/tasks/survey/models/SurveyTask.js [hunk 1]
```diff
@@ -44,6 +44,21 @@ const Survey = types.model('Survey', {
...
+
+      }
+      if (snapshot.alwaysShowThumbnails === 'true') {
+        newSnapshot.alwaysShowThumbnails = true
+      }
+      newSnapshot.alwaysShowThumbnails = !!newSnapshot.alwaysShowThumbnails
+      return newSnapshot
+    }
+    return snapshot
+  })
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/plugins/tasks/survey/models/SurveyTask.js:61]: Since `alwaysShowThumbnails` is deprecated, a better fix might be to remove it here and replace it with `thumbnails`.

File: packages/lib-classifier/src/plugins/tasks/survey/models/SurveyTask.js [hunk 2]
```diff
@@ -41,9 +41,33 @@ const Survey = types.model('Survey', {
...
+    if (snapshot.hasOwnProperty('alwaysShowThumbnails')) {
+      const newSnapshot = { ...snapshot }
+      // 'true' and 'false' are both true.
+      if (snapshot.alwaysShowThumbnails === 'false') {
+        newSnapshot.alwaysShowThumbnails = false
+      }
+      if (snapshot.alwaysShowThumbnails === 'true') {
+        newSnapshot.alwaysShowThumbnails = true
+      }
+      newSnapshot.alwaysShowThumbnails = !!newSnapshot.alwaysShowThumbnails
```
Comment (mcbouslog) [inline packages/lib-classifier/src/plugins/tasks/survey/models/SurveyTask.js:59]: I think this line fixes the empty string issue 👍 .

**Review by mcbouslog — APPROVED** [review]
LGTM!

Code changes look good, correspond to PFE 👍 
Confirmed copied task works on staging: https://local.zooniverse.org:3000/projects/markb-panoptes/survey-task-test-project/classify/workflow/3814?env=staging
Confirmed original workflow (⚠️ live project) works as expected/fixed: https://local.zooniverse.org:3000/projects/embeller/offal-wildlife-watching/classify/workflow/25727?demo=true

Nice work!

File: packages/lib-classifier/src/plugins/tasks/survey/models/SurveyTask.js (hunk 2 above)
Comment (eatyourgreens) [reply packages/lib-classifier/src/plugins/tasks/survey/models/SurveyTask.js:59]: Yeah. String truthiness is determined by `string.length` so empty strings are false (and `'false'` is true.)
