### PR TITLE
fix(lib-classifier): refresh expired bearer tokens

### LINKED ISSUE #6594: Unable to create a new discussion from Quick Talk
https://github.com/zooniverse/front-end-monorepo/blob/51f064ed7d49dd54275113563831ad5b43b14387/packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalkContainer.js#L47

`usePanoptesAuth` here doesn’t refresh expired tokens, leading to permissions errors if you’re logged in, but using a tab that’s been open for two hours or more.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Fix `usePanoptesAuth` hook to refresh expired bearer tokens in the classifier. Fixes a bug where Quick Talk stops working once your bearer token expires.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
- lib-classifier

## Linked Issue and/or Talk Post
- fixes #6594.

## How to Review
The original issue (#6594) happens if you leave the classifier open long enough for your bearer token to expire, so you might need to open the classifier in a tab and leave it for a couple of hours. With the changes here, an expired token should always be refreshed, as long as you don't allow your Panoptes refresh token to expire. I think refresh tokens are good for up to 2 weeks.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

File: packages/lib-classifier/src/hooks/usePanoptesAuth.js [hunk 1]
```diff
@@ -1,17 +1,18 @@
...
     const token = await getBearerToken(authClient)
-    setAuthorization(token)
+    if (token !== authorization) {
+      setAuthorization(token)
+    }
   }
 
-  useEffect(function onUserChange() {
-    checkAuth()
-  }, [authClient, userID])
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/hooks/usePanoptesAuth.js:14]: The original bug happens because this hook stores your bearer token in component state and reuses it forever, even after it has expired. It should be checked (by running `checkAuth()`) every time that it's used.

Comment (eatyourgreens) [reply packages/lib-classifier/src/hooks/usePanoptesAuth.js:14]: General tip for reviewing React components: whenever you see `useEffect` it has probably introduced a subtle bug.
