### PR TITLE
Classifier: Refactor FeedbackModal. Remove @inject.

### LINKED ISSUE #2877: Light curve viewer feedback doesn't show expected colors
## Package
- lib-classifier

## Describe the bug
The light curve viewer feedback doesn't show the expected colors (green for success, red for failure) unless the graph is interacted with (dragged or zoomed within).

## To Reproduce
1. Go to https://frontend.preview.zooniverse.org/projects/nora-dot-test/planet-finders-beta/classify/workflow/3317?env=staging&demo=true
2. Make a few random annotations, click on Done
3. Get feedback (if don't get feedback, go to another subject)
4. See feedback modal with graph showing annotations and actual, but note no green or red transits
5. Drag within graph or zoom within, expected colors will appear

## Expected behavior
Expected transits shown as green or red.

### PR DESCRIPTION
**Pull request by eatyourgreens**
- Replace `@inject` with `@helpers/withStores`.
 - Rewrite `FeedbackModal` as a functional component.
 - Rewrite `Graph2dRangeFeedback` as a functional component.
 - Wrap `drawFeedbackBrushes` in `useCallback`.
 - Fix feedback colours when the SVG is first rendered.

Try it out on Planet Hunters: TESS in the dev classifier.
https://local.zooniverse.org:8080/?project=nora-dot-eisner/planet-hunters-tess&env=production&demo=true

or PH Staging while the live project is offline.
https://local.zooniverse.org:8080/?project=nora-dot-test/planet-finders-beta&demo=true

Package:
lib-classifier

Closes #2877.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
This is a straight rewrite of the feedback popup from a class to a function, so it doesn't fix #2877. I'm having a look to see if I can spot why the colours aren't rendering properly.

File: packages/lib-classifier/src/components/Classifier/components/Feedback/components/Graph2dRangeFeedback.js [hunk 1]
```diff
@@ -72,46 +72,39 @@ class Graph2dRangeFeedback extends Component {
...
+        .selectAll('.selection')
+        .style('fill', () => {
+          if (feedbackBrush.success === true) {
+            return 'green'
+          } else if (feedbackBrush.success === false) {
+            return 'red'
+          } else {
+            return 'white'
+          }
+        })
```
Comment (shaunanoordin) [inline packages/lib-classifier/src/components/Classifier/components/Feedback/components/Graph2dRangeFeedback.js:93]: The biggest change is that the "Set Brush Colour" logic is now moved from `brushSelection` to `feedbackBrushes`, got it. I'm still trying to grok the differences between these two. From my first read, I see that...

feedbackBrushes = array of brushes (the 2D value ranges) consisting of user-made annotations (annotationBrushes) plus the feedback rules

brushSelection = the logically-OR-joined version of existing brushes (as in DOM elements) on the chart plus feedbackBrushes

What the?

I mean, the new code makes sense now, I'm just trying to figure out how the old code worked previously. 🤔

Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/Feedback/components/Graph2dRangeFeedback.js:93]: Can I delete `brushSelection` now that it isn't used? I'm not 100% sure what it does, so I'm hesitant to remove it in case it does something vital elsewhere.

Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/Feedback/components/Graph2dRangeFeedback.js:93]: Answering my own question: I removed `brushSelection` from the code and feedback disappeared.

Comment (shaunanoordin) [reply packages/lib-classifier/src/components/Classifier/components/Feedback/components/Graph2dRangeFeedback.js:93]: Oh man, yeah, D3.js can be gobbledygook if you're just looking at it like a normal human being. This is what's happening...

_(Technical Trivia ahead! Ignore if you can't be bothered with D3.js!)_

```
// Join the D3 brush objects with our internal annotationBrushes array
const brushSelection = d3annotationsLayer
  .selectAll('.brush')
  .data(feedbackBrushes, (d) => d.id)
```

This bit here says,
- OK, in the Annotations Layer (the actual SVG/DOM element), find all elements with class='brushes'.
- We're going to logically bind/join all those SVG elements to the data values of Feedback brushes.
- ...there's be _no visible changes_ (that happens later), we're just saying, "hey, these SVG elements are joined to these data values..."
- (And yes, confusingly, there can be cases where an existing SVG element has lost the data value it was joined to, or a data value doesn't have an existing SVG element to join to. That's where .exit() and .enter() play their part.)

```
// Set up new brushes
brushSelection.enter()
  .insert('g', '.brush')
  .doBlahBlahBlah()
```

This bit here says,
- For every NEW data value (i.e. a data value that hasn't been paired with an SVG element)...
- ...insert a new `<g class='brush'>` SVG element
- And then for each of those _new_ SVG elements, do blah blah blah on them.
- (Any SVG Element that has already been paired with an existing data value doesn't get blah blah blah performed on them.)

Removing all the `brushSelection` would result in no data points being rendered, as the brushes (data values) wouldn't be data-joined to the, erm, other brushes (SVG elements controlled by D3.js)

**Review by shaunanoordin — APPROVED** [review]
## PR Review

Package: `lib-classifier`

This PR fixes the issue where the Feedback modal for the LightCurveViewer would render the 'feedback range values' (feedback brushes) in the correct feedback colours.

- How this actually works is still a bit baffling to me, as the primary change was to move the "Set Brush Colour" logic from `brushSelection` (which is the "Join" between the SVG elements and the data values (user annotations + feedback range values)) to `feedbackBrushes` which is just the aforementioned data values, _brushified._ My assumption (and the old code's assumption, apparently) was that they'd be functionally similar.
- Also in this PR: code refactors! No behavioural or functional changes detected or anticipated.

Screenshot 2022-02-22 at 17 36 24

_Above: the correct, expected behaviour for the Feedback from, given a user's input, for a simulated light curve subject. "Correctly marked ranges" are marked green, "missed ranges" (the bits where a user is supposed to mark but didn't) are marked red, the user's input/annotations are marked white._

### Testing

Tested on localhost with the [Planet Hunters Beta](https://local.zooniverse.org:8080/?env=staging&project=nora-dot-test/planet-finders-beta&workflow=3317&demo=true) project on staging, with macOS + Chrome

Main test:
- After making some annotations and submitting (clicking Done), for a simulated light curve Subject with Feedback...
  - ...the Feedback modal appears, with the correct colours for user annotations/correct ranges/missed ranges 👍 
  - NOTE: the Planet Hunters Beta project has a mix of simulated and non-simulated Subjects, you may need to repeat this test a few times to see the Feedback modal.

Baseline tests:
- LightCurveViewer remains the same 👍 
  - I can change between Annotate and Move mode.
  - I can pan/zoom using mouse (in Move mode), keyboard (in both modes), and pressing the zoom in/out buttons on the image toolbar
  - I can create, edit, and delete annotations (in Annotate mode)
  - I can submit Classifications
 
### Status

LGTM 👍
