### PR TITLE
lib-user: Refactor group stats data export

### LINKED ISSUE #6363: User group CSV export ("Export all stats") doesn't work with a group of over 800 members
## Package
- lib-user

## Describe the bug
The CSV export ("Export all stats") doesn't work with a group of over 800 members. The related [request for all users in a group](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-user/src/components/Contributors/Contributors.js#L104-L109) exceeds nginx limits, as it includes the user IDs for all group members.

Note user group `2533715` as an example.

## Expected behavior
The CSV export ("Export all stats") should process as expected with all groups.

### PR DESCRIPTION
**Pull request by mcbouslog**
## Package
- lib-user

## Linked Issue and/or Talk Post
- closes #6363 

## Describe your changes
- refactor `handleGenerateExport` and `getAllUsers` to separate functions
- refactor `getAllUsers` with `CHUNK_SIZE` of 200 to batch requests of users to a character size that's broadly compatible (see Character Size Note)
- create ExportStats component to provide confirmation, loading, error, and success states UIs
- add progress indicator
- add file size estimate
- [x] design review and edits

Character Size Note
- previously groups with more than ~200 members exceeded request character size limitations (~2,084 per Chrome, ~4,000 - ~8,000 per nginx, depending on settings, to name a few)
- the request exceeded character size limitations because the user ids were included in the get request as a url param, i.e.  `https://www.zooniverse.org/api/users?page=1&id=**123456**%2C**789123**%2C**234567**%2C**891234**` (user ids surrounded by **'s)
- with groups of over roughly 200, this returns a 406 error

UX Changes Note
- with a very large group, like https://www.zooniverse.org/groups/2533715/contributors , after clicking the export stats link, it will take a long time to process the related requests and the CSV file may be as large as 24MB(!!)
- because many `/users` requests take a long time and the file size might be quite large...
- the confirm step (file size) and progress (many requests) component states are included in these changes
- the final success component state provides a link to click instead of auto-downloading

## How to Review
_Helpful explanations that will make your reviewer happy:_
- What Zooniverse project should my reviewer use to review UX?
  - ⚠️ very large group ⚠️ (requires admin): https://local.zooniverse.org:3000/groups/2533715/contributors?env=production
  - medium group: [insert medium group link here]
  - small group: https://local.zooniverse.org:3000/groups/2620016/contributors?env=production
- What user actions should my reviewer step through to review this PR?
  - click the "Export all stats" link in the upper right of the group/contributors page
- Which storybook stories should be reviewed?
  - a few new ones for the different ExportStats states, starting with http://localhost:6008/?path=/story/components-contributors-exportstats--confirm-large-export
- Are there plans for follow up PR’s to further fix this bug or develop this feature? no

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

## Refactoring
- [ ] The PR creator has described the reason for refactoring
- [ ] The refactored component(s) continue to work as expected

## Post-merge
- [ ] This PR adds translations keys to English dictionary(s). See guidance for pulling new keys to Lokalise [here](https://github.com/zooniverse/how-to-zooniverse/blob/master/Translations/lokalise.md#lokalise-and-fem).

### CODE REVIEW

File: packages/lib-user/src/components/Contributors/helpers/getAllUsers.js [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+          id: chunk.join(','),
+          page_size: 100 // per panoptes, maximum page_size is 100
+        }
+
+        const wrappedPromise = fetchPanoptesUsers(chunkQuery).then(result => {
+          setExportProgress(prevProgress => prevProgress + ((1 / totalChunks) * 100))
+          return result
+        })
+
+        userPromises.push(wrappedPromise)
```
Comment (mcbouslog) [inline packages/lib-user/src/components/Contributors/helpers/getAllUsers.js:33]: The wrapped promises are essentially the progress indicator. This is not exact. On very large groups the progress hangs around 90-98% as the very last few `/users` requests take awhile to return, and I'm not sure why. 

This makes me wonder - is a roughly accurate but not exact progress indicator that sometimes appears to but doesn't actually get stuck towards completion better or worse than a simple loading indicator? For most groups a progress status isn't necessary, but for the very large groups it feels like something is necessary.

File: packages/lib-user/src/components/Contributors/helpers/handleGenerateExport.js [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+  setErrorMessage,
+  stats
+}) {
+  setExportStatus(asyncStates.loading)
+  setExportProgress(0)
+
+  try {
+    const allUsers = await getAllUsers({ memberIdsPerStats, setExportProgress })
+
+    const { filename, dataExportUrl } = await generateExport({
```
Comment (mcbouslog) [inline packages/lib-user/src/components/Contributors/helpers/handleGenerateExport.js:23]: I'm not sure without doing some research, but I presume there's way to calculate the actual size of the dataExport once it's generated. If so, the actual size could be added to the success state component.

File: packages/lib-user/src/components/Contributors/helpers/getAllUsers.js (hunk 1 above)
Comment (goplayoutside3) [reply packages/lib-user/src/components/Contributors/helpers/getAllUsers.js:33]: I checked out this branch locally, and confirmed I can generated an export for the large group and the small group. In the large group, I can replicate the loading state freeze at 98%, and I noticed that the loading animation also freezes at that point.

What would cause the `<Loader />` animation to stop? Is that a point in the export process that can be hooked into to display an extra message like "Finishing up..."? Because the animation also froze, I could easily assume the export failed.

File: packages/lib-user/src/components/Contributors/helpers/handleGenerateExport.js [hunk 3]
```diff
@@ -0,0 +1,102 @@
+import asyncStates from '@zooniverse/async-states'
+import { arrayOf, func, number, shape, string } from 'prop-types'
+
+import { getAllUsers } from './getAllUsers'
+
+async function generateExportWithWorker({ group, projects, stats, users }) {
+  return new Promise((resolve, reject) => {
+    const worker = new Worker(new URL('./generateExport.worker.js', import.meta.url))
```
Comment (mcbouslog) [inline packages/lib-user/src/components/Contributors/helpers/handleGenerateExport.js:8]: Creating the CSV was causing the UI to appear stuck at 98%. All the API requests had resolved, and the CSV generation started, which would cause the main browser JavaScript thread to hang. The only solution I could find was to put the CSV content creation on a separate thread with a [Web Worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API). I'm not super familiar with Web Workers, largely followed the examples linked in the MDN docs.

File: packages/lib-user/src/components/Contributors/components/ExportStats/ExportStats.js [hunk 4]
```diff
@@ -0,0 +1,216 @@
...
+      <Layer>
+        <ExportBox>
+          <Text
+            textAlign='center'
+          >
+            {t('Contributors.ExportStats.generating')}
+          </Text>
+          <Button
+            label={t('Contributors.ExportStats.close')}
+            onClick={onClose}
```
Comment (mcbouslog) [inline packages/lib-user/src/components/Contributors/components/ExportStats/ExportStats.js:119]: Since the browser might be hanging at this stage while the CSV content is created, maybe the Close button should be `disabled`? I lean towards the button _not_ be disabled, but open to suggestion.
```suggestion
            disabled
            onClick={onClose}
```

**Comment by mcbouslog** [comment]
@seanmiller26 - apologies for the delay, here are some screenshots using the most basic/default styled elements:

contributors_export
ExportStats_confirm_large_export
ExportStats_confirm_small_export
ExportStats_loading
ExportStats_error
ExportStats_generating_file
ExportStats_success_download

File: packages/lib-user/src/components/Contributors/components/ExportStats/ExportStats.js (hunk 4 above)
Comment (goplayoutside3) [reply packages/lib-user/src/components/Contributors/components/ExportStats/ExportStats.js:119]: Will the `onClose` function cancel the csv generation?

I don't think the button should be disabled, but the `Contributors.ExportStats.generating` could offer guidance such as "Generating stats export file. Do not close this browser tab".

**Review by goplayoutside3 — APPROVED** [review]
Looks great, and I'm able to download the largest group export with the expected UI messages. Also appreciate the in-code comments for easy understanding!

Only NB suggestion would be to add guidance to the "generating" message mentioned below.

**Review by seanmiller26 — APPROVED** [review]
Including a status indication is a major improvement to what we have currently. I do agree with Delilah's comment about guidance so that users don't close the modal prematurely. Besides that, looks Good!
