### PR TITLE
Use UTC for daily stats calculations

### LINKED ISSUE #2244: Daily count stats bug
## Describe the bug

Found while doing follow up testing for #2238. I was testing to make sure I didn't introduce a regression and found a bug that is pre-existing on production. I'm wondering if this is a bug having to do with the localization happening in `DailyClassificationsChartContainer` here:

https://github.com/zooniverse/front-end-monorepo/blob/fae3e5e60dd6423fc6de2ef831fc3ed722da4349/packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.js#L23-L31

Anyway, I made a classification on Monday and the bar chart shows I have one on Sunday and Monday even though I didn't actually on Sunday:

Screen Shot 2021-06-14 at 1 41 57 PM

What it's rendering:

Screen Shot 2021-06-14 at 1 38 07 PM

The original store data is correct:

Screen Shot 2021-06-14 at 1 44 05 PM

And in the response from the stats service:

Screen Shot 2021-06-14 at 1 54 28 PM

So the culprit is likely the above noted function. 

## To Reproduce
1. Go to https://fe-project.zooniverse.org/projects/blicksam/transcription-task-testing/classify/workflow/13898
2. Make a classification (on a Monday in a US timezone maybe?)
3. Check out the daily classifications bar chart
4. There's a count for Sunday and Monday.

## Expected behavior

Only counts render on the days a volunteer has made them. Note the data from the stats service is correct. This is just a rendering bug.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Ignore the local time zone and use UTC when calculating your daily classification counts. With this change, the daily stats chart should always begin on a Monday, regardless of which time zone you're in. Classifications should be shown on the day that you made them, not the day before.

Screenshot of the daily stats chart with mock data, in the project storybook.
http://localhost:9001/?path=/story/project-app-screens-classify-daily-classifications-chart--plain

I've also upgraded the chart component to remove `inject`, and upgraded the stories to remove `storiesOf`.

Package:
app-project

Closes #2244.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
https://local.zooniverse.org:3000/projects/eatyourgreens/-project-testing-ground/classify/workflow/3223?env=staging is a Yes/No workflow on staging, which can be used to check today's classification count. I don't think daily stats are stored for staging projects.

File: packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.js [hunk 1]
```diff
@@ -1,56 +1,44 @@
...
+function DailyClassificationsChartContainer({
+  counts = defaultCounts,
+  projectName,
+  thisWeek = []
+}) {
+  const TODAY = new Date()
+  const stats = thisWeek.map(stat => {
+    const day = new Date(stat.period)
+    const locale = counterpart.getLocale()
+    const count = (day.getUTCDay() === TODAY.getUTCDay()) ? counts.today : stat.count
```
Comment (eatyourgreens) [inline packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.js:19]: I'm not sure if changing both of these to `getUTCDay()` is correct. If the stats server sends back daily stats stamped with `2021-06-14T00:00:00Z`, and the local clock is CDT eg. `2021-06-14T20:00:00-05:00`, should we compare the UTC day (from the server) with the local day? Otherwise, I think the local UTC day will be one day ahead of the day in the server response.
```js
    const count = (day.getUTCDay() === TODAY.getDay()) ? counts.today : stat.count
```

Comment (eatyourgreens) [reply packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.js:19]: So in that example, at 8pm on Monday, any classifications you made after midnight in London would be displayed as Tuesday. I think.

File: packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.js [hunk 2]
```diff
@@ -1,56 +1,44 @@
...
+    const longLabel = day.toLocaleDateString(locale, { weekday: 'long' })
```
Comment (eatyourgreens) [inline packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.js:20]: This might need to add the `timeZone` option, to override the local clock.

File: packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.js [hunk 3]
```diff
@@ -1,56 +1,44 @@
...
+    const alt = `${longLabel}: ${count}`
+    const label = day.toLocaleDateString(locale, { weekday: 'narrow' })
```
Comment (eatyourgreens) [inline packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.js:22]: This might need the `timeZone` option too.

File: packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.js (hunk 2 above)
Comment (eatyourgreens) [reply packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.js:20]: Yep. I changed my Mac's time zone (in date and time preferences) and the graph labels changed to the local clock, one day off from the expected day names. We should be using UTC for the datetimes sent back from the stats API, local clock otherwise.

File: packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.js (hunk 1 above)
Comment (eatyourgreens) [reply packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.js:19]: I've verified that this is still a bug by changing my mac's clock today (Wednesday) to a time zone that's still on Tuesday. Any classifications I made were shown as Wednesday, one day ahead in my local future (cue spooky Twilight Zone music.) Fixed by making the change I outlined in the comments: use UTC to get a day number from the stats API data, but the local clock to get the local day number.

File: packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.js [hunk 4]
```diff
@@ -1,56 +1,45 @@
...
+function DailyClassificationsChartContainer({
+  counts = defaultCounts,
+  projectName,
+  thisWeek = []
+}) {
+  const TODAY = new Date()
+  const locale = counterpart.getLocale()
+  const stats = thisWeek.map(({ count: statsCount, period }) => {
+    const day = new Date(period)
+    const isToday = day.getUTCDay() === TODAY.getDay()
```
Comment (eatyourgreens) [inline packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.js:19]: We could put the day numbers and local names for each day in the store, so that each daily count is `{ count, dayNumber, label, longLabel, period }`. They never change, so only need to be generated once. Maybe something for a future rewrite of this component?

**Review by srallen — COMMENTED** [review]
Unfortunately none of the tests for the `DailyClassificationChartContainer` pass running in Chicago CDT time. Everything is a day later compared to the expectation it looks like. Do you want a copy of the test failure outputs?

**Comment by srallen** [comment]
It's 11:22 AM if that helps.

**Review by srallen — CHANGES_REQUESTED** [review]
I'm still seeing failures, having to do with mismatches between Saturday and Sunday:

```
1) Component > DailyClassificationsChartContainer
       daily stats counts
         2019-10-05
           should have a count:

      AssertionError: expected 25 to equal 8
      + expected - actual

      -25
      +8

      at Context.<anonymous> (src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.spec.js:121:33)
      at processImmediate (internal/timers.js:464:21)

  2) Component > DailyClassificationsChartContainer
       daily stats counts
         2019-10-05
           should have an accessible description:

      AssertionError: expected 'Saturday: 25' to equal 'Saturday: 8'
      + expected - actual

      -Saturday: 25
      +Saturday: 8

      at Context.<anonymous> (src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.spec.js:137:31)
      at processImmediate (internal/timers.js:464:21)

  3) Component > DailyClassificationsChartContainer
       daily stats counts
         2019-10-06
           should have a count:

      AssertionError: expected 15 to equal 25
      + expected - actual

      -15
      +25

      at Context.<anonymous> (src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.spec.js:121:33)
      at processImmediate (internal/timers.js:464:21)

  4) Component > DailyClassificationsChartContainer
       daily stats counts
         2019-10-06
           should have an accessible description:

      AssertionError: expected 'Sunday: 15' to equal 'Sunday: 25'
      + expected - actual

      -Sunday: 15
      +Sunday: 25

      at Context.<anonymous> (src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.spec.js:137:31)
      at processImmediate (internal/timers.js:464:21)
```

**Comment by eatyourgreens** [comment]
That's weird. `sinon.useFakeTimers({ now: new Date('2019-10-06'), toFake: ['Date'] })` is setting the day to Saturday when you run the tests, but not when I run the tests here (in BST) or in CI (in UTC.) My guess would be that it should use `UTCDate`. I'll try that.

**Review by srallen — APPROVED** [review]
The latest updates resolved it. Thanks!

**Comment by eatyourgreens** [comment]
Cool! Let's see if this resolves any issues for people who are seeing their classifications plotted on the wrong day.
