### PR TITLE
Classifier: scale subject width to page zoom

### LINKED ISSUE #3336: Page zoom shrinks the subject viewer
## Package
lib-classifier

## Describe the bug
Zooming into the Classify page, on any project, increases the text size (as expected) but shrinks the subject viewer. Zooming out shrinks the text but enlarges the subject.

https://user-images.githubusercontent.com/59547/174794439-4bef79f2-bd19-475e-8773-a9f1e22f510d.mov

## To Reproduce
1. Go to the Classify page on any project.
2. Use page zoom to zoom in.

## Expected behavior
The subject viewer should be enlarged, more like this screen recording.

https://user-images.githubusercontent.com/59547/174795413-19c200c2-d48f-4ed5-800e-f4c3b9548f97.mov

### Desktop (please complete the following information):
 - OS: MacOS 11.6.6
 - Browser: Firefox
 - Version: 101

## Additional context
The default layout sets the subject size to [`8fr`](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Basic_Concepts_of_Grid_Layout#the_fr_unit), which will shrink to fit remaining space after the task panel has enlarged.
https://github.com/zooniverse/front-end-monorepo/blob/a1af82bf7da492fa3b004fec31e37cb221242dbf/packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js#L23-L25

### PR DESCRIPTION
**Pull request by eatyourgreens**
Add [`minmax()`](https://developer.mozilla.org/en-US/docs/Web/CSS/minmax) sizing to the subject width, so that the subject enlarges along with the rest of the page, when the page is zoomed in. When the page is zoomed out, the subject expands to fill the available width.

https://user-images.githubusercontent.com/59547/174805197-38235f8c-86a5-4b1c-a997-65ba0a7f3125.mov

## Package
lib-classifier

## Linked Issue and/or Talk Post
- Closes #3336.

## How to Review
Use page zoom to zoom in and out on the Classify page for any project. Zooming in should enlarge the subject, not shrink it.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [x] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [x] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [x] Can submit a classification
- [x] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [x] The PR creator has listed user actions to use when testing if bug is fixed
- [x] The bug is fixed
- [x] Unit tests are added or updated

### CODE REVIEW

File: packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js [hunk 1]
```diff
@@ -12,7 +12,8 @@ import QuickTalk from '@components/Classifier/components/QuickTalk'
 import SubjectViewer from '@components/Classifier/components/SubjectViewer'
 import TaskArea from '@components/Classifier/components/TaskArea'
 
-const columnSize = pxToRem(380)
+const subjectSize = pxToRem(680)
+const taskSize = pxToRem(380)
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js:16]: I'm wondering if we need this calculation, or if it would be better to explicitly state the sizes here.
```suggestion
const subjectSize = '45rem'
const taskSize = '25rem'
```

Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js:16]: `pxToRem` just divides the provided number by 15, but 15px isn't the base font size so the columns here don't come out as 680px and 380px wide in the rendered page.
https://github.com/zooniverse/front-end-monorepo/blob/a1af82bf7da492fa3b004fec31e37cb221242dbf/packages/lib-react-components/src/helpers/pxToRem.js#L1-L14

Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js:16]: The rendered grid column widths, in Firefox, are 729px and 405px on my laptop, which corresponds to a base font size of ~16px.

Comment (mcbouslog) [reply packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js:16]: I would have thought the base font size would be [14px based on the theme](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-grommet-theme/src/index.js#L473) but I think you're right, it looks like it's ~16px. Explicitly stating the sizes makes sense to me.

**Review by mcbouslog — APPROVED** [review]
Tested https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats/classify/workflow/693 on Chrome, Edge, Firefox, and Safari - no issues, worked as expected.

File: packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js (hunk 1 above)
Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/Layout/components/DefaultLayout/DefaultLayout.js]: The theme sets 14px for paragraphs but the base font size will be the font size that’s set for the page body.
