### PR TITLE
app-project: Fix broken dark/light mode theme toggle

### LINKED ISSUE #2555: Dark theme cookies aren't applied instantly
## Package
app-project

## Describe the bug
In this video, I switch from dark mode to light, then back to dark mode again. After switching back to dark mode, light mode persists in the page props when I navigate to About and back to Classify.

https://user-images.githubusercontent.com/59547/142620576-d5e3d647-67c4-460b-9b35-c2a42baca74d.mov

## To Reproduce

1. Go to https://planethunters.org
2. Switch between light mode and dark mode.
3. Navigate between pages to check that downloaded page props match the theme mode cookie.

## Expected behavior
Theme changes should be applied instantly, and remembered across page transitions.

## Additional context
Requests for page props, like the following URL, are cached for 60s so there's probably a 60s lag between changing a cookie locally and seeing those changes reflected on our servers.
https://www.zooniverse.org/projects/_next/data/sveH-W7XOnvZ_IHl6uSt1/nora-dot-eisner/planet-hunters-tess/about/research.json?owner=nora-dot-eisner&project=planet-hunters-tess

I think we can fix this by reading `ui.mode` and `ui.dismissedAnnouncementBanner` from local cookies when the page loads, rather than getting them from page props.

Alternatively, use [`mst-persist`](https://github.com/agilgur5/mst-persist) to persist the store in the browser, including the UI settings.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Remove server-side cookie handling and the `initialState.ui` page prop. Read cookies in the browser on app mount and apply to the store. This should remember your selected theme across projects, rather than using cached page props from the CDN.

To test this out, toggle the theme between light and dark, then check that it persists across page transitions, and also after refreshing the page.

Package:
app-project

Closes #2555.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Review by goplayoutside3 — COMMENTED** [review]
## PR Review

I'm able to toggle the dark/light mode. Refreshing the page remembers my theme mode preference, and that preference is consistent while navigating around FEM pages. ✔️ That preference is not saved across browser tabs.

Clarification question: The refactor of `readCookies()` in the UI Store includes `getCookie('dismissedAnnouncementBanner')`. Dismissing a banner is not remember after page refresh on this branch though. Is there a plan for implementing banner dismissal? Is it a relatively quick refactor that could be included here?

**Comment by eatyourgreens** [comment]
I’ll double check but I think that’s the code that was already there. I’ve no plans to do any more work on it.

**Comment by eatyourgreens** [comment]
I think this line does the same thing, on the live site?

https://github.com/zooniverse/front-end-monorepo/blob/f421b4dea4d0f19b9589709baf9138842d3b8fe6/packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.js#L15

**Comment by goplayoutside3** [comment]
> I’ll double check but I think that’s the code that was already there. I’ve no plans to do any more work on it.

I'm referring to the `getCookies()` function that you added to the UI Store.

**Comment by eatyourgreens** [comment]
Yeah, that’s the same function that ran on the server. The only change is that `request` is replaced with `document`. 

I’ve tried dismissing the announcement banner on my test project and the cookie does seem to be ignored. 
https://frontend.preview.zooniverse.org/projects/eatyourgreens/-project-testing-ground/classify/workflow/3586/subject-set/4925?env=staging&demo=true


The tests for that cookie are passing, here and on the main branch, so I’m not sure where the problem is.

**Comment by eatyourgreens** [comment]
I wonder if the announcement banner cookie has always been broken and we've never noticed?

**Comment by eatyourgreens** [comment]
I can see that `dismissedProjectAnnouncement` session cookie in the browser, but it's definitely being ignored when I reload the page, or switch to a new tab.

https://frontend.preview.zooniverse.org/projects/eatyourgreens/-project-testing-ground/classify/workflow/3586/subject-set/4974?env=staging
Screenshot of the browser storage console, showing that a 'dismissedProjectAnnouncementBanner' cookie is set for the session.

**Comment by eatyourgreens** [comment]
Wait! Should the cookie name be `dismissedProjectAnnouncementBanner` or `dismissedAnnouncementBanner`? Is inconsistent naming the bug? If so, I think that's something that can be easily fixed in this PR.

**Comment by eatyourgreens** [comment]
@goplayoutside3 I've added a failing test for the announcement banner cookie. How has the code gone for so long with this typo in it, not caught by any tests?

**Comment by eatyourgreens** [comment]
@goplayoutside3 `ui.readCookies()` should be reading and parsing both cookies properly now. I think that the announcement banner cookie has been broken for a very long time.

**Comment by eatyourgreens** [comment]
Roger pointed out, in https://github.com/zooniverse/front-end-monorepo/pull/1235, that the announcement banner doesn't need to be stored in global window state. The code might be easier to understand if the announcement banner component was responsible for both reading and writing the cookie, via `useEffect`. Hooks weren't around when the monorepo first started but we could use them now.

File: packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.js [hunk 1]
```diff
@@ -8,24 +7,15 @@ const HOSTS = {
   staging: 'https://frontend.preview.zooniverse.org'
 }
 
-export default async function getDefaultPageProps({ params, query, req }) {
-
-  // cookie is in the next.js context req object
-  const mode = getCookie(req, 'mode') || null
-  const dismissedAnnouncementBanner = getCookie(req, 'dismissedAnnouncementBanner') || null
```
Comment (eatyourgreens) [inline packages/app-project/src/helpers/getDefaultPageProps/getDefaultPageProps.js:15]: This has probably never worked, because the store property is called `dismissedProjectAnnouncementBanner`.

**Comment by goplayoutside3** [comment]
I can confirm that banner dismissal and theme mode are remembered while navigating between FEM pages, but now refreshing the page reverts the theme to light mode and the banner reappears. Was that intentional with your latest changes?

**Comment by eatyourgreens** [comment]
@goplayoutside3 this might be the problem. The toggle has created two mode cookies, on `.zooniverse.org` and `local.zooniverse.org`. I've got both 'light' and 'dark' set now, which causes unpredictable results.

I didn't touch the cookie writing code here, but it seems like it has bugs.

Screenshot of cookies for a local build of the project app, showing two mode cookies: one dark, one light.

**Comment by eatyourgreens** [comment]
This gets weirder. If I inspect `document.cookie` in the console, it returns `'mode=light'` even though I can see a `dismissedProjectAnnouncementBanner` cookie for `local.zooniverse.org` under Storage.

**Comment by eatyourgreens** [comment]
The banner cookie path is not set correctly. If I change it to `/projects/eatyourgreens/-project-testing-ground?env=staging`, I can read the cookie, but only on the home page. This must also have been broken ever since that code was first written.

**Comment by eatyourgreens** [comment]
@goplayoutside3 I've done some debugging and the UI store sets the banner cookie path to `/${slug}` but the path to a project on our site is `/projects/${slug`, of course!

**Comment by eatyourgreens** [comment]
Weird that that didn't fail any tests, either.

**Review by goplayoutside3 — APPROVED** [review]
Glad the dismissed banner could also be included here! Looks good. I'm able to keep my theme mode and banner dismissal preferences across FEM pages and during page refresh.
