### PR TITLE
Markdownz: avoid creating username-links with ping in email addresses

### LINKED ISSUE #2212: Markdownz incorrectly parsing email addresses in markdown
## Describe the bug

If an email address is spelled out, the markdownz `ping` custom plugin for rendering links to user profile pages thinks email addresses are user accounts.

## To Reproduce
Run the project app in development mode, `yarn dev` and visit http://localhost:3000/projects/nora-dot-eisner/planet-hunters-tess/about/research?env=production

Scroll to the bottom of the page for the last paragraph which has an example.

## Expected behavior

Email addresses should just be plain text while user accounts get rendered as links to their profile page. The regex being used needs to be updated:

https://github.com/zooniverse/front-end-monorepo/blob/5568331f7161e20b46934acef17b85d872e92591/packages/lib-react-components/src/Markdownz/lib/ping.js#L15

Maybe to look for a space before the at symbol?

## Screenshots

Screen Shot 2021-05-26 at 1 08 51 PM

### PR DESCRIPTION
**Pull request by goplayoutside3**
Package:
lib-react-components

Closes #2212.

Describe your changes:

I modified `ping`'s matching regex string to match usernames and hashtags while avoiding email addresses. I added more markdown examples to `example.md`, so the expected links can be tested by running `yarn storybook`.

@srallen it looks like the previous `matchRegex` variable deconstructed in `ping` was being overwritten by the plugin’s default regex. I simply added `\B` to the plugin’s default regex to find usernames but skip email addresses. 

One `ping.spec` test was affected, which was making sure "links aren’t created inside links". Everything in storybook looks as expected to me, but it’s possible I’ve missed something by changing the expected output of that test here:
https://github.com/zooniverse/front-end-monorepo/blob/89ebaa86e89a94a1dcd284b80039c3f00706626d/packages/lib-react-components/src/Markdownz/lib/ping.spec.js#L138

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

File: packages/lib-react-components/src/Markdownz/lib/ping.js [hunk 1]
```diff
@@ -12,17 +12,18 @@ export default function plugin({
   ping, // Rename this from pingUsername to ping since we may be pinging more than users
   pingSymbols = ['@'], // Add a parameter to specify what the ping symbols are to be able to support custom ping symbols and more than one.
   resourceURL, // Rename from userURL to resourceURL
-  matchRegex = /@(?:\*\*([^*]+)\*\*|(\w+))/,
+  matchRegex // plugin default is /@([\w\-.]+\b)|#([-\w\d]{3,40})|(\^S[0-9]+)/
 }) {
   if (typeof ping !== 'function' || typeof resourceURL !== 'function') {
     throw new Error(helpMsg)
   }
+  const customMatchRegex = /\B@([\w\-.]+\b)|#([-\w\d]{3,40})|(\^S[0-9]+)/ // match must not be inside an email address
```
Comment (srallen) [inline packages/lib-react-components/src/Markdownz/lib/ping.js:20]: The original function parameter, `matchRegex` isn't used anymore, so the regex passed in to the function call in the `Markdownz` component isn't used: 

https://github.com/zooniverse/front-end-monorepo/blob/fa4a46044042c00f295a7f94ed7db6905b61988f/packages/lib-react-components/src/Markdownz/Markdownz.js#L120

We should clean this up so it's clear what this plugin is doing. I don't exactly recall why I setup the plugin this way to set the regex by way of function parameter, but I would guess it was to be able to support customization, so this could be handled a few ways:

- Remove the parameter default (already done), set the argument in `Markdownz` ping function call to be the updated `customMatchRegex` and use it by way of the `matchRegex` parameter in the ping plugin. 
- Remove the argument for `matchRegex` in `Markdownz` and set `customMatchRegex` to be the default parameter. Could be done either on line 15:
`matchRegex = /\B@([\w\-.]+\b)|#([-\w\d]{3,40})|(\^S[0-9]+)/`
Or line 20:
`const customMatchRegex = matchRegex || /\B@([\w\-.]+\b)|#([-\w\d]{3,40})|(\^S[0-9]+)/`

`Markdownz` could be updated to have a settings' prop for ping as a future update?

**Review by srallen — CHANGES_REQUESTED** [review]
This is looking good, but there's a tiny bit of cruft that now needs cleaning up, probably from a customization support that I left unfinished from the initial setup (see comment on line 117 in `Markdownz`). Details are in a comment inline.

**Review by srallen — APPROVED** [review]
LGTM. Thanks!
