### PR TITLE
Markdownz: catch parsing errors

### LINKED ISSUE #3673: "document is not defined" on Maria Edgeworth Team page.
## Package
app-project

## Describe the bug
Loading the Maria Edgeworth Letters Team page displays a "document is not defined" error.

The Maria Edgeworth Letters Team page showing a 'document is not defined' error.

## To Reproduce
1. Go to https://www.zooniverse.org/projects/mariaedgeworthletters/maria-edgeworth-letters/about/team

## Expected behavior
The project team page should load.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Add a try/catch block to Markdownz so that markdown parsing errors don't crash the parent app, making the page unusable. When there is a parsing error, the error message is displayed instead of the original content.

The Maria Edgeworth Letters team page, showing 'document is not defined' instead of the page content.

## Package
lib-react-components

## Linked Issue and/or Talk Post
- closes #3673.

## How to Review
With these changes, markdown errors in the Maria Edgeworth Letters team page will be caught during server-side rendering, and the page content should at least show correctly when React runs in the browser and renders the content for a second time.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

**Comment by eatyourgreens** [comment]
NB. if you want to test the HTML that's generated by SSR, turn off JS in your browser (so that React doesn't run when the page loads.)

File: packages/lib-react-components/src/Markdownz/Markdownz.js [hunk 1]
```diff
@@ -111,26 +111,32 @@ class Markdownz extends React.Component {
...
+        .processSync(newChildren).result
+
+      return (
+        <React.Fragment>
+          {markdown}
+        </React.Fragment>
+      )
+    } catch (error) {
+      console.error(error)
+      return <p>{error.message}</p>
```
Comment (shaunanoordin) [inline packages/lib-react-components/src/Markdownz/Markdownz.js:137]: [rambling to self] I'm trying to imagine situations where you might not want to render a `<p>` to display an error message... but in the context of app-project and lib-classifier, I can't think of any. This is fine. 👌

**Review by shaunanoordin — APPROVED** [review]
## PR Review

Package: `lib-react-components`, but mostly affects `app-project` etc
Closes #3679 and closes #3673

This PR fixes the issue where, if there's a Markdown component trying to render HTML entities (e.g. `&amp;`), the whole page crashes _if_ you try to access the page URL directly (or reload).

- Code read is straightforward: the `remark` Markdown renderer is just wrapped in a try-catch
- Functionality checks out:
  - _If you have JS enabled,_  the Markdown text will render correctly. `&amp;` for example will be rendered as `&` (👌 this means most users won't see a problem.)
  - _if you don't have JS enabled,_ the Markdown text will be replaced with the text "document is not defined". ( ⚠️ this may be relevant when our projects are indexed by Google or etc)

### Testing

Tested on macOS + Chrome _(with JavaScript enabled)_ using a random test project.

Testing Steps:
- Go into the [Project Builder](https://master.pfe-preview.zooniverse.org/lab/1966) of the test project
- Change the Announcement Banner to some text that uses a HTML entity _bracketed by & and ;,_ e.g. `Don't use HTML entities &amp; stuff`
- Open the [test project's home page.](https://local.zooniverse.org:3000/projects/darkeshard/test-project-2022)
- The Announcement Banner should be displayed properly as `Don't use HTML entities & stuff`. Nothing should crash.
  - Optional: test with JS switched off. The Announcement Banner should now say "document is not defined"

Screenshot 2022-09-20 at 21 40 50

### Status

LGTM 👍
