### PR TITLE
lib-user: Add DeactivatedGroup component for active membership with deactivated group

### LINKED ISSUE #6249: MyGroups displays a de-activated group
## Package
_Choose from the list:_
- [x] lib-user

## Describe the bug

When signed in to https://fe-root.preview.zooniverse.org, I see four groups on MyGroups (`/groups`) page. Three of them are expected and I can click their group card to see their GroupStats component. However, there's also a group MB Prod Test Group 1 that doesn't exist when I click the group card. This might be a legacy group from the very first days of development, but I should only see group cards for active groups I'm a member of.

## Screenshots

Signed-in with my account and not in admin mode:
Screenshot 2024-08-29 at 11 34 44 AM

### PR DESCRIPTION
**Pull request by mcbouslog**
## Package
- lib-user

## Linked Issue and/or Talk Post
- closes #6249 

## Describe your changes
- adds component for active membership with deactivated group providing brief (too brief?) message and Leave Group button
- I could not determine a way to differentiate between a user with an active membership in a deactivated group from a user with an active membership in a brand new group, so I think this is the best solution for #6249, though open to suggestion on a different approach or scrapping this in favor or more consideration 

## How to Review
_Helpful explanations that will make your reviewer happy:_
- What Zooniverse project should my reviewer use to review UX?
- What user actions should my reviewer step through to review this PR?
- Which storybook stories should be reviewed?
- Are there plans for follow up PR’s to further fix this bug or develop this feature?

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

File: packages/lib-user/src/components/shared/GroupContainer/components/DeactivatedGroup.js [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+
+  return (
+    <Box
+      align='center'
+      direction='column'
+      gap='medium'
+    >
+      <SpacedText uppercase={false}>
+        This is a deactivated group.
+        Please leave the group or contact the group administrator if you believe this is an error.
```
Comment (mcbouslog) [inline packages/lib-user/src/components/shared/GroupContainer/components/DeactivatedGroup.js:33]: I'm not sure about this message, I think it's ok, but let me know what you think.

**Review by goplayoutside3 — APPROVED** [review]
I think this is fine to merge! As noted in our Slack convo, there's discussion around whether preventing a membership from being created for a deactivated group can be handled by panoptes (https://github.com/zooniverse/panoptes/pull/4385), but in the rare case where someone may end up a member of a deactivated group, this is a definite solution.
