### PR TITLE
Fix static paths

### LINKED ISSUE #1214: Static file paths are broken in production
**Package**
app-project

**Describe the bug**
Static images aren't being loaded in production.
Screenshot showing missing image placeholders for recent classifications.

**To Reproduce**
Load https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify while not logged in, so that the Recent Classifications box is initially empty.

**Expected behavior**
Empty recent classifications should show a grey placeholder, with the Zooniverse logo.

### PR DESCRIPTION
**Pull request by rogerhutchings**
Closes #1214

Moves the `static` folder to `public`, and updates the placeholder image URLs (see [Next docs](https://github.com/zeit/next.js#static-file-serving-eg-images))

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Looks good, but probably needs fixing in the storybook too.

File: packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.js [hunk 1]
```diff
@@ -38,7 +36,7 @@ function RecentSubjects (props) {
               height={height}
               key={recent.subjectId}
               isLoggedIn={isLoggedIn}
-              placeholder={<img alt='' role='presentation' src='/static/subject-placeholder.png' />}
+              placeholder={<img alt='' role='presentation' src='/subject-placeholder.png' />}
```
Comment (eatyourgreens) [inline packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.js]: This will resolve to https://www.zooniverse.org/subject-placeholder.png, which I think will 404.

**Comment by rogerhutchings** [comment]
This will require a next version bump, so will do an upgrade in a separate PR. From reading issues though, I think the `static` folder still requires the `ASSET_PREFIX` to be prepended to urls; the new `public` folder feature doesn't.

**Comment by eatyourgreens** [comment]
This won't fix #1214, by the way. It just removes the deprecated `static` directory. Should it be bundled in with #1217, since it requires the NextJS upgrade?

File: packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.js (hunk 1 above)
Comment (rogerhutchings) [reply packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.js]: it's been updated to use the `assetPrefix`

File: packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.js [hunk 2]
```diff
@@ -15,6 +13,9 @@ counterpart.registerTranslations('en', en)
 function RecentSubjects (props) {
   const { isLoggedIn, recents, projectName, size, slug } = props
   const height = (size === 1) ? '40vw' : '200px'
+  const placeholderUrl = process.env.ASSET_PREFIX
+    ? `${process.env.ASSET_PREFIX}/subject-placeholder.png`
```
Comment (eatyourgreens) [inline packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.js]: Isn't this still  https://frontend.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify which resolves to https://static.zooniverse.org/preview.zooniverse.org/panoptes-front-end/master/static/subject-placeholder.png.

File: packages/app-project/package.json [hunk 3]
```diff
@@ -42,7 +42,7 @@
     "mobx-react": "~5.2.8",
     "mobx-state-tree": "~3.5.0",
     "newrelic": "~5.10.0",
-    "next": "~9.0.3",
+    "next": "~9.1.1",
```
[the remark this answers is not in the document]
Comment (rogerhutchings) [reply packages/app-project/package.json]: should have been - might have got monkeyed with by a master merge on here

File: packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.js (hunk 2 above)
Comment (rogerhutchings) [reply packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.js]: nope. the kube config for staging sets `ASSET_PREFIX` to `https://fe-project.preview.zooniverse.org`, so this becomes `https://fe-project.preview.zooniverse.org/subject-placeholder.png`, which gets resolved.

Prepending the `ASSET_PREFIX` without using the new `public` folder would work too: https://fe-project.preview.zooniverse.org/static/subject-placeholder.png

Comment (eatyourgreens) [reply packages/app-project/src/screens/ClassifyPage/components/RecentSubjects/RecentSubjects.js]: That's interesting, because https://frontend.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify is trying to load them from the static files directory in PFE. Is that because it isn't prefixing the URLs with the correct hostname?
