### PR TITLE
Reset the Classifier key after logging out

### LINKED ISSUE #2962: The classifier user is not signed out when the project app signs out
## Package
app-project
lib-classifier

## Describe the bug
When you log out of a project page, that change is not passed down to the classifier. You can test this by logging the key on the `Classifier` component in the classify page. When you're logged in, the key is your user ID. When you log out, it should be changed to `no-user`.

On workflows with tutorials, the tutorial should also open when you sign out, since it is shown to all anonymous users.

## To Reproduce
1. Go to https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify/workflow/11235
2. Sign out.

## Expected behavior
When you sign out, the logged-in user should be cleared in the classifier.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Explicitly pass a userID prop to the `ClassifierWrapper` component in the Classify page. Set the `Classifier` key from this prop, so that the classifier unmounts and remounts when you log out.

To test this out: sign out from PH-TESS. You should see that the classifier resets and reloads without a logged-in user.

Package:
app-project

Closes #2962.

# Review Checklist

## General

- [x] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [x] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
@goplayoutside3 this should fix the tutorial opening on top of the sign-in form, if you log in after the classifier has loaded and the classifier store has been created.

File: packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js [hunk 1]
```diff
@@ -147,6 +148,12 @@ ClassifierWrapper.propTypes = {
   subjectID: string,
   /** optional subject set ID (from the page URL.) */
   subjectSetID: string,
+  /** Current logged-in user */
+  user: shape({
+    error: string
```
Comment (mcbouslog) [inline packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js:153]: Getting console "Warning: Failed prop type: Invalid prop `user.error` of type `object` supplied to `ClassifierWrapper`, expected `string`."

**Review by mcbouslog — APPROVED** [review]
LGTM! 

Noted minor console warning regarding `user.error` type.

**Comment by eatyourgreens** [comment]
I’ll have a follow-up to fix #2954 so I’ll fix that prop type there.
