### PR TITLE
Classifier: better handling of invalid tasks

### LINKED ISSUE #3251: Client-side application error on refresh with drawing mark
## Package
- lib-classifier?

## Describe the bug
Create a transcription line with subtask text, refresh the page (will prompt "Reload?", click "Reload"), then client-side application error.
To clear error must clear browser session storage.

Bug - https://www.zooniverse.org/projects/humphrydavy/davy-notebooks-project?demo=true
Similar project without bug - https://www.zooniverse.org/projects/rachaelsking/corresponding-with-quakers?demo=true

## To Reproduce
1. Go to https://www.zooniverse.org/projects/humphrydavy/davy-notebooks-project/classify/workflow/21240?demo=true
2. Create line, in subtask add text, click "Save and Close"
3. Refresh page (will be prompted "Reload?", click "Reload")

## Expected behavior
Do same steps as noted above on https://www.zooniverse.org/projects/rachaelsking/corresponding-with-quakers/classify/workflow/20713?demo=true - no error

### LINKED ISSUE #3292: Classifier: invalid task types crash the project Classify page
## Package
lib-classifier

## Describe the bug
The classifier is very strict about the `task.type` field. If a workflow loads from Panoptes with a task type that doesn't match any supported types, the classifier page crashes with a generic error message:

```
Application error: a client-side exception has occurred (see the browser console for more information).
```

## To Reproduce
1. Visit https://frontend.preview.zooniverse.org/projects/eatyourgreens/-project-testing-ground/classify/workflow/3489?env=staging
2. In the same tab, change the URL to https://frontend.preview.zooniverse.org/projects/eatyourgreens/-project-testing-ground?env=staging and try to load any other workflow for the test project.

## Expected behavior
The classifier should fail gracefully, displaying an error message in place of the unsupported task:
https://github.com/zooniverse/front-end-monorepo/blob/8b8d22cbbe5660cf4e8d937095f4b2223c5d8a66/packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Task/Task.js#L52-L54

### PR DESCRIPTION
**Pull request by eatyourgreens**
- Catch undefined tasks in the `Task` component, and display an error message in place of the task.
- Catch invalid snapshot errors, when the store loads, and create a new, empty store.

## Package
lib-classifier

## Linked Issue and/or Talk Post
- Closes #3292.
- Closes #3251.

## How to Review
The task bug only exists in the production build of the classifier, so build the classifier then run the project app (either development or production build) and load this test workflow, which contains a task where the type is 'dropdown'.
https://local.zooniverse.org:3000/projects/eatyourgreens/-project-testing-ground/classify/workflow/3489?env=staging

Screenshot of the classifier showing an error message in place of one task: T0 dropdown is not a supported task type.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

File: packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Task/Task.js [hunk 1]
```diff
@@ -33,10 +33,19 @@ function Task ({
...
-  const { TaskComponent } = task.type === 'dropdown-simple'? tasks.dropdownSimple : tasks[task.type]
+  const TaskPlugin = task.type === 'dropdown-simple'? tasks.dropdownSimple : tasks[task.type]
+  const TaskComponent = TaskPlugin?.TaskComponent
   let annotation
   let suggestions
 
+  if (!TaskComponent) {
+    return (
+      <Paragraph>
+        <code>{task.taskKey} {task.type}</code> is not a supported task type.
```
Comment (shaunanoordin) [inline packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Task/Task.js:44]: [minor][enhancement] This string is a good candidate to be _t(translatified)_

**Review by shaunanoordin — COMMENTED** [review]
## PR Review

Package: lib-classifier

This PR fixes an issue where 1️⃣ the Classifier would crash when it encounters a Workflow with a Dropdown Task.

- Code change is very straightforward and adds some sensible existence checks 👍 
- 2️⃣ Additionally, we have a fallback for the Classifier Store. The Store has the option of initialising from a "saved state" (used only in specific projects) to preserve the Classifier between page transitions. Now, when that fails, we fall back to a default state instead of crashing.

### Testing

(Planned) On macOS + Chrome 102

- Load (app-project) https://local.zooniverse.org:3000/projects/eatyourgreens/-project-testing-ground/classify/workflow/3489?env=staging
- If that example WF with a Dropdown works fine, this PR is a go.
- The [current version on master](https://frontend.preview.zooniverse.org/projects/eatyourgreens/-project-testing-ground/classify/workflow/3489?env=staging) crashes with the error `Cannot read properties of undefined (reading 'TaskComponent')` in the console, so we have a very solid baseline.

### Status

LGTM, just let me run some local tests and I'll get this approved.

**Review by shaunanoordin — APPROVED** [review]
## PR Review (Update)

Tests are good 👍 Let's gooo!
