### PR TITLE
Lint ClassifierWrapper callbacks

### LINKED ISSUE #5036: Missing dependencies in classifier callback hooks
## Package
app-project

## Describe the bug
```sh
./src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js
62:6  Warning: React Hook useCallback has missing dependencies: 'recents' and 'yourStats'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
72:6  Warning: React Hook useCallback has a missing dependency: 'router'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
80:6  Warning: React Hook useCallback has a missing dependency: 'collections'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
```

## To Reproduce
Build the project app.

## Expected behavior
The NextJS app should build without warnings.

## Additional context
Missing dependencies in hooks can lead to subtle bugs eg. #4977.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Refactor `useCallback` hooks in `ClassifierWrapper` to remove warnings (from `eslint-react`) and clean up their dependency arrays.

Refactor subject URL routing to use a `useEffect` hook, triggered by changes in the classifier subject (see #4977.)

## Package
app-project

## Linked Issue and/or Talk Post
- closes #5036.

## How to Review
- [x] The project app should build without warnings.
- [x] Classifier callbacks should continue to work as before.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [x] Can submit a classification
- [x] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

File: packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js [hunk 1]
```diff
@@ -49,35 +51,36 @@ export default function ClassifierWrapper({
...
       favorite: subject.favorite,
       subjectId: subject.id,
       locations: subject.locations
     })
-  }, [recents?.add, yourStats?.increment])
+  }, [addRecents, incrementStats])
 
+  const replaceRoute = router.replace
+  const baseURL = `/${ownerSlug}/${projectSlug}/classify/workflow/${workflowID}`
   const onSubjectChange = useCallback((subject) => {
```
Comment (goplayoutside3) [inline packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js:70]: I noticed `onSubjectChange` is called every time the locale changes in the url (same behavior exists in #5038 I tested there first).

I don't think this function is intended to run when locale changes, but probably caused because `router` is a dependency of the `useCallback`. This also means the `useEffect` in lib-classifier's ClassifierContainer handling `classifierStore.setOnSubjectChange` runs when locale changes too. Any consequences to this chain of function calls, or is it a harmless/unavoidable side effect?

Comment (eatyourgreens) [reply packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js:70]: The callback should depend on the `replaceRoute` function, not the whole `router` object.

Comment (eatyourgreens) [reply packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js:70]: This function should generate a new `onSubjectChange` callback whenever the classifier URL changes. Unfortunately, the callback changes the URL when it runs, so changing the selected subject will generate a new callback for each subject.

Comment (eatyourgreens) [reply packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js:70]: > I noticed onSubjectChange is called every time the locale changes in the url (same behavior exists in #5038 I tested there first).

I'm not sure I follow this. `onSubjectChange` is the handler for the previous and next buttons in the subject banner. It shouldn't be linked to a props change anywhere.

Comment (goplayoutside3) [reply packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js:70]: Hmmm. The behavior I noticed is actually logged by the classifier, but I'm trying to understand if it's connected to the `onSubjectChange` function above. For instance, if I visit TESS's classify page, and then change the locale with the dropdown, I see the following logged in the browser console:
```
cleaning up onSubjectChange
setting onSubjectChange
```

The logs are from a `useEffect` in lib-classifier ClassifierContainer with dependencies `[classifierStore.setOnSubjectChange, onSubjectChange]` and the logging happens on every locale change even though the subject remains the same. 

Because `onSubjectChange` is passed as a prop from app-project's ClassifierWrapper, I thought that it must be changing every time locale is updated in app-project. For further testing I added a console log to line 71 inside the `useCallback` of `onSubjectChange` however nothing is logged to the console when locale is changed. 

What would cause the `setting onSubjectChange` logging if the subject is not changing, and only the locale?

Comment (eatyourgreens) [reply packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js:70]: That’s not running the `onSubjectChange` function. That’s creating the `onSubjectChange` function.

Comment (eatyourgreens) [reply packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js:70]: The closure’s lexical scope (its dependencies) is changing, which creates a new closure. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures

Comment (eatyourgreens) [reply packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js:70]: Incidentally, that was the cause of #4977 too. An old copy of `onSubjectChange` was running, where `subjectID` was still undefined.

Comment (eatyourgreens) [reply packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js:70]: `onSubjectChange` depends on `router.replace`. Maybe that changes when the locale changes?

This PR is fixing the warning that `router` is missing from the dependency list, so a new callback should be created when the router changes.

Comment (eatyourgreens) [reply packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js:70]: I’ll have another look at that. It could be that we want `router.replace` to run as a side effect of the subject changing, rather than directly in the callback.

Comment (eatyourgreens) [reply packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js:70]: I do find the current callback confusing, and hard to debug, because it has so many external dependencies.

Comment (eatyourgreens) [reply packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js:70]: This example from the `useCallback` docs looks like it’s handling exactly the same problem:
https://react.dev/reference/react/useCallback#preventing-an-effect-from-firing-too-often

File: packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js [hunk 2]
```diff
@@ -27,57 +29,74 @@ export default function ClassifierWrapper({
...
     }
-  }, [ownerSlug, projectSlug, router?.replace, subjectID, subjectSetID, workflowID])
+  }, [baseURL, replaceRoute, subjectRouteChanged])
 
+  /*
+    Track the current classification subject, when it changes inside the classifier.
+  */
+  const onSubjectChange = useCallback((subject) => {
+    setClassifierSubjectID(subject?.id)
+  }, [setClassifierSubjectID])
```
Comment (eatyourgreens) [inline packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js:93]: Do `setState` calls have to be declared as dependencies in hooks that set state?

Comment (eatyourgreens) [reply packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js]: Apparently not:
>React guarantees that `setState` function identity is stable and won’t change on re-renders. This is why it’s safe to omit from the `useEffect` or `useCallback` dependency list.

https://legacy.reactjs.org/docs/hooks-reference.html#usestate

**Review by goplayoutside3 — APPROVED** [review]
Looks good! I tested #4977 again to be sure
