### PR TITLE
Classifier: always check for a logged-in user on mount

### LINKED ISSUE #2954: Classifier: previously seen tutorial opens after logging in.
## Package
lib-classifier

## Describe the bug
On a project like PH TESS, where I've already seen the tutorial, the tutorial will still open if I log in after the `Classifier` store has been created.

## To Reproduce
1. While signed out of Panoptes, visit https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify/workflow/11235.
2. Dismiss the tutorial, which opens for all anonymous users.
3. Sign in.
4. The tutorial opens again, even if your project preferences mark it as seen.

## Expected behavior
The tutorial should only open if I haven't seen it before.

## Additional context
When you sign in, `upp.loadingState` should be reset, while your preferences load, so that `tutorial.hasNotBeenSeen` returns false here:
https://github.com/zooniverse/front-end-monorepo/blob/afddbb4683c5664eea33d6889257316d5f5b5f11/packages/lib-classifier/src/store/TutorialStore/Tutorial/Tutorial.js#L21-L23

If the UPP loading state is still set to 'success', from the initial user check when the classifier mounted, then `tutorial.hasNotBeenSeen` will be true while your preferences load, which will then trigger the tutorial to open.

### PR DESCRIPTION
**Pull request by eatyourgreens**
- When the classifier mounts, reset the UPP store to clear any stale user state that might persist in the global store.
- Update the `ResourceStore` model to reset loading state on reset.
- refactor `tutorial.hasNotBeenSeen`.

This fixes #2954 by forcing the classifier to check for a logged-in user after mounting, even if the classifier mounts with an existing store from a previous session in the same window/tab. The popup tutorial should wait for that user check to complete before opening.

To test this: log out then log back in on a project where you've already seen the tutorial. The tutorial should open when you log out, but should stay closed when you log back in.

Package:
lib-classifier

Closes #2954.

# Review Checklist

## General

- [x] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [x] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
@mcbouslog @goplayoutside3 I've tagged you because you've both looked at the tutorial code recently. Feel free to reassign this if you have too much on your plates already.

File: packages/lib-classifier/src/components/Classifier/ClassifierContainer.js [hunk 1]
```diff
@@ -71,13 +71,18 @@ export default function ClassifierContainer({
 
   const loaded = useHydratedStore(classifierStore, cachePanoptesData, `fem-classifier-${project.id}`)
 
+  useEffect(function onMount() {
+    console.log('resetting stale user data')
+    classifierStore?.userProjectPreferences.reset()
+  }, [])
+
   useEffect(function onLoad() {
-    const { classifications, subjects, workflows } = classifierStore
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/components/Classifier/ClassifierContainer.js:75]: This was slightly unsafe, because it will crash if `classifierStore` is undefined. I removed it just to be on the safe side.

**Review by mcbouslog — APPROVED** [review]
Code changes LGTM.

Confirmed tutorial not prompted on production when signing out. Confirmed these changes fix tutorial prompts as expected - tutorial prompted after sign out, not prompted when sign in.
