### PR TITLE
Classifier: Refactor subject snapshots

### LINKED ISSUE #2799: Davy Notebooks crashes when you change workflow
## Package
lib-classifier

## Describe the bug
Davy Notebooks crashes the classifier if you change workflow after visiting Talk.
```
Application error: a client-side exception has occurred (see the browser console for more information).
```
The error in the browser console is:

>[mobx] uncaught error in 'Reaction[Autorun]' Error: [mobx-state-tree] Failed to resolve reference 'ckzcsioky00052a6owot7r8hj' to type '(DataVisAnnotation | DrawingAnnotation | MultipleChoiceAnnotation | SimpleDropdownAnnotation | SingleChoiceAnnotation | SubjectGroupComparisonAnnotation | SurveyAnnotation | TextAnnotation | TranscriptionAnnotation)' (from node: /subjects/resources/68872134/stepHistory/steps/ckzcsiol100072a6ook74zkoc/annotations/0)

## To Reproduce
1. Go to https://www.zooniverse.org/projects/humphrydavy/davy-notebooks-project?demo=true
2. Choose a workflow and classify a page.
3. Choose Done & Talk.
4. Go back to the classifier.
5. Go back to the home page and choose a different workflow.

Applicable Panoptes resource IDs (project, workflow, etc) to demonstrate the issue:

## Expected behavior
The page shouldn't crash.

## Additional context
I think what's happening here is that snapshots of `subject.stepHistory` are being saved in session storage, but step history contains references to annotations, which will break when the snapshot is applied to the store on classifier load.

### PR DESCRIPTION
**Pull request by eatyourgreens**
- refactor `subject.stepHistory` as `subject.startClassification()`, which starts a new undo history when a subject becomes active.
- remove `subject.stepHistory` from snapshots.
- refactor `subject.transcriptionReductions` so that they are only fetched from Caesar when empty.
- explicitly set `subjects.active` to undefined on reset, despite it being `types.safeReference`.

Testing URL:
https://local.zooniverse.org:3000/projects/humphrydavy/davy-notebooks-project?env=production&demo=true

Package:
lib-classifier

Closes #2799.

# Review Checklist

## General

- [x] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [x] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

File: packages/lib-classifier/src/store/SubjectStore/SubjectStore.js [hunk 1]
```diff
@@ -322,6 +322,11 @@ const SubjectStore = types
     }
 
     function reset () {
+      /*
+      This line stops the classifier from crashing when changing workflows.
+      TODO: It's a safeReference, so why is it not being cleared automatically?
+      */
+      self.active = undefined
```
Comment (mcbouslog) [inline packages/lib-classifier/src/store/SubjectStore/SubjectStore.js:329]: I'm not sure why yet, or if it's this line specifically, but when testing this branch with Davy Notebooks locally if I:
- go to workflow A
- draw a line (start a classification)
- go back to the project home page
- go to workflow B => I get an error including `TypeError: Cannot read properties of undefined (reading 'latest')`

Changing [TasksConnector line 27](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/TasksConnector.js#L27) to `const latest = subject?.stepHistory?.latest` (adding optional chaining to stepHistory) appears to fix the issue.

I didn't see an issue related to it, but [Task](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Task/Task.js#L27) maybe could use the optional chaining as well.

**Review by mcbouslog — APPROVED** [review]
Code changes LGTM, confirmed fixes issue, tested on Davy Notebooks and HMS NHS bouncing between workflows, monitoring session storage, with and without in progress classifications, and to talk (404 page locally) and back and more bouncing between workflows. Only issue noted is detailed in comment.

File: packages/lib-classifier/src/store/SubjectStore/SubjectStore.js (hunk 1 above)
Comment (eatyourgreens) [reply packages/lib-classifier/src/store/SubjectStore/SubjectStore.js:329]: That’s interesting. I’d have thought that change would stop you from classifying at all, because that one is used to get the current step and its annotations.

**Comment by eatyourgreens** [comment]
Let’s see if this fixes the page crashes on staging.
