### PR TITLE
Project: fix collections search

### LINKED ISSUE #4865: Collections Modal Search feature not working
## Package
app-project

## To Reproduce
Your user account should have at least a couple of collections to test this. Visit any project’s classify page. Click on “Add to Collections” button to open the Collections modal. Type into the search field and the list of options does not respond to the search text as expected.

Screenshot 2023-06-20 at 3 02 22 PM

## Expected behavior
Search field text matching the display name of your collections should filter the list of options appropriately. Also, an empty search field should list all of your collections.

### PR DESCRIPTION
**Pull request by eatyourgreens**
- the `search` parameter should not be included in the API call when the text box is empty.
- the `SelectCollections` component should observe the project store for changes.
- Use Postgres full text search for long search strings. Otherwise, filter collection display names by short search strings. 

https://github.com/zooniverse/front-end-monorepo/assets/59547/34022d1d-b3bb-4dd4-9f1a-fc492e50b6b0

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
app-project

## Linked Issue and/or Talk Post
- closes #4865.

## How to Review
While logged in, search your collections from the 'Add to collection' button underneath any subject on the Classify page (including subject previews.) You should be able to search both collections that you own, and collections that have been shared with you.

Clearing the text box should send an API query without the `search` parameter, which will list all your collections (up to a limit of the current page size, max. 100 in Panoptes.)

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [x] The PR creator has listed user actions to use when testing if bug is fixed
- [x] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

**Review by goplayoutside3 — CHANGES_REQUESTED** [review]
The bugs still exist on this branch.

When type "New" into the search query, it does not find my collection titled New Collection:
Screenshot 2023-06-21 at 3 22 29 PM

When I backspace the search field to empty, none of my collections are listed:
Screenshot 2023-06-21 at 3 21 51 PM

**Comment by eatyourgreens** [comment]
I’m unable to reproduce the bug on this branch, I’m afraid. The video at the top of the PR shows me using the collections search without problems.

**Comment by eatyourgreens** [comment]
@goplayoutside3 I've added a hack when the search text is 3 characters or less. Essentially the same workaround that you used in #4846: filter collection names by the search text.

When the search text is 4 characters or more, the search uses the Panoptes API to find matching collections.

NB. this bug (or feature?) in the API also affects collections search on PFE projects.

**Comment by eatyourgreens** [comment]
That approach seems to give the best UX. Short strings like 'New' are directly matched in the collection display name. Long searches like 'test card' use Postgres full text search to return full and partial matches.

**Comment by goplayoutside3** [comment]
I think this strategy is a good plan as discussed in FE standup today 👍 

I have a question though about behavior I see on both `master` and this branch. If I run app-project locally with `yarn dev`, and visit a production project such as Planet Hunters TESS, I can't open the collections modal because of the following error:
Screenshot 2023-06-22 at 2 38 23 PM

The error doesn't show if the `env`'s match though. For instance, i-fancy-cats with `yarn dev` works fine, as does Planet Hunters TESS with `yarn start`. Why might that be?

**Comment by eatyourgreens** [comment]
Oh, that’s weird. That error shows up pretty regularly in Sentry too. 

I think #4866 will fix it, by removing class components and component instance methods.

**Comment by eatyourgreens** [comment]
My best guess would be that the component ref isn’t being set on the first render, but I’m not sure.

**Comment by goplayoutside3** [comment]
No problem. I do think that #4866 will help with that particular error.

As for the search feature in this PR, I think the code in SelectCollection still needs some work. If I understand correctly, I have three collections and using the search field with the text "new" should filter my collections that have "new" in their name. Then, when I backspace to clear the search field, I should see the list of all my collections again (<100). However, I don't see either of those expected behaviors on this branch:

https://github.com/zooniverse/front-end-monorepo/assets/23665803/27571341-8707-492b-8663-c0178130a166

**Comment by eatyourgreens** [comment]
Hmmm, 'cat’ and 'tes' worked for me. Does 'New' work?

File: packages/app-project/src/shared/components/CollectionsModal/components/SelectCollection/SelectCollection.js [hunk 1]
```diff
@@ -10,10 +12,23 @@ function SelectCollection ({
...
+    onSearch({
+      favorite: false,
+      current_user_roles: 'owner,collaborator,contributor',
+      search: text.length > 3 ? text : undefined
+    })
+    setSearchText(text)
+  }
+  const options = searchText.length > 3 ?
+    collections :
+    collections.filter(collection => collection.display_name.includes(searchText))
```
Comment (eatyourgreens) [inline packages/app-project/src/shared/components/CollectionsModal/components/SelectCollection/SelectCollection.js:30]: I think `String.includes()` is case sensitive. Maybe downcase both strings before matching?

Comment (eatyourgreens) [reply packages/app-project/src/shared/components/CollectionsModal/components/SelectCollection/SelectCollection.js:30]:
```suggestion
    collections.filter(collection => collection.display_name.toLowerCase().includes(searchText.toLowerCase()))
```

**Comment by eatyourgreens** [comment]
I've updated the string matching to ignore case.

Here's a quick screen recording from Firefox.


https://github.com/zooniverse/front-end-monorepo/assets/59547/34022d1d-b3bb-4dd4-9f1a-fc492e50b6b0

**Comment by eatyourgreens** [comment]
@goplayoutside3 are the problems that you're seeing because of the code changes here, or because the API request isn't returning results when it should?

I don't think there's much that we can do here about bugs in the API, except maybe try to work around them.

**Comment by eatyourgreens** [comment]
Updated the screen recording at the top of the PR to include long strings, short strings and mixed case searches.
