### PR TITLE
app-content-pages: resolve skipped unit tests

### LINKED ISSUE #4765: Publications category menu should have an accessible label
## Package
app-content-pages
## Describe the bug
The sidebar navigation on the publications page is missing an accessible label for the category menu.
```html
<nav class="StyledBox-sc-13pk1d4-0 ezNNQt">
  <ul class="StyledBox-sc-13pk1d4-0 bjWreY">
    <li class="sc-5b224d84-0 LmnZY"><a class="StyledButton-sc-323bzc-0 eerEGI sc-5b224d84-1 jTtzKn" href="/about/publications">Show all</a></li>
    <li class="sc-5b224d84-0 LmnZY"><a class="StyledButton-sc-323bzc-0 fxCSHo sc-5b224d84-1 kCWXRm" href="/about/publications#space">Space</a></li>
    <li class="sc-5b224d84-0 LmnZY"><a class="StyledButton-sc-323bzc-0 fxCSHo sc-5b224d84-1 kCWXRm" href="/about/publications#physics">Physics</a></li>
    <li class="sc-5b224d84-0 LmnZY"><a class="StyledButton-sc-323bzc-0 fxCSHo sc-5b224d84-1 kCWXRm" href="/about/publications#climate">Climate</a></li>
    <li class="sc-5b224d84-0 LmnZY"><a class="StyledButton-sc-323bzc-0 fxCSHo sc-5b224d84-1 kCWXRm" href="/about/publications#humanities">Humanities</a></li>
    <li class="sc-5b224d84-0 LmnZY"><a class="StyledButton-sc-323bzc-0 fxCSHo sc-5b224d84-1 kCWXRm" href="/about/publications#nature">Nature</a></li>
    <li class="sc-5b224d84-0 LmnZY"><a class="StyledButton-sc-323bzc-0 fxCSHo sc-5b224d84-1 kCWXRm" href="/about/publications#medicine">Medicine</a></li>
    <li class="sc-5b224d84-0 LmnZY"><a class="StyledButton-sc-323bzc-0 fxCSHo sc-5b224d84-1 kCWXRm" href="/about/publications#social-science">Social Science</a></li>
    <li class="sc-5b224d84-0 LmnZY"><a class="StyledButton-sc-323bzc-0 fxCSHo sc-5b224d84-1 kCWXRm" href="/about/publications#language">Language</a></li>
    <li class="sc-5b224d84-0 LmnZY"><a class="StyledButton-sc-323bzc-0 fxCSHo sc-5b224d84-1 kCWXRm" href="/about/publications#meta">Meta</a></li>
    <li class="sc-5b224d84-0 LmnZY"><a class="StyledButton-sc-323bzc-0 fxCSHo sc-5b224d84-1 kCWXRm" href="/about/publications#data">Data</a></li>
  </ul>
</nav>
```

## To Reproduce
Inspect the sidebar menu here:
https://frontend.preview.zooniverse.org/about/publications

## Expected behavior
Since https://github.com/zooniverse/front-end-monorepo/pull/4673, the menu should be labelled something like 'Filter by category'.

### PR DESCRIPTION
**Pull request by goplayoutside3**
## Package
app-content-pages

## Linked Issue and/or Talk Post
Closes #4765 
Follow-up to #4643 

## Describe your changes
- Added aria-label to sidebar in Teams and Publications screen components
- Resolved previous unit tests that were skipped due to removing counterpart
- Removed unused i18n-for-tests.js file
- Reduce number of publications in mock data so that RTL doesn't take so long to render PublicationsContainer

The unit tests for Next.js /pages are still skipped, but I'm still debating whether those are necessary at all.

## How to Review

- Run this branch locally and visit https://local.zooniverse.org:3000/about/test/publications?env=production
- Check that all tests pass
- app-content-pages storybook loads

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

File: packages/app-content-pages/src/screens/Publications/Publications.js [hunk 1]
```diff
@@ -55,7 +55,7 @@ function Publications({ className = '', data = [], filters = [] }) {
   )
 
   const sidebar = (
-    <Nav ariaLabel={t('Publications.sideBarLabel')}>
+    <Nav aria-label={t('Publications.sideBarLabel')}>
```
Comment (eatyourgreens) [inline packages/app-content-pages/src/screens/Publications/Publications.js:58]: Not a blocking comment, but is there a test to find this labelled navigation menu?

**Review by eatyourgreens — APPROVED** [review]
Looks good!

File: packages/app-content-pages/src/screens/Publications/Publications.js (hunk 1 above)
Comment (goplayoutside3) [reply packages/app-content-pages/src/screens/Publications/Publications.js:58]: Good point~ I don't think there is yet, so I'll add before merging!
