### PR TITLE
Stronger checking for classifier data fetching 

### LINKED ISSUE #5015: Intermittent bug: empty labels for workflow tasks
## Package
lib-classifier 

## Describe the bug
The classifier sometimes loads without any text in the task labels. 

I Fancy Cats, without any text for the question or its answers.
## To Reproduce
I think you basically have to load and reload the classifier until this triggers. 

## Expected behavior
Workflow tasks should be labelled. 

## Additional context
This code checks for `workflowSnapshot` but doesn't check `workflowSnapshot.strings`, so the classifier might render before the workflow strings have been set.
https://github.com/zooniverse/front-end-monorepo/blob/3847048f66f7e59bf1574adc5fbafa0e900891c1/packages/lib-classifier/src/components/Classifier/ClassifierContainer.js#L133-L139

### PR DESCRIPTION
**Pull request by eatyourgreens**
Set the current `userID` to undefined while the user is loading. Check that in both `useProjectPreferences` and `useProjectRoles` so that the possible return values are:
- undefined (resource is loading.)
- null (user isn't logged in.)
- a Panoptes resource (user is logged in.)

Wait until workflow translations have loaded before rendering the classifier (closes #5015.)
 
_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
lib-classifier

## How to Review
I checked this in the dev classifier. With these changes, you shouldn't see any requests made for either project preferences or project roles until the user is authenticated, and set to either null or a Panoptes user resource.

You shouldn't see GET requests like this, where the user ID is `false` because the user session hasn't authenticated yet.
https://panoptes-staging.zooniverse.org/api/project_preferences?project_id=335&user_id=false&http_cache=true

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [x] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [x] Can submit a classification
- [x] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Refactoring
- [x] The PR creator has described the reason for refactoring
- [x] The refactored component(s) continue to work as expected

### CODE REVIEW

File: packages/lib-classifier/src/components/Classifier/hooks/usePanoptesUserSession.js [hunk 1]
```diff
@@ -6,7 +6,7 @@ import {
 
 export default function usePanoptesUserSession({ authClient, projectID }) {
   const { data: user, isLoading: userLoading } = usePanoptesUser(authClient)
-  const userID = !userLoading && user?.id
+  const userID = userLoading ? undefined : user?.id
```
Comment (mcbouslog) [inline packages/lib-classifier/src/components/Classifier/hooks/usePanoptesUserSession.js:9]: I'm not sure I'm thinking about this correctly, but I think 
- if the user is loading we want `userID` to be undefined ✔️ , 
- if the user isn't loading then there are two possible scenarios
  - we have a user in which case we want `userID` to be the user.id ✔️  
  - we want `userID` to be null ✖️ (for an anonymous / logged out user) which I think the following change would do...

```suggestion
  const userID = userLoading ? undefined : user?.id || null
```

Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/hooks/usePanoptesUserSession.js]: Ha! I just pushed exactly this change, then saw your comment.

Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/hooks/usePanoptesUserSession.js]: But yeah, you’re exactly right. We need to be able to distinguish between a value that’s falsy because it’s still loading and a value that’s falsy because you aren’t actually logged in.

Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/hooks/usePanoptesUserSession.js]: This change gets the tests passing again for anonymous users. Without it, you never get past ‘Loading…’.

**Review by mcbouslog — APPROVED** [review]
This LGTM!
Tested signed out and signed in. Noted the expected number of `project_preferences` requests. Couldn't replicate empty translations strings issue, but didn't note instance of when testing locally.
