### PR TITLE
fix(app-root): wait for login to complete before fetching authenticated user data

### LINKED ISSUE #6337: Unread notifications vanish on the app-root pages
## Package
- app-root

## Describe the bug
Unread notifications vanish when I go from Talk to the new home page, then reappear when I go back to Talk.

## To Reproduce
Here's a video where I've got 2 unread notifications in the top bar, but they don't appear on the home page.

https://github.com/user-attachments/assets/0f77a4c9-baa8-45a6-946f-3d0725446191

## Expected behavior
Unread notifications should be consistent across the various different React apps that make up the Zooniverse site.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Wait for the current Panoptes user to be signed-in before fetching unread messages and notifications. See https://zooniverse.github.io/panoptes-javascript-client/#panoptes-javascript-client-auth-authcheckbearertoken

Update user hooks that had the same race condition. Move token fetching code into a hook.

I've moved token fetching into a hook so that the auth token can be used in the SWR cache key, invalidating cached values when auth state changes. See the example in [the SWR docs for multiple fetcher arguments](https://swr.vercel.app/docs/arguments#multiple-arguments).

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
- lib-react-components
- lib-user

## Linked Issue and/or Talk Post
- fixes #6337.
- #6336.

## How to Review
Unread notifications should now be fetched with your bearer token. In production, the bearer token can be an empty string when you first fetch notifications, so they come back as 0 when `app-root` loads in the browser, and the SWR cache then returns 0 until it expires and refreshes from Panoptes.

`lib-user` hasn’t changed at all, except that auth’ed requests now wait until you have a refresh token from Panoptes. Previously, `auth.checkBearerToken()` could run before `auth.checkCurrent()` had received your refresh token. In that case, auth’ed requests would fail. 

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

**Comment by eatyourgreens** [comment]
The fix I've applied here may also need to be applied to recent projects and recent classifications, in order to fix #6336.

**Comment by eatyourgreens** [comment]
I’ve updated this to include all the hooks in `lib-user`. I think the only request that isn’t fixed now is recent subjects.

**Review by goplayoutside3 — COMMENTED** [review]
When I run this PR locally there are two bugs I noticed with groups 🚨 

- On the homepage run locally https://local.zooniverse.org:3000 (staging), my groups all have 0 classifications and members, which I know is not true.
- On the homepage run locally forced to production, https://local.zooniverse.org:3000/?env=production, my groups component is empty, which again is known not to be true.

Please double check for bugs before re-requesting review.

**Comment by eatyourgreens** [comment]
I'm not seeing that bug but I'll double check. Probably something obvious that I've missed.

File: packages/lib-user/src/hooks/usePanoptesAuthToken.js [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+import { useRef } from 'react'
+
+const isBrowser = typeof window !== 'undefined'
+
+if (isBrowser) {
+    auth.checkCurrent()
+}
+
+export default function usePanoptesAuthToken() {
+    const tokenRef = useRef('')
```
Comment (eatyourgreens) [inline packages/lib-user/src/hooks/usePanoptesAuthToken.js:11]: I think this should be using state, not a ref.

**Comment by eatyourgreens** [comment]
@goplayoutside3 I took a look at the `MyGroups` component and I've got a couple of comments:
- it has a story but the story doesn't mock data-fetching, so doesn't catch bugs in the auth token code.
- it has no tests, so CI passes even if the component isn't fetching groups.

File: packages/lib-user/src/hooks/usePanoptesAuthToken.js [hunk 2]
```diff
@@ -0,0 +1,35 @@
+import auth from "panoptes-client/lib/auth"
+import { useState } from "react"
+
+const isBrowser = typeof window !== "undefined"
+
+let defaultToken
+/*
+  Top-level await in modules has been supported in Node
+  and in all browsers since 2021. However, ES modules are still
+  not supported in the monorepo. An immediately-invoked async
```
Comment (goplayoutside3) [inline packages/lib-user/src/hooks/usePanoptesAuthToken.js:10]: Perhaps this is picky, but I think "ES Modules are still not supported in the monorepo" is a misleading phrase that's been thrown around over the past two years. Yes ,ESM are incompatible with our test suites, see https://github.com/zooniverse/front-end-monorepo/issues/3779, but not a problem for FEM apps and libraries in a browser.

**Review by goplayoutside3 — COMMENTED** [review]
@eatyourgreens I don't see the bugs I mentioned on my previous review anymore, but could you rebase to fix the merge conflicts with this branch so I can do a full review?

File: packages/lib-user/src/hooks/usePanoptesAuthToken.js (hunk 2 above)
Comment (eatyourgreens) [reply packages/lib-user/src/hooks/usePanoptesAuthToken.js:10]: None of the monorepo packages are ES modules. They all use `type: commonjs` in their package files by default, even if they have ES6 exports. Top level await is only available in modules, so I couldn’t use it here. 

If I could use top level await, the code would simplify to this, which would be great. 

```js
await auth.checkCurrent()
const defaultToken = await auth.checkBearerToken()
```

Comment (eatyourgreens) [reply packages/lib-user/src/hooks/usePanoptesAuthToken.js:10]: By the way, Node 23 is out now and finally fixes static imports for CJS.

Comment (goplayoutside3) [reply packages/lib-user/src/hooks/usePanoptesAuthToken.js:10]: > However, server-side rendering of ES modules in Node would require either type: module in package files, or .mjs extensions on modules.

Doesn't app-root do this?

Comment (eatyourgreens) [reply packages/lib-user/src/hooks/usePanoptesAuthToken.js:10]: The changes here are in `lib-user`, which uses CommonJS in Node.

Comment (eatyourgreens) [reply packages/lib-user/src/hooks/usePanoptesAuthToken.js:10]: You're right about `app-root`. Top level await will work in that package.

Comment (eatyourgreens) [reply packages/lib-user/src/hooks/usePanoptesAuthToken.js:10]: Here's the build warning that I get from Next.js when I use top level await here.

```sh
printf 'Building `fe-root`...\n'
Building `fe-root`...
yarn workspace @zooniverse/fe-root build
$ APP_ENV=${APP_ENV:-development} NODE_ENV=${NODE_ENV:-production} PANOPTES_ENV=${PANOPTES_ENV:-production} next build
  ▲ Next.js 14.2.15

   Creating an optimized production build ...
 ⚠ Compiled with warnings

../lib-user/dist/esm/hooks/usePanoptesAuthToken.js
The generated code contains 'async/await' because this module is using "topLevelAwait".
However, your target environment does not appear to support 'async/await'.
As a result, the code may not run as expected or may cause runtime errors.
```

**Comment by eatyourgreens** [comment]
@goplayoutside3 merge conflicts should be fixed now.

**Review by goplayoutside3 — APPROVED** [review]
Thanks!

**Comment by goplayoutside3** [comment]
@eatyourgreens I'm revisiting this PR while working on refactoring user stats in app-project (https://github.com/zooniverse/front-end-monorepo/pull/6472) because authorization is needed for ERAS requests. The `usePanoptesAuth()` hook in app-project is missing `auth.checkCurrent()` prior to `auth.checkBearerToken()`.

https://github.com/zooniverse/front-end-monorepo/blob/dff3098940f532df6b9644d3248ea7402eb5fb3d/packages/app-project/src/hooks/usePanoptesAuth.js#L7-L11

I think I'll just add `auth.checkCurrent()` to that hook, but wanted to double check my understanding of https://zooniverse.github.io/panoptes-javascript-client/#panoptes-javascript-client-auth-authcheckbearertoken you linked in the description of this PR. Is app-project's `usePanoptesAuth()` the same scenario where `auth.checkCurrent()` should be called first?

**Comment by eatyourgreens** [comment]
Yeah. I don’t know why this wasn’t built into the client but you must always run:

```js
await auth.checkCurrent() // get the current session and refresh token
const token = await auth.checkBearerToken() // exchange the refresh token for a bearer token
```

I went to a talk during the pandemic that really clarified OAuth for me. I’ll see if I can find it again.

**Comment by eatyourgreens** [comment]
Here you go. Kim Maida: the art of authentication. 
https://youtu.be/Y52inonPftU
