### PR TITLE
Project: clear stored User on log out

### LINKED ISSUE #3608: Classify page: Recent subjects aren't cleared when I log out
## Package
app-project

## Describe the bug
When I log out, my recent subjects remain on the Classify page.

Your Statistics and Recent Classifications, under the classifier. I'm signed out, but my three most recent subjects are still listed.

## To Reproduce
1. Go to https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify/workflow/11235
2. Log out, then scroll down to see that recent subjects are still displayed.

## Expected behavior
All personalisation should be cleared when I log out, including recent classifications.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Use `applySnapshot` to clear the stored user on sign out, including collections, recents and personalisation.

## Package
app-project

## Linked Issue and/or Talk Post
- closes #3608.

## How to Review
- Log in and out of a project that you've classified on. Recent subjects should only be displayed while you are logged in.
- Also check that the classifier loads properly for both logged-in and logged-out volunteers.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [x] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [x] Can submit a classification
- [x] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [x] The PR creator has listed user actions to use when testing if bug is fixed
- [x] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

File: packages/app-project/stores/User/User.js [hunk 1]
```diff
@@ -33,10 +33,18 @@ const User = types
...
-      self.login = null
-      self.loadingState = asyncStates.success
+      const loggedOutUser = {
+        id: null,
+        display_name: null,
+        login: null,
+        loadingState: asyncStates.success,
+        personalization: {
+          projectPreferences: {
+            loadingState: asyncStates.success
```
Comment (eatyourgreens) [inline packages/app-project/stores/User/User.js:43]: Without this, the classifier never loads for anonymous volunteers. 🤔

**Review by mcbouslog — APPROVED** [review]
Confirmed issue, confirmed fix, signed in and out a few times, code LGTM 👍

File: packages/app-project/stores/User/User.js (hunk 1 above)
Comment (eatyourgreens) [reply packages/app-project/stores/User/User.js:43]: I think it could be changed by fetching preferences in a hook, similar to how the user is fetched from Panoptes.
