### PR TITLE
fix(app-root): missing dependency warnings in useEffect hooks

### LINKED ISSUE #6241: User stats: missing dependency errors in useEffect
## Package
_Choose from the list:_
- app-root
## Describe the bug
Build warnings are generated during a production build:
```
./src/app/groups/[groupId]/GroupStatsContainer.js
40:6  Warning: React Hook useEffect has a missing dependency: 'updateQueryParams'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./src/app/users/[login]/stats/UserStatsContainer.js
38:6  Warning: React Hook useEffect has a missing dependency: 'updateQueryParams'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./src/app/users/[login]/stats/certificate/CertificateContainer.js
47:6  Warning: React Hook useEffect has a missing dependency: 'updateQueryParams'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
```

## To Reproduce
Build the app with `yarn build`.

## Expected behavior
[`useEffect` hooks must declare all reactive dependencies](https://react.dev/reference/react/useEffect#specifying-reactive-dependencies) in their dependency array, or redefine dependencies so that they aren't reactive values.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Fix some build warnings in the user stats pages by moving `updateQueryParams` out of the render function for container components. Otherwise, a new `updateQueryParams` function is created on every render, but the new function won't be invoked by the `useEffect` hook.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
- app-root

## Linked Issue and/or Talk Post
- closes #6241.

## How to Review
This is a straight refactor of the container components, so the user pages shouldn't have changed at all. The app should build without linter warnings, though.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [x] The PR creator has listed user actions to use when testing if bug is fixed
- [x] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

File: packages/app-root/src/app/groups/[groupId]/GroupStatsContainer.js [hunk 1]
```diff
@@ -35,45 +49,30 @@ function GroupStatsContainer({
...
-      } else {
-        queryParams.set(key, value);
-      }
+      const newQueryParams = updateQueryParams([['start_date', selectedStartDate]])
+      router.push(`${window.location.pathname}?${newQueryParams.toString()}`)
     }
-
-    router.push(`${window.location.pathname}?${queryParams.toString()}`)
-  }
+  }, [selectedStartDate, startDate, router])
```
Comment (eatyourgreens) [inline packages/app-root/src/app/groups/[groupId]/GroupStatsContainer.js:55]: The missing dependency, that's generating the original error, is the client-side router here.

**Review by mcbouslog — APPROVED** [review]
Thank you for this refactor! I'm going to merge this then address the back button issue (these changes help towards that) 🙇‍♂️ .

Confirmed locally user and group stats pages continue to work as expected with these changes.
