### PR TITLE
fix(a11y): clickable labels for simple dropdown menus

### LINKED ISSUE #5706: Dropdown task labels aren't clickable/tappable
## Package
_Choose from the list:_
- [ ] app-content-pages
- [ ] app-project
- [x] lib-classifier
- [ ] lib-panoptes-js
- [ ] lib-react-components
- [ ] unknown

## Describe the bug
When I click or tap on the text task instruction, the dropdown menu of suggestions opens and I can select an option.

https://github.com/zooniverse/front-end-monorepo/assets/59547/782424d7-2b34-4c82-87d8-93fb2df00852

When I click or tap the instruction for a dropdown menu, nothing happens. I have to click inside the control itself, in order to activate it.

https://github.com/zooniverse/front-end-monorepo/assets/59547/b3f8a672-37c7-4a07-875b-0ceaf518d0a6

## To Reproduce
Click or tap the task instruction for [the dropdown task](https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/story/tasks-simple-dropdown--short-options) in the classifier storybook.

## Expected behavior
UX should be consistent between tasks. Form controls should also have accessible labels. Clicking the label for a dropdown task should open the menu and focus the control.

### LINKED ISSUE #7160: Simple dropdown task does not handle autoFocus
## Package

- lib-classifier

## Describe the bug

When rendered as the first task in a step the simple dropdown task does not receive focus.

## Expected behavior

The first task of a step receives `autoFocus=true` from the `Tasks` component, causing it to receive focus on render.

## To Reproduce

1. On the development server go to https://localhost:8080/?project=1995&workflow=3770
2. Notice that the dropdown does not have focus.

## Additional information

The cause of the bug is that the `SimpleDropdownTask` component does not pass the `autoFocus` prop down to the `Select` component. 

Note that the grommet `Select` component currently has a bug ([issue](https://github.com/grommet/grommet/issues/7851)) that stops the `autoFocus` prop from focusing the component. So fixing this in FEM (at least via `autoFocus`) is contingent on the fix in grommet, although the code modifications could still be made in advance.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Replaces the simple dropdown's `legend` with a `label` element, linked to the Grommet `Select` component.

Adds the `autoFocus` prop to the labelled select menu.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._

## Package
- lib-classifier

## Linked Issue and/or Talk Post
- closes #5706.
- closes #7160.

## How to Review
Simple dropdown menus should have clickable labels now.

https://github.com/user-attachments/assets/f7b7351e-63e5-4426-a234-afd1d7d687df

## WCAG criteria to test

- [ ] [1.3.1 Info and Relationships](https://www.w3.org/WAI/WCAG22/Understanding/info-and-relationships.html) (level A.)

## Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

### General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `pnpm panic && pnpm bootstrap`
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

### General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

### Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

File: packages/lib-classifier/src/plugins/tasks/dropdown-simple/components/SimpleDropdownTask.jsx [hunk 1]
```diff
@@ -69,8 +69,12 @@ function SimpleDropdownTask({
...
       className={className}
     >
-      <StyledText as='legend' size='small'>
-        <Markdownz>
+      <StyledText
+        as='label'
+        size='small'
+        htmlFor={`${task.taskKey}-select`}
+      >
+        <Markdownz inline>
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/plugins/tasks/dropdown-simple/components/SimpleDropdownTask.jsx:86]: Both `legend` and `label` only accept inline content as children, so `Markdownz` needs to be set to inline here.
