### PR TITLE
fix modal-subtask buttons on touch devices 

### LINKED ISSUE #3344: Transcription Task: Subtask modal buttons do not work in mobile browser
## Package
lib-classifier
(maybe lib-react-components)

## Describe the bug
When completing a transcription task, the subtask modal has two buttons: "Save and Close" and "X" close button. When using a mobile browser, these buttons do not work as expected.

## To Reproduce

1. Use a mobile browser such as Safari or Brave
2. Visit any transcription project such as https://frontend.preview.zooniverse.org/projects/wgranger-test/anti-slavery-testing/classify/workflow/3392?env=staging
3. Click an existing transcription line to open the modal, and the modal buttons do not work
4. Create a new transcription line to open the modal, and the modal buttons do not work
5. See the same behavior in the Transcription Line story: https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/story/drawing-tools-transcription-line--subtask

## Expected behavior
The "Save and Close" and "X" buttons should close the modal or prompt the user if they want to continue without saving work.

## Screenshots
Modal buttons will not close this modal:
modal

### Smartphone (please complete the following information):
 - Device: iPhone 12
 - OS: 15
 - Browser: Safari or Brave
 - Version: latest

## Additional context
Maybe related to #3246

### PR DESCRIPTION
**Pull request by MaysaB**
Staging branch URL: 
https://github.com/zooniverse/front-end-monorepo/tree/fix-3344

## Package
lib-classifier
lib-react-components

## Linked Issue and/or Talk Post
Fixes #3344 

## Changes
Problem -  the subtask modal buttons on 'Save and Close' and 'X' do not work on mobile devices. Pointer actions outside of task area for pop up is being overidden and being replaced by drag actions.

Analysis - The 'Save and Close' button, as well as the 'Close' (x) button were missing the property that the task area has (className="subtaskpopup-element-that-ignores-drag-actions"). This property doesn't allow the pointer actions to be overridden.

Solution - add the property to both the Save and Close button in a <Box> element and also to the <CloseButton> element so that they ignore the drag actions (but only on those elements.)

See screen recording below. 
View on an iPhone12Pro 390x844 at 125%

https://user-images.githubusercontent.com/49612167/186196257-f3a9338d-8460-4691-9768-a18a667aa10b.mov

## How to Review
_Helpful explanations that will make your reviewer happy:_

- Zooniverse Projects to review UX

This is production env: 
(https://local.zooniverse.org:3000/projects/maceb/drawing-project/classify/workflow/3614?reload=0&workflow=3614)

This is staging env.
https://local.zooniverse.org:8080/?env=staging&project=maceb%2Fdrawing-project&workflow=3614

To view the solved bug:

1. Go to the staging environment
2. Create a new project, add a drawing tool task, add a subtask to the drawing tool task, ensure you've added a subject. 
3. Go to classify. Draw something on your subject. Click on the drawing to bring up the subtask. 
4. Go to developer tools and change the dimensions to AirPad or iPhone12.
5. Close the subtask using the 'save and close'.
6. Click the drawing again, close the subtask using the (x) on the top right hand corner of the component.

 **Ensure you have done yarn build on both lib-classifier and lib-react-components, then run yarn dev on app-project to run production env**

To test on mobile, Safari v.15.6:

1. Find your laptop’s IP address (on MacOS you can hold option + click on wifi symbol)
2. Run app-project locally
3. Connect your mobile device to the same wifi network as your laptop
4. Visit the project url on your mobile device, for example: https://your.ip.address.here:3000/projects/brooke/i-fancy-cats or https:/your.ip.address.here:3000/projects/maceb/drawing-project/classify/workflow/3614?reload=0&workflow=3614

## Which storybook stories should be reviewed?
This is lib-react components:

http://localhost:6006/?path=/story/components-movablemodal--sub-task&globals=locale:en;locales.en:English;locales.test:Test+Language

This is lib-classifier:

http://localhost:6007/?path=/story/drawing-tools-transcription-line--subtask&globals=locale:en;locales.en:English;locales.test:Test+Language

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ 822 tests are passing, 14 pending due to .skip ]
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox v.104, Chrome v.104, Safari v.15.6 
- [ ] FEM works in a mobile browser, Safari v.15.6.

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
https://local.zooniverse.org:3000/projects/maceb/drawing-project/classify/workflow/3614?reload=0&workflow=3614

- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible

## Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

## New Feature
- [ ] The PR creator has listed user actions to use when testing the new feature
- [ ] Unit tests are included for the new feature
- [ ] A storybook story has been created or updated
  - Example of SlideTutorial [component](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/components/Classifier/components/SlideTutorial/SlideTutorial.js) with docgen comments, and its [story](https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/docs/other-slidetutorial--default)

## Refactoring
- [ ] The PR creator has described the reason for refactoring
- [ ] The refactored component(s) continue to work as expected

## Maintenance
- [ ] If not from dependabot, the PR creator has described the update (major, minor, or patch version, changelog)

### CODE REVIEW

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.js [hunk 1]
```diff
@@ -106,7 +106,10 @@ function SubTaskPopup({
         rndProps={rndProps}
         titleColor=''
       >
-        <Box gap='small'>
+        <Box 
+        className='subtaskpopup-element-that-ignores-drag-actions'
+        gap='small'
+        >
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.js:112]:
```suggestion
        <Box 
          className='subtaskpopup-element-that-ignores-drag-actions'
          gap='small'
        >
```

Missing indentation here.

**Review by eatyourgreens — COMMENTED** [review]
Code changes look good to me. I'm not sure why the tests are failing. There's nothing obvious in the changes that should break any tests. I think this can be merged once we've figured out why the tests failed.

**Comment by eatyourgreens** [comment]
Tests like this one have broken but this is a bad test anyway. 
https://github.com/zooniverse/front-end-monorepo/blob/7869f1aeef833f16a089f4e92c5e70a53e2bb7e2/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/components/SubTaskPopup/SubTaskPopup.spec.js#L71

**Comment by eatyourgreens** [comment]
@MaysaB #3570 should fix the tests. Let me know if you have any questions about it.

**Review by eatyourgreens — APPROVED** [review]
Looks good to me!
