### PR TITLE
fix(classifier): add z-index to QuickTalk

### LINKED ISSUE #6973: QuickTalk modal opens behind recent classifications thumbnails
## Package
lib-classifier

## Describe the bug
When a user clicks on the QuickTalk icon, the modal opens underneath the recent classifications subject thumbnails.

## To Reproduce

Open a QuickTalk enabled workflow, ie. [
The Material Culture of Wills](https://www.zooniverse.org/projects/hjsmith/the-material-culture-of-wills-england-1540-1790/classify/workflow/28041 )
Make sure your browser window width isn't too wide
Open QuickTalk panel

Repeat on mobile for the same results.

## Screenshots

https://github.com/user-attachments/assets/82a9472d-f9be-4af3-8b41-74d280cffbed

## Expected behavior
This modal should be on top of every other element on the screen.

### Desktop:
 - OS: [MacOS 14.4.1]
 - Browser [Chrome, Safari]
 - Version [138.0.7204.101, 17.4.1]

### Smartphone:
 - Device: [Samsung Galaxy s20+]
 - OS: Android 13
 - Browser: Chrome
 - Version: xx

### PR DESCRIPTION
**Pull request by eatyourgreens**
Add `z-index: 10;` to `QuickTalk`, so that it is stacked above other content on the page.

## Package
- lib-classifier

## Linked Issue and/or Talk Post
- fixes #6973.

## How to Review
On a workflow with Quick Talk, the Talk dialog should now appear above Recent Classifications subjects, not behind them. See #6973 for details (and screenshots of this change in Firefox and Chrome.)

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

File: packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalk.js [hunk 1]
```diff
@@ -16,6 +16,7 @@ const FixedBox = styled(Box)`
   right: 2.5em;
   max-width: 80vw;
   max-height: 80vh;
+  z-index: 10;
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/components/Classifier/components/QuickTalk/QuickTalk.js:19]: This doesn't need to be 10, specifically. Any positive numerical value, other than `0`, should work.
