### PR TITLE
Disable task area while subject is loading

### LINKED ISSUE #511: Tasks should be disabled while subject is loading
**Package**
lib-classifier

**Feature or Issue Description**
Testing the classifier with the network disconnected,I found that you can continue to classify even if the subject area is displaying a broken image icon.

For image subjects, the task area should be disabled/hidden while the image file is loading.

### PR DESCRIPTION
**Pull request by eatyourgreens**
- [x] Add a `ready` flag ro the subject viewer store. Reset it to false for each new subject. Add an `onReady` handler to subject viewers, which fires on load for images, or after JSON data has loaded and parsed for data subjects.
- [x] Add a disabled prop to task nav buttons.
- [x] Add a disabled prop to tasks.
- [x] Disable tasks while subject data is loading.

Package:
lib-classifier

Closes #511 .

Describe your changes:

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Thanks. The problem I ran into with the approach here is that these changes break any project that uses images as subjects. The store never registers the subject files as having loaded.

**Comment by eatyourgreens** [comment]
@srallen I've re-written this so the store stays agnostic about the type of files that a subject might be loading. It should work now for TESS data subjects and for single image subjects. Each subject viewer is required to fire an `onReady` callback when all linked subject files are loaded and ready.

**Comment by eatyourgreens** [comment]
Tasks, and task nav buttons, don't support a `disabled` prop at the moment, so I've just hidden the task area while the subject is loading. I'm not sure if I like that, visually.

File: packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/MultipleChoiceTask/MultipleChoiceTask.js [hunk 1]
```diff
@@ -54,14 +54,18 @@ class MultipleChoiceTask extends React.Component {
...
       task
     } = this.props
     let annotation
     if (annotations && annotations.size > 0) {
       annotation = annotations.get(task.taskKey)
     }
     return (
-      <StyledFieldset autoFocus={(annotation && annotation.value && annotation.value.length === 0)}>
+      <StyledFieldset
+        autoFocus={(annotation && annotation.value && annotation.value.length === 0)}
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/MultipleChoiceTask/MultipleChoiceTask.js]: Fieldsets aren't focusable elements in HTML, so I suspect this a line that was copied over from PFE even though it does nothing here. It can probably be removed.

**Comment by eatyourgreens** [comment]
I've updated the task components so that task nav buttons and question answers can be disabled by passing a `disabled` prop. I think this is ready to go now.

File: packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/MultipleChoiceTask/MultipleChoiceTask.js (hunk 1 above)
Comment (srallen) [reply packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/MultipleChoiceTask/MultipleChoiceTask.js]: Yep, it wouldn't just been a straight lift from PFE. Let's open an issue to update the auto focus for the task area.

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js [hunk 2]
```diff
@@ -59,14 +48,22 @@ class SingleImageViewerContainer extends React.Component {
...
+
+  onError (error) {
+    console.error(error)
+    this.setState({ loading: asyncStates.error })
+  }
+
   render () {
     const { loadingState } = this.state
-    const { subject } = this.props
+    const { onReady, subject } = this.props
```
Comment (srallen) [inline packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js]: What's onReady doing here? I don't see it being used.

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js [hunk 3]
```diff
@@ -63,33 +63,43 @@ class LightCurveViewerContainer extends Component {
...
+  onLoad (rawData) {
+    this.setState({
+      dataExtent: {
+        x: d3.extent(rawData.x),
+        y: d3.extent(rawData.y)
+      },
+      dataPoints: zip(rawData.x, rawData.y),
+      loading: asyncStates.success
+    })
+    this.props.onReady()
```
Comment (srallen) [inline packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js]: Perhaps this should be a callback of `setState`?

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js [hunk 4]
```diff
@@ -59,14 +48,22 @@ class SingleImageViewerContainer extends React.Component {
...
       })
     } catch (error) {
-      console.error(error)
-      this.setState({ loading: asyncStates.error })
+      this.onError(error)
     }
   }
 
+  onLoad (event) {
+    this.props.onReady(event)
```
Comment (srallen) [inline packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js]: Does the event object need to be passed along here? The `onSubjectReady` store function is just setting a boolean and doesn't do anything with the event.

File: packages/lib-classifier/src/store/SubjectViewerStore.js [hunk 5]
```diff
@@ -27,55 +29,79 @@ const SubjectViewer = types
...
+
+      disableFullscreen () {
+        self.fullscreen = false
+      },
+
+      onSubjectReady () {
+        self.ready = true
+      },
+
+      resetSubject () {
```
Comment (srallen) [inline packages/lib-classifier/src/store/SubjectViewerStore.js]: I think this could be slightly more clearly named, perhaps `resetSubjectReady`?

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js (hunk 2 above)
Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js]: My bad. It's supposed to be passed down as the `onLoad` handler for the SVG image.

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js (hunk 3 above)
Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js]: Sure. I don't think it makes much difference here if `onReady` is called before, after, or at the same time as the state change.

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js (hunk 4 above)
Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js]: I originally thought `onReady` would be a proxy handler for the DOM's `load` event but that's only true if the store ever needs to reflect on the event eg. to get info about the downloaded image file. The image loading code is slightly complicated anyway, because of the preloader that I'm assuming is there to get the images original height and width?

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js (hunk 2 above)
Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js]: I've rewritten this, and added a test.

**Comment by eatyourgreens** [comment]
Looking back through my changes here, I'd also expect a test that the task area is disabled while the subject is loading, but I haven't added one. 😞

File: packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js [hunk 6]
```diff
@@ -26,21 +34,51 @@ describe('Tasks', function () {
...
+        <Tasks.wrappedComponent
+          loadingState={asyncStates.success}
+          ready={false}
+          tasks={tasks}
+        />
+      )
+      taskWrapper = wrapper.find('inject-SingleChoiceTask')
+    })
+
+    it('tasks should be disabled', function () {
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js]: Small thing but I'm not a big fan of wording like `it tasks should be disabled.` It tells me I haven't quite got my describe/it blocks set up correctly.

File: packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js [hunk 7]
```diff
@@ -26,21 +34,51 @@ describe('Tasks', function () {
...
-      type: 'single'
-    }]
-
-    const wrapper = shallow(<Tasks.wrappedComponent loadingState={asyncStates.success} tasks={tasks} />)
+    const wrapper = shallow(<Tasks.wrappedComponent loadingState={asyncStates.success} ready={true} tasks={tasks} />)
     // Is there a better way to do this?
     expect(wrapper.find('inject-SingleChoiceTask')).to.have.lengthOf(1)
   })
+
+  describe('when the subject is loading', function () {
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js]: Maybe this should be describing a thing, rather than a state. Then the `it` block can test an expected state for that thing.

**Comment by eatyourgreens** [comment]
@srallen this should be done now. I added some more tests, in addition to the PR comments.

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js (hunk 4 above)
Comment (srallen) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js]: Yes, the original PFE code gets the original height and width as well as the client height and width  at the onload event and stores them in the classification metadata. We still need to add that data to the classification metadata as noted in #304, but it's hasn't been done yet because we're now using an svg `image` instead of an html `img` and it doesn't have a client height and width. I'm not sure if we should go forward with the change to svg `image` or not.

File: packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js [hunk 8]
```diff
@@ -5,6 +5,14 @@ import { Tasks } from './Tasks'
 import asyncStates from '@zooniverse/async-states'
 
 describe('Tasks', function () {
+  const tasks = [{
```
Comment (srallen) [inline packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/Tasks.spec.js]: There's a factory for a test mock of single choice task types if you want to use it. I'd like us to move toward using those so our mocks are consistent across tests. This isn't really a blocker for me though.

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js (hunk 4 above)
Comment (srallen) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js]: I could see this being used to store the image's original height and width in the subject viewer store and the classification store could observe for that state and update the metadata.

Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js]: Yeah, if you inspect the `image` element in the DOM, client height and width are 0 in Chrome. Although we've recorded those numbers historically, I don't think they've ever been used in data analysis. Caesar doesn't need the client size, as far as I know, although it will need the natural size of an SVG image in order to analyse drawing annotations.

>I'm not sure if we should go forward with the change to svg image or not.

I don't think you can have drawing tasks or zoom and rotation transforms without using SVG.

Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js]: PFE renders an SVG rectangle just to get the client bounding box for drawing tasks:
https://github.com/zooniverse/Panoptes-Front-End/blob/fe0c87a8ef589ef6c662bbb350ed35f8b1b8e895/app/classifier/annotation-renderer/svg.jsx#L18-L31

Anti-Slavery Manuscripts is a drawing task on top of a jpeg image, so it might be worth looking at their code to see how they get the image dimensions in oder to map drawn points to positions on a page. They might have used a better approach than the one in PFE. AnnoTate might be worth looking at too.

Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js]: I've started work on this in #804.

Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewerContainer.js]: If we do need client height/width, they can be read from one of the containing DOM elements. Or we can get the client bounding box of the SVG element. #804 is pretty much done but I'm recording the client dimensions as 0 at the moment.
