### PR TITLE
fix(classifier): reset hidden marks when the subject changes

### LINKED ISSUE #6062: Hide previous marks persists to next subject, but will show 2nd mark
## Package
_Choose from the list:_
- [ ] app-content-pages
- [ X ] app-project
- [ ] lib-classifier
- [ ] lib-panoptes-js
- [ ] lib-react-components
- [ ] unknown

## Describe the bug
When you are classifying on a drawing task you can select "Hide previous marks." After submitting a classification, the marks do not show on the next subject. However, you can still draw new marks. The 1st mark will be hidden, and subsequent marks will show. If you then press "show previous marks" you will see the 1st hidden mark has actually been recorded. See this video for more details.

https://github.com/zooniverse/front-end-monorepo/assets/89043489/d06d8818-2556-4c47-b852-14b91d9e991a

### Desktop (please complete the following information):
 - OS: [e.g. Windows 10]

### Smartphone (please complete the following information):
 - Device: [e.g. iPhone]
 - OS:
 - Browser:
 - Versio:

### PR DESCRIPTION
**Pull request by eatyourgreens**
Reset the Hide Previous Marks toggle when a drawing task is reset. This should fix a bug where `task.hidingIndex` is remembered across subjects, which means that a volunteer won't see the first few marks that they draw on a new subject.

That affects both drawing and transcription tasks, as both use the same code to store `task.hidingIndex` across subjects. 

https://github.com/zooniverse/front-end-monorepo/assets/59547/76e24ab1-8842-4da8-8fda-5fe04b6d4137

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
- lib-classifier/plugins/tasks/drawing
- lib-classifier/plugins/tasks/experimental/transcription

## Linked Issue and/or Talk Post
- should fix #6062.

## How to Review
You can test this on WildWatch Burrowing Owl. See the video above.
https://localhost:8080/?project=sandiegozooglobal/wildwatch-burrowing-owls&env=production&demo=true

Checking a transcription workflow would also be a good idea, as the same code is used by both transcription and drawing tasks. I’ve included tests for both tasks in this PR. 

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

File: packages/lib-classifier/src/plugins/tasks/drawing/models/DrawingTask.js [hunk 1]
```diff
@@ -98,6 +98,8 @@ export const Drawing = types.model('Drawing', {
         self.tools.forEach(tool => tool.reset())
         self.activeToolIndex = 0
         self.subTaskVisibility = false
+        self.hidingIndex = null
+        self.shownMarks = SHOWN_MARKS.ALL
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/plugins/tasks/drawing/models/DrawingTask.js:102]: This line will need to be modified slightly for transcription tasks, where `shownMarks` has three possible states, not two.

**Review by goplayoutside3 — APPROVED** [review]
Looks good thank you!
