### PR TITLE
fix(classifier): Polygon tool drag handles

### LINKED ISSUE #6549: Drag handles are broken for polygon drawing tool
## Package
- lib-classifier

## Describe the bug
The polygon drawing tool has drag handles, but dragging them doesn't do anything.

## To Reproduce
1. Go to https://frontend.preview.zooniverse.org/projects/eatyourgreens/-project-testing-ground/classify/workflow/3370?env=staging
2. Draw a polygon with 3 or more corners.
3. Drag one of the corners.

You can also reproduce the bug in the storybook: https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/story/drawing-tools-polygon--active

## Screenshots

https://github.com/user-attachments/assets/b43fea26-b63a-4f6b-8ad6-3b5dfa42bed1

## Expected behavior
Dragging the drag handles should pull the polygon into a new shape.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Refactor the polygon tool drag handles so that `pointerdown` does not close and finish the shape, overriding the pointer dragging behaviour. Instead, the shape is closed and finished on `pointerup`.

Refactor the `draggable` decorator so that it decorates any existing `onPointerDown`, `onPointerMove`, and `onPointerUp` handlers with draggable behaviour. The draggable behaviour is run before the existing handler, for each event.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
- lib-classifier

## Linked Issue and/or Talk Post
- closes #6549.
- original bug introduced by #3389, I think.

## How to Review

https://github.com/user-attachments/assets/5b9e791a-1971-43b2-a8c6-e68f7fd77ca3

Clicking a drag handle should still close and finish a polygon, but `pointerdown` should now start dragging where previously it was cancelled.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

File: packages/lib-classifier/src/plugins/drawingTools/components/Polygon/Polygon.js [hunk 1]
```diff
@@ -72,7 +72,6 @@ function Polygon({ active, mark, scale, onFinish }) {
           strokeWidth={strokeWidth}
           strokeDasharray={strokeDasharray}
         />
-      )}
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/plugins/drawingTools/components/Polygon/Polygon.js:75]: The polygon tool code is actually broken here, and has been for a while. 😳

**Review by goplayoutside3 — COMMENTED** [review]
While I can move the drag point by running this PR with https://localhost.zooniverse.org:3000/projects/eatyourgreens/-project-testing-ground/classify/workflow/3370?env=staging, when I release the drag point then move my mouse around the subject viewer, hovering sometimes picks up the drag point again. Do you see that behavior too? I'm using Brave Browser on MacOS.

**Comment by eatyourgreens** [comment]
I haven’t seen that, but it sounds like a bug where pointer capture isn’t automatically released on pointer up.

File: packages/lib-classifier/src/plugins/drawingTools/components/Polygon/Polygon.js [hunk 2]
```diff
@@ -84,7 +83,7 @@ function Polygon({ active, mark, scale, onFinish }) {
               y={point.y}
               fill='currentColor'
               dragMove={point.moveTo}
-              onPointerDown={handleClosePolygon}
+              onPointerUp={handleClosePolygon}
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/plugins/drawingTools/components/Polygon/Polygon.js:86]: Previously this overrode `onPointerDown` for draggable elements, which stopped dragging from happening at all. Now it overrides `onPointerUp` which means dragging is never canceled once it has started. 😳

Comment (eatyourgreens) [reply packages/lib-classifier/src/plugins/drawingTools/components/Polygon/Polygon.js:86]: Fixed in 4059705.

Comment (eatyourgreens) [reply packages/lib-classifier/src/plugins/drawingTools/components/Polygon/Polygon.js:86]: Tested in Chrome and Firefox with a few different drawing tools. Seems to work OK, and dragging is cancelled on pointer up.
https://localhost:8080/?project=eatyourgreens%2F-project-testing-ground&workflow=3370

Comment (eatyourgreens) [reply packages/lib-classifier/src/plugins/drawingTools/components/Polygon/Polygon.js:86]: The ellipse tool still seems to work as expected in I Fancy Cats.

**Review by goplayoutside3 — APPROVED** [review]
Looks good!
