### PR TITLE
Announce current project nav in screen readers

### LINKED ISSUE #3982: Going directly to a project's about page (owner/project/about/research) removes sidebar nav highlight
## Package
app-project

## Describe the bug
The sidebar for navigating a project's about pages should display a teal highlight to indicate the current page. Navigating from a project's home page correctly shows the highlight, but going directly to a project's about page (owner/project/about/research) removes the sidebar nav highlight.

## To Reproduce
Point a browser directly to a project's about page such as TESS [Research](https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/about/research), TESS [Results](https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/about/results), etc, and the highlight is missing.

Refreshing the browser while viewing an about page also removes the sidebar highlight.

## Screenshots
highlight
no highlight

## Additional context
Likely has to do with latest Next.js updates to its Router.

### PR DESCRIPTION
**Pull request by eatyourgreens**
- Add [`aria-current=page`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current) to the project navigation and the project About section navigation menus.
- Use the `[aria-current=page]` attribute selector to style the current page link.
- Compare the current project section, not the whole URL path, to find the current page in the project navigation menu.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
- app-project

## Linked Issue and/or Talk Post
- Closes #3982.

## How to Review
- screen readers will now announce the current page in both project navigation menus.
- the current section will be correctly underlined, for sighted volunteers, in the project navigation menu.

https://local.zooniverse.org:3000/projects/zooniverse/gravity-spy/about/team
The Gravity Spy Team page, showing that 'About' is correctly underlined in the project navigation menu.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [x] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [x] Can submit a classification
- [x] Can sign-in and sign-out
- [x] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [x] The PR creator has listed user actions to use when testing if bug is fixed
- [x] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

File: packages/app-project/src/components/ProjectHeader/components/Nav/Nav.js [hunk 1]
```diff
@@ -28,13 +29,39 @@ const StyledAnchor = styled(Anchor)`
     &[href]:hover {
       border-bottom-color: ${props.color};
     }
-    &:not([href]) {
+    &[aria-current=page] {
```
Comment (goplayoutside3) [inline packages/app-project/src/components/ProjectHeader/components/Nav/Nav.js:32]: This is a helpful selector! As a follow-up, I'll refactor the styling of active links in app-content-pages to use this rather than an `active` prop. There's always warnings about `active` being an unexpected boolean passed to elements, so good to know that `aria-current` is available instead.

**Review by goplayoutside3 — COMMENTED** [review]
While this is a helpful understanding of `aria-current`, the solution here does not close #3982. I put these code changes on the FEM PR branch, and when I navigate directly to https://fe-project-branch.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/about/research, neither the ProjectHeader link or AboutSidebar link are correctly highlighted.

**Comment by eatyourgreens** [comment]
That’s odd, because they’re correctly highlighted in my screenshot. I wonder what we’re doing differently.

**Comment by eatyourgreens** [comment]
Oh wait, going directly to a page will be broken with the Next 12 router but fixed in Next 13. This branch is still on 12.

**Comment by eatyourgreens** [comment]
So #5521 will fix #3982. This PR fixes the problem where the top-level project navigation is not correctly underlined to show the section that you are in.

**Comment by eatyourgreens** [comment]
I don't have permission to update this branch, but hopefully that will fix Next 12 bugs by updating to 13.5.

**Comment by goplayoutside3** [comment]
Navigating directly to https://fe-project-branch.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/about/research on this branch (updated with Next.js 13) or navigating directly to https://frontend.preview.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/about/research still does not solve #3982. I think there might be something going on with the components being built on the server, and the check for `asPath` versus `href` being unexpectedly false.

I'm happy to merge this PR as an accessibility improvement without solving the link highlight though. If needed in PRs, you could still update a branch by pulling master to it locally and then pushing - is that correct?

**Comment by eatyourgreens** [comment]
I can't push to this repo any more. I only have read access.

**Comment by goplayoutside3** [comment]
I figured out why the link `isCurrentPage` isn't worked as expected. At least in dev mode, the `routerPath` is `['', '[env]', owner, project, section, ...rest]` while the `hrefPath` is `['', owner, project, section, ...rest]`. The section is at different indices in the arrays, so the check has to be `routerPath[4] === hrefPath[3]`. I'll push that change and see if it works on the deployed branch today, too.

**Comment by eatyourgreens** [comment]
Thanks for debugging that. I wonder if `asPath` can be different between dev mode and a production build? I never thought to check that.

**Comment by goplayoutside3** [comment]
After more investigation, I'm pretty sure what's happening is that `router.asPath` is `/staging/brooke/i-fancy-cats/about/research` when run on the server, but is `/brooke/i-fancy-cats/about/research` in the browser. The code to check for active links when navigating directly to a url like https://fe-project-branch.preview.zooniverse.org/projects/brooke/i-fancy-cats/about/research is SSR, but `isCurrentPage = routerPath[3] === hrefPath[3]` returns false because there's an extra `env` subpath. The check is not run again once loaded in a browser 😞 

I'm not sure how to solve this issue yet, but pushed edits to the dropdown navs in ProjectHeader and AboutPage so we can work toward correctly highlighting those, too. There's a hook [usePathname()](https://nextjs.org/docs/app/api-reference/functions/use-pathname) available, but using it breaks component tests even if they're wrapped in a `<RouterContext>`. I'll have to come back to this PR later.

**Comment by eatyourgreens** [comment]
That's annoying. I don't have a good solution either. Maybe use `href` rather than `asPath`? That might also be prepended with `production/staging` on the server.

If the current page in each navigation list can't be determined programmatically, that could be a failure of [WCAG SC 1.3.1 Info and Relationships](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships), which is a level A requirement.

**Comment by eatyourgreens** [comment]
>There's a hook [usePathname()](https://nextjs.org/docs/app/api-reference/functions/use-pathname) available, but using it breaks component tests even if they're wrapped in a <RouterContext>.

After looking very quickly at the linked docs, that hook is only available with the app router.

**Comment by eatyourgreens** [comment]
This might work around server-side routing and client-side routing but I've written this very quickly, without checking it. It probably needs checking that `href` isn't being prepended with the API environment either, in Node.
```js
const routerPath = router?.asPath.split('/')
const isSSR = ['production', 'staging'].includes(routerPath[1])
const section = isSSR ? routerPath[4] : routerPath[3]
const isCurrentPage = section === hrefPath[3]
```

**Comment by eatyourgreens** [comment]
I've updated my local copy of this branch, but I'm now seeing all the links in the About sidebar are highlighted as the current page, when I go straight to the Research page in dev mode.

image

**Comment by eatyourgreens** [comment]
I've opened #5755 to fix those problems on this branch. I tested it locally in Chrome and Firefox, with dev mode and with a production build of the project app. I couldn't find any problems, and the navigation should now be properly highlighted during SSR.

**Comment by goplayoutside3** [comment]
When going directly to https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats/about/research, the AboutSidebar is still not correctly highlighted. Will have to keep investigating 🤔

**Comment by goplayoutside3** [comment]
I ended up trying the same strategy as the Project Title in the project header component:
https://github.com/zooniverse/front-end-monorepo/blob/995a00edd870ed8bb68c295f9b264a93ca134033/packages/app-project/src/components/ProjectHeader/components/ProjectTitle/ProjectTitle.js#L35

Rather than mess with `/staging` or `/production` during SSR, I think it works well to instead check for `isCurrentPage` only when `router.isReady === true` (Next.js [docs](https://nextjs.org/docs/pages/api-reference/functions/use-router#router-object)).

**Review by goplayoutside3 — APPROVED** [review]

**Comment by eatyourgreens** [comment]
I considered using `isReady` but decided against it as the docs don’t recommend using it for conditional rendering. 

> Should only be used inside of useEffect methods and not for conditionally rendering on the server.
