### PR TITLE
App-project: refactor when notifications requests called

### LINKED ISSUE #3672: Notifications and Messages links vanish on iOS
## Package
app-content-pages
app-project

## Describe the bug
When you use the Back button to return to a page in mobile Safari, or follow a link to another page, the Notifications and Messages links vanish from the top of the page.

Screenshot of Maria Edgeworth Letters, showing that the links for Notifcations and Messages are missing.

## To Reproduce
1. Go to [Maria Edgeworth Letters](https://www.zooniverse.org/projects/mariaedgeworthletters/maria-edgeworth-letters)
2. Navigate to Talk.
3. Use the Back button to return to the home page.

Alternatively, go to one of the About pages and navigate from Research to The Team.

## Expected behavior
Notifications and Messages should always be available (while logged in.)

### Smartphone (please complete the following information):
 - Device: iPhone Xs
 - OS: iOS 15.6.1
 - Browser Safari
 - Version 15.6.1

## Additional context
~~This bug doesn't exist in the page header for the Publications or Team pages, only in the page header for project pages.~~ Since #3671, where I connected the content-pages site header to the store, this bug also affects the Team and Publications pages.

### LINKED ISSUE #3941: Console errors for notifications and messages on page load
## Package
app-project

## Describe the bug
Console errors appear on page load regarding notifications and messages:
- First: `Failed to load resource: net::ERR_HTTP2_PROTOCOL_ERROR`
- After reload: 401 errors with message `instrument.js:108 Error: {"error":"not allowed to index this Notification"}`.

While the notification and message counts are displayed correctly, @mcbouslog noted that this is likely due to an ordering issue where Talk is being queried before user credentials are loaded (or similar).

## To Reproduce
1. Visit https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess
2. Open console to see errors
3. Reload page to see 401 errors

## Expected behavior
No errors.

### Desktop (please complete the following information):
 - OS: MacOS 12.6.1
 - Browser: Chrome 107

### PR DESCRIPTION
**Pull request by mcbouslog**
## Package
- app-project

## Linked Issue and/or Talk Post
- closes #3941 
- closes #3672

## Describe your changes
- add test for anonymous user to not request notifications
- refactor notifications request to `UserPersonalization` load action
- refactor tests per changes

## How to Review
_Helpful explanations that will make your reviewer happy:_
- What Zooniverse project should my reviewer use to review UX?
  - any project, here's production TESS - https://local.zooniverse.org:3000/projects/nora-dot-eisner/planet-hunters-tess?env=production&demo=true
- What user actions should my reviewer step through to review this PR?
  - with notifications (Messages or Notifications in header, let me know if you'd like me to send you a message to create some), start on https://local.zooniverse.org:3000/projects/nora-dot-eisner/planet-hunters-tess?env=production&demo=true
  - go to Talk, will 404, but then click back
  - confirm notification counts still show
- Which storybook stories should be reviewed? N/A
- Are there plans for follow up PR’s to further fix this bug or develop this feature? no, though other notifications related work is ongoing

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

File: packages/app-project/stores/User/UserPersonalization/UserPersonalization.js [hunk 1]
```diff
@@ -46,10 +46,8 @@ const UserPersonalization = types
   }))
   .actions(self => {
     function _onUserChange() {
-      const { project, user } = getRoot(self)
-      if (user.id) {
-        self.notifications.fetchAndSubscribe()
-      } else if (user.loadingState === asyncStates.success) {
+      const { user } = getRoot(self)
+      if (user.loadingState === asyncStates.success) {
         self.projectPreferences.setLoadingState(asyncStates.success)
```
Comment (eatyourgreens) [inline packages/app-project/stores/User/UserPersonalization/UserPersonalization.js:51]: This will mark project prefs as loaded while we’re still waiting for them to load, for a logged-in user. 

Personally I find the logic here confusing, but this is a workaround to set prefs as loaded for anonymous users.

Comment (eatyourgreens) [reply packages/app-project/stores/User/UserPersonalization/UserPersonalization.js:51]: Also, this change should have caused tests to fail. 🤔

Comment (mcbouslog) [reply packages/app-project/stores/User/UserPersonalization/UserPersonalization.js:51]: My understanding on why we want user project preferences set to success for an anonymous user - I think it's because we use `appLoadingState` in components including [the ClassifierWrapper](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/app-project/src/screens/ClassifyPage/components/ClassifierWrapper/ClassifierWrapper.js#L93) and [the ClassifyPage](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/app-project/src/screens/ClassifyPage/ClassifyPage.js#L25), which needs the user project preferences loading state to `= 'success'` [per this code in the Store](https://github.com/zooniverse/front-end-monorepo/blob/master/packages/app-project/stores/Store.js#L23), and for a user we want the classifier to wait for user project preferences (UPPs) and for an anonymous user we want to load the classifier but there aren't UPPs so in the UserPersonalization store here we're forcing the UPPs loadingState to success so the classifier can load for an anonymous user. Not ideal, but I think makes sense.

No point/question to the above, just documenting my understanding.

Comment (eatyourgreens) [reply packages/app-project/stores/User/UserPersonalization/UserPersonalization.js:51]: That’s my understanding too. There are some mocks in the tests that don’t work unless you explicitly set the loading state. I’ll see if I can find an example.

File: packages/app-project/stores/User/UserPersonalization/UserPersonalization.js [hunk 2]
```diff
@@ -46,10 +46,8 @@ const UserPersonalization = types
   }))
   .actions(self => {
     function _onUserChange() {
-      const { project, user } = getRoot(self)
-      if (user.id) {
-        self.notifications.fetchAndSubscribe()
-      } else if (user.loadingState === asyncStates.success) {
+      const { user } = getRoot(self)
+      if (user.loadingState === asyncStates.success) {
```
Comment (eatyourgreens) [inline packages/app-project/stores/User/UserPersonalization/UserPersonalization.js]:
```suggestion
      if (!user.isLoggedIn && user.loadingState === asyncStates.success) {
```

It’s been a while since I looked at the User code but I think this will fix it, and is easier to read.

File: packages/app-project/stores/User/UserPersonalization/UserPersonalization.js [hunk 3]
```diff
@@ -69,6 +67,7 @@ const UserPersonalization = types
       },
 
       load() {
+        self.notifications.fetchAndSubscribe()
```
Comment (eatyourgreens) [inline packages/app-project/stores/User/UserPersonalization/UserPersonalization.js:70]: This might fix a load of project tests that fire off a request to the Talk API as soon as you create a mock store.

File: packages/app-project/stores/User/UserPersonalization/UserPersonalization.js (hunk 2 above)
Comment (mcbouslog) [reply packages/app-project/stores/User/UserPersonalization/UserPersonalization.js]: I like this more than my commit a minute ago, checking out more 👍

File: packages/app-project/stores/User/UserPersonalization/UserPersonalization.spec.js [hunk 4]
```diff
@@ -213,6 +214,10 @@ describe('Stores > UserPersonalization', function () {
       expect(rootStore.user.personalization.totalClassificationCount).to.equal(0)
     })
 
+    it('should not trigger the child Notifications store to request unread notifications or conversations', function () {
+      expect(talkAPI.get).to.have.not.been.called()
```
Comment (eatyourgreens) [inline packages/app-project/stores/User/UserPersonalization/UserPersonalization.spec.js:218]: Not a requirement for this PR, but it might be better to mock the Talk API with `nock`, rather than stub the get request.

**Review by eatyourgreens — APPROVED** [review]
Changes look good to me. I think this can merge once the check for an anonymous user is fixed.

File: packages/app-project/stores/User/UserPersonalization/UserPersonalization.js (hunk 2 above)
Comment (mcbouslog) [reply packages/app-project/stores/User/UserPersonalization/UserPersonalization.js]: Yep, `isLoggedIn` is a view from the User store returning `return !!self.id`, but I think makes more sense from a code read, so I'm going to update to use that (`isLoggedIn`) ✅ , just a sec...

**Comment by mcbouslog** [comment]
Related to the user project preference loading state - one user project preference property is if a user has completed a tutorial for a project, so I confirmed on https://local.zooniverse.org:3000/projects/nora-dot-test/planet-finders-beta/classify/workflow/3317?demo=true:
- signed-out: tutorial is displayed, can still classify
- signed-in (having previously completed the tutorial): tutorial is not displayed, can still classify

Which is what would expect ☑️
