### PR TITLE
fix(classifier): ctrl to zoom images and wheel zoom for drawn marks

### LINKED ISSUE #6746: Drawing: drawn marks silently ignore trackpad wheel zoom gestures
There's a small bug in the new wheel zoom, at least when using a MacBook trackpad. Found while writing up https://github.com/zooniverse/front-end-monorepo/issues/6745:

- This affects all drawn marks but is easiest to reproduce by drawing an extended shape like a rectangle or circle.
- Try to use wheel zoom to zoom in to the centre of the extended shape.
- The drawing mark silently ignores wheel events from the trackpad, so the scrolling gesture scrolls the page instead.

Screen recording from the latest Chrome:

https://github.com/user-attachments/assets/4a3abc2e-768e-4ddc-a8fc-dc46cb66c5fe

### LINKED ISSUE #6758: Scroll behavior unexpected for workflows initially in pan-zoom mode
Per recent mouse-wheel zoom changes in #6390 the scroll behavior is unexpected when the classifier is in pan-zoom mode by default. The classifier is in pan-zoom mode by default for workflows that don't have a drawing task, which then don't include an Annotate button in the image toolbar, and default to pan-zoom mode.

With workflows with tall portrait images and no drawing task, after the classifier loads, especially if a user has just dismissed the tutorial for the first time, the user could likely begin to scroll down with the mouse over the subject image, and the image will zoom (per recent mouse wheel zoom implementation) when I think user would expect the page to scroll down.

This can be observed in a workflow like:
- ⚠ production project/workflow ⚠ : https://frontend.preview.zooniverse.org/projects/cmnbotany/notes-from-nature-capture-the-collections/classify/workflow/27243
- staging/dev workflow https://frontend.preview.zooniverse.org/projects/markb-panoptes/test-project-1-mb-fem-lab/classify/workflow/3849?env=staging&demo=true

This is not an issue with PFE because in PFE the annotate button persists and annotate mode is the default initial state regardless of drawing task existence in the workflow.

### PR DESCRIPTION
**Pull request by eatyourgreens**
- In `VisXZoom`, listen for wheel events from the subject components (including the drawing canvas.)
- Explicitly set `passive: false` to allow `event.preventDefault()` in the wheel event listener (to turn off window scrolling.)
- Add the `move` prop so that we can enable/disable wheel zoom according to whether 'pan' is selected in the subject toolbar.
- Tune the wheel zoom parameters for a smoother zooming UX.
- Require the ~~Shift~~ Ctrl key for wheel zoom.
- Add an `allowsScrolling` prop. Disabling window scroll is the default behaviour for JSON data viewers with `VisXZoom`. When `allowsScrolling` is enabled, the mouse wheel scrolls the window by default, and zooms with the ~~Shift~~ Ctrl modifier key.
- a maintenance refactor: upgrade `VisXZoom` to use the [render props pattern](https://react.dev/reference/react/cloneElement#passing-data-with-a-render-prop). This change is more about future code maintainability and modernising the Zooniverse codebase than adding the new functionality here. With the render props pattern, you don't have to add the zooming component's props as extra props to `VisXZoom`, so there's a clear separation between eg. `VisXZoom` props and `SingleImageCanvas` props.

With these changes, you should be able to zoom in and out with the mouse wheel, even if there are marks drawn on top of the subject, and you'll need to use a modifier key to use scrolling zoom with images.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
- lib-classifier

## Linked Issue and/or Talk Post
- closes #6746 (but still allows you to drag drawn marks.)
- fixes #6758.

https://localhost:8080/?env=staging&project=markb-panoptes/test-project-1-mb-fem-lab&workflow=3847

In pan mode, you should be able to use wheel zoom (with the ~~Shift~~ Ctrl key) anywhere on the subject, even on top of drawn marks.

https://github.com/user-attachments/assets/b24dd8a8-69ff-41d0-817c-af8a1ad5c2ff

You can use the Scatter Plot Viewer > X Range Selection story, in the classifier storybook, to check that wheel zoom hasn't changed for Black Hole Hunters.

Try out a portrait subject, from NfN, here:
https://localhost:8080/?env=production&project=cmnbotany%2Fnotes-from-nature-capture-the-collections&workflow=27243

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [x] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [x] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [x] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [x] Can submit a classification
- [x] Can sign-in and sign-out
- [x] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [x] The PR creator has listed user actions to use when testing if bug is fixed
- [x] The bug is fixed
- [x] Unit tests are added or updated

### CODE REVIEW

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js [hunk 1]
```diff
@@ -149,28 +162,31 @@ function VisXZoom({
...
+                focusable
+                height={height}
+                onDoubleClick={onDoubleClick}
+                onKeyDown={onKeyZoom}
+                onPointerEnter={onPointerEnter}
+                onPointerDown={panning ? _zoom.dragStart : DEFAULT_HANDLER}
+                onPointerMove={panning ? _zoom.dragMove : DEFAULT_HANDLER}
+                onPointerUp={panning ? _zoom.dragEnd : DEFAULT_HANDLER}
+                onPointerLeave={onPointerLeave}
+                onWheel={throttledOnWheel}
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js:183]: The zooming UX is much smoother if you remove `onWheel` here. However, 13 tests rely on it being present, so removing it fails CI.

Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js:188]: Tunning the zoom parameters in `wheelDelta` also produces a much smoother UX, so I've done that.

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js [hunk 2]
```diff
@@ -75,7 +75,7 @@ function SingleImageViewer({
           <title id={title.id}>{title.text}</title>
         )}
         <svg
-          style={{ touchAction: 'none' }}
+          style={{ touchAction: 'pinch-zoom' }}
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js:78]: I think this is needed to allow for zoom on tablets and phones, but I'm not 100% sure. PFE varies the style according to whether you are drawing or not:
https://github.com/zooniverse/Panoptes-Front-End/blob/85b7a04618b8d0c8621e83366728efde20fc243d/app/classifier/annotation-renderer/svg.jsx#L136-L141

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.spec.js [hunk 3]
```diff
@@ -37,14 +37,16 @@ describe('Component > ZoomingScatterPlot', function() {
     clientX: 50,
     clientY: 50,
     deltaY: -1,
-    preventDefault: sinon.spy()
+    preventDefault: sinon.spy(),
+    shiftKey: true
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.spec.js:41]: Using Shift + Wheel to zoom JSON data plots is a potentially breaking change for Black Hole Hunters here.

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js [hunk 4]
```diff
@@ -75,10 +75,11 @@ function SingleImageViewer({
...
           viewBox={`0 0 ${naturalWidth} ${naturalHeight}`}
         >
           <VisXZoom
+            disablesScrolling={false}
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js:82]: I made this true by default because the JSON data viewers disable window scrolling.

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js (hunk 2 above)
Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js:78]: `@visx/zoom` also supports pinch gestures, via `zoom.containerRef` passed into the zoom render function.

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.spec.js (hunk 3 above)
Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.spec.js]: I've taken this out, in favour of leaving the existing mouse wheel behaviour in place for Black Hole Hunters, where the subject never needs to scroll vertically.

**Comment by mcbouslog** [comment]
This is looking good, I'm still testing various actions and will post more shortly, but noting the following local projects have been helpful for testing:
- many image workflows: https://local.zooniverse.org:3000/projects/markb-panoptes/test-project-1-mb-fem-lab?env=staging&demo=true
- data and image viewer: https://local.zooniverse.org:3000/projects/mrniaboc/superluminous-supernovae/classify/workflow/16264?env=production&demo=true
- data viewer: https://local.zooniverse.org:3000/projects/cobalt-lensing/black-hole-hunters/classify/workflow/25860?env=production&demo=true

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js [hunk 5]
```diff
@@ -35,12 +37,28 @@ function VisXZoom({
...
   const zoomRef = useRef(null)
+  const wheelEventLayer = useRef(null)
 
   useEffect(function setCallbacks() {
     setOnPan(handleToolbarPan)
     setOnZoom(handleToolbarZoom)
   }, [setOnPan, setOnZoom])
 
+  function wheelDelta(event) {
+    const zoomValue = (-event.deltaY > 0) ? 1.1 : 0.9
```
[the remark this answers is not in the document]
Comment (mcbouslog) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js:51]: Could/should these be per the `zoomConfiguration`? I think they can be, but might be missing a reason they shouldn't be.

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js [hunk 6]
```diff
@@ -1,13 +1,16 @@
...
-import { throttle } from 'lodash'
+import throttle from 'lodash/throttle'
 import { observer } from 'mobx-react'
 import PropTypes from 'prop-types'
 import { useEffect, useRef } from 'react'
 
 import { useKeyZoom } from '@hooks'
 import ZoomEventLayer from '../ZoomEventLayer'
 
+export const ZOOM_HOT_KEY = 'ctrlKey'
```
Comment (mcbouslog) [inline packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js:12]: This change is so it's easier to tinker with which key to use as we discuss the various key options (shiftKey, ctrlKey, metaKey, altKey, other?).

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js:51]: They could be. Default scale step in the zoom config is 1.2 for zoom in, 0.8 for zoom out, which works well for the toolbar buttons and keyboard, but is kind of hard to control with the wheel.

[the remark this answers is not in the document]
Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js:51]: Oh and zoom config might be per subject, rather than set for the workflow, which gives fine-grained control but alos potentially a UX that varies from subject to subject. Eg. imagine I upload a subject set with one zoom config, decide I don't like it, upload a new subject set with a new zoom config, and then mix both subject sets in the same workflow.

I think the zoom config be documented in a Readme somewhere in the repo. It was all set up before I worked on the zooming data subjects for LSST, so I just worked with whatever was already there.

If LSST subjects are going to include zoom config for light curves, then this might be an opportunity to revisit how that works.

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.spec.js [hunk 7]
```diff
@@ -465,7 +467,8 @@ describe('Component > VisXZoom', function () {
           clientX: 50,
           clientY: 50,
           deltaY: -1,
-          preventDefault: sinon.spy()
+          preventDefault: sinon.spy(),
+          [ZOOM_HOT_KEY]: true
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.spec.js:471]: I forgot that the tests don't need the modifier key unless you also pass `disablesScrolling={false}` into the `VisXZoom` component. Default behaviour is to continue as before, to avoid breaking the JSON data viewers.

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js:51]: >Could/should these be per the zoomConfiguration? I think they can be, but might be missing a reason they shouldn't be.

If you do modify these values, they're also baked into the tests for `ZoomingScatterPlot` and `VisXZoom`, so you might need to edit some tests too. That's why I had to update the tests in this PR. They rely on very specific values for the zoom scale steps.

[the remark this answers is not in the document]
Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js:51]: Re. where zoom config is set, it can be stored on a data subject in `chartOptions.zoomconfiguration` here:
https://github.com/zooniverse/front-end-monorepo/blob/aed398d41e9aa30d9690e726e47ecde13f99c30f/packages/lib-classifier/src/store/JSONData/DataSeriesPlot.js#L25-L35

I don't know if there's an equivalent for image subjects.

I think zoom configuration can also be read from `workflow.configuration.zoomConfiguration`, where it has the same shape as the subject config, which is set here:
https://github.com/zooniverse/front-end-monorepo/blob/aed398d41e9aa30d9690e726e47ecde13f99c30f/packages/lib-classifier/src/store/JSONData/DataSeriesPlot.js#L17-L23

Side note: I guess `zoomConfiguration.direction` is meaningless for image subjects. It allows you to zoom data in only one axis eg. zoom only the x-axis with the wheel or toolbar buttons here: https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/story/subject-viewers-scatterplotviewer--x-range-selection

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js (hunk 6 above)
Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js:12]: If you choose `metaKey`, be aware that it doesn't work in Firefox < 188, and one of the NfN moderators is stuck on FF 115 (also, don't make decisions like this without including user research!)

https://github.com/zooniverse/front-end-monorepo/issues/6592

**Comment by eatyourgreens** [comment]
I've added explanatory comments to the `onWheel` handler, which was getting a bit complex. Also docgen descriptions for `VisXZoom` and its props, as it is completely undocumented at present.

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js (hunk 6 above)
Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js:12]: Ctrl + tap brings up the context menu with a trackpad, so Ctrl might not have been a great choice on my part. That said, there is a clear difference between single finger tap to click and two finger drag to scroll, and the latter won't be expected to open a context menu.

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js [hunk 8]
```diff
@@ -142,58 +219,83 @@ function VisXZoom({
       scaleXMax={zoomConfiguration.maxZoom}
       scaleYMin={zoomConfiguration.minZoom}
       scaleYMax={zoomConfiguration.maxZoom}
-      passive
       top={top}
       width={width}
+      wheelDelta={wheelDelta}
     >
       {_zoom => {
         zoomRef.current = _zoom
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js:227]: For future reference, the VisX zoom object is documented as `ProvidedZoom` in the zoom type definitions here:
https://github.com/airbnb/visx/blob/86738178e86fdc0feacf83ac96e68724da0627c2/packages/visx-zoom/src/types.ts#L49-L100

VS Code should read those type annotations automatically.

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js [hunk 9]
```diff
@@ -96,38 +98,18 @@ function SingleImageViewer({
...
-    }))
-  }),
   title: shape({
     id: string,
     text: string
   }),
   zoomControlFn: func,
-  zooming: bool
+  zooming: bool,
+  ...SingleImageCanvas.propTypes
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageViewer.js:112]: > [!TIP]
> When you use composition to combine components, use the spread operator to avoid managing the same type definitions in two places.

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js [hunk 10]
```diff
@@ -142,58 +219,87 @@ function VisXZoom({
       scaleXMax={zoomConfiguration.maxZoom}
       scaleYMin={zoomConfiguration.minZoom}
       scaleYMax={zoomConfiguration.maxZoom}
-      passive
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js:145]: `passive` was removed from `@visx/zoom` in 2021.

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js [hunk 11]
```diff
@@ -142,58 +219,96 @@ function VisXZoom({
...
+   * `VisXZoom` will inject the following props into this component:
+   * - `initialTransformMatrix`: the initial transformation matrix.
+   * - `transformMatrix`: the current transformation matrix.
+   * - `transform`: a string representation of the matrix transform.
+   * - `children`: `ZoomEventLayer`, an SVG `<rect>` which handles zoom pointer and wheel events.
+   * ```jsx
+   * ({ children, ...zoomProps }) => (
+   *   <SVGComponent {...zoomProps} {...SVGComponentProps} >
+   *     {children}
+   *   </SVGComponent>
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js:308]: The design of `VisXZoom` means you can't use it to zoom an SVG element that doesn't accept children.

For example, you can't directly zoom an SVG image. The following code will render an image but no event layer to pand and zoom: 
```jsx
<VisXZoom
  zoomingComponent={(props) => <image {...props} height={500} width={1000} src={someURL} />}
/>
```

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js [hunk 12]
```diff
@@ -31,16 +64,69 @@ function VisXZoom({
...
+    won't prevent the default wheel scroll, so style the document body to stop
+    scrolling and remove scrollbars.
+    */
+    if (event[ZOOM_HOT_KEY]) {
+      /* Disable scroll in Safari (or for passive wheel events.) */
+      document.body.style.overflow = 'hidden'
+      const scrollbarWidth = window.innerWidth - document.documentElement.clientWidth
+      if (scrollbarWidth) {
+        document.body.style.paddingRight = `${scrollbarWidth}px`
+      }
```
Comment (mcbouslog) [inline packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js:110]: If the scrollbar is hidden before the scrollbar width is calculated, then the calculated `scrollbarWidth` will always be zero, and there's a horizontal layout shift when a user begins scrolling with the hot key.

Can the scrollbar width be calculated first, then `overflow: hidden` ? Doesn't have to be exactly like the following, but something like:

```suggestion
      /* Calculate width of scrollbar */
      const scrollbarWidth = window.innerWidth - document.documentElement.clientWidth
      
      /* Disable scroll in Safari (or for passive wheel events), hide scrollbar */
      document.body.style.overflow = 'hidden'
      
      /* Add right padding for the width of the scrollbar to prevent horizontal layout shift */
      if (scrollbarWidth) {
        document.body.style.paddingRight = `${scrollbarWidth}px`
      }
```

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (mcbouslog) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js:78]: Thank you for this breakdown between subject and workflow configs! I think I'm going to convert the previous comment to it's own issue.

[the remark this answers is not in the document]
Comment (mcbouslog) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js:78]: Otherwise I think the wheel zoom values (1.1 and 0.9) feel appropriate and are preferably standardized as such (as opposed to set via config).

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js (hunk 12 above)
Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js:110]: Sure, that should be fine (but do check in desktop Safari.)

The underlying problem here is that `ZoomEventLayer` uses React's `onWheel`, which fires passive events. 

If you update `ZoomEventLayer` to fire active events, with `passive: false`, that might remove some of these hacks that work around passive wheel events. That would be a PR in its own right, however.

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.js [hunk 13]
```diff
@@ -205,55 +207,31 @@ function ZoomingScatterPlot({
...
-      tickDirection={tickDirection}
       top={topPosition}
       width={width}
-      zoomingComponent={ScatterPlot}
+      zoomingComponent={(zoomProps) => (
+        <ScatterPlot {...zoomProps} {...scatterPlotProps} />
+      )}
       zoomConfiguration={zoomConfiguration}
       zooming={zooming}
-      {...props}
```
Comment (mcbouslog) [inline packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.js:223]: I think `setOnPan` and `setOnZoom` that are included in the old `...props` / or new `...scatterPlotProps` need to be passed as props to the `<VisXZoom>` component here for the toolbar to work.

**Comment by mcbouslog** [comment]
This is looking really good, thank you @eatyourgreens ! 

I think the key open item (unrelated to these code changes) is which key to use, which I'm going to continue discussing #6758 .

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js (hunk 6 above)
Comment (mcbouslog) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js:12]: Added the info regarding the meta key and control key, as well as a few other notes about the potential hot keys in https://github.com/zooniverse/front-end-monorepo/issues/6758#issuecomment-2730967783 .

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js [hunk 14]
```diff
@@ -142,58 +219,96 @@ function VisXZoom({
...
-              onWheel={throttledOnWheel}
-              panning={panning}
-              tabIndex={0}
-              width={width}
-            />
-          </ZoomingComponent>
+          <g ref={wheelEventLayer}>
+            <ZoomingComponent
+              initialTransformMatrix={_zoom.initialTransformMatrix}
+              move={move}
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js:232]: I accidentally left this in from an earlier version of this PR. It doesn't do anything. 

```suggestion
```

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.js (hunk 13 above)
Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.js:223]: Good catch. The list of props for `ScatterPlotViewer` is quite long and confusing. 

https://github.com/zooniverse/front-end-monorepo/blob/aed398d41e9aa30d9690e726e47ecde13f99c30f/packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ScatterPlot/ScatterPlot.js#L224-L286

Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.js:223]: Fixed!

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js (hunk 12 above)
Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js]: Fixed!

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js (hunk 14 above)
Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SVGComponents/VisXZoom/VisXZoom.js]: Fixed!

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.js (hunk 13 above)
Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/ScatterPlotViewer/components/ZoomingScatterPlot/ZoomingScatterPlot.js:223]: Weird that this didn't break the tests at all (but did break the zoom in/out buttons for scatter plot stories in the storybook.)

**Review by mcbouslog — APPROVED** [review]
Recent changes look good, this is good to go 🚀 

Thank you @eatyourgreens
