### PR TITLE
fix(lib-classifier): screen scale calculations for SVG subject images

### LINKED ISSUE #6881: Drawn mark unexpected interactions after proceeding from step drawn
## Package
- lib-classifier

## Describe the bug
After drawing a mark, then proceeding to the next step, the drawn mark appears smaller than expected. After going back to the step with the drawing task, dragging the mark is not at the expected scale of movement.

## To Reproduce
1. Go to https://www.zooniverse.org/projects/aeuk/elephant-id/classify/workflow/24547?demo=true
2. Draw a mark
3. Go to the next step
4. Note smaller than expected mark
5. Go back to the previous step
6. Note dragging the mark is not at the expected scale

## Screenshots
https://github.com/user-attachments/assets/aa6c2a62-2382-49e1-a385-6a722a2e5765

## Expected behavior
The drawn mark has consistent size and dragging interactions regardless of step.

### Desktop (please complete the following information):
 - OS: MacOS Sonoma v14.7.4
 - Browser: Chrome v135

### PR DESCRIPTION
**Pull request by eatyourgreens**
Update `useScale` to check if the `canvas` DOM node exists before calculating the subject image scale on the screen.

Update `isInBounds` to also catch the case where `svgContext.canvas` is undefined or null.

Fix `canvasRef` in `SingleImageCanvas` so that it reports the correct dimensions for the subject image, in Firefox.

Remove the `canvasRef` hack from `InteractionLayer`, now that `SingleImageCanvas` is fixed.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
- lib-classifier

## Linked Issue and/or Talk Post
- fixes #6881

## How to Review
Should be the same as #6882.

You'll want to check that this hasn't regressed #6490, so be sure to check in Firefox, with the subject zoomed in. Remember to test with a rotated image too, to make sure that rotation transforms are still correctly accounted for.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [x] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [x] Can submit a classification
- [x] Can sign-in and sign-out
- [x] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [x] The PR creator has listed user actions to use when testing if bug is fixed
- [x] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

**Comment by eatyourgreens** [comment]
https://github.com/zooniverse/front-end-monorepo/pull/6887/commits/e4194b702982740995a8dea7ffcb046bc523d153 should fix #6490, or at least stop it from regressing in this PR.

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageCanvas.js [hunk 1]
```diff
@@ -34,36 +34,33 @@ function SingleImageCanvas({
           transformMatrix
         }}
       >
-        <svg
+        <g
           ref={canvasLayer}
+          data-testid='single-image-canvas-visxzoom-transform-group'
+          transform={transform}
         >
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageCanvas.js:41]: I'm guessing this got broken in the move to `VisXZoom`, but you want to  use the `<g>` element as the subject canvas, since it wraps the entire subject image.

The `<svg>` element was constrained to the visible viewport, so wouldn't have given the correct dimensions, in turn leading to incorrect scale calculations for the rendered image on the screen.

Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageCanvas.js]: On second thoughts, I've left the parent `<svg>` in this comppnent. My original pass at fixing this removed the nested `<svg>`, but I'm not sure if it was important to establish a new SVG viewport here, so I've changed my mind and left in.

Changing the ref from the `<svg>` element to the `<g>` element should be sufficient to fix the incorrect canvas sizing in Firefox.

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js [hunk 2]
```diff
@@ -52,8 +52,10 @@ function InteractionLayer({
 }) {
   const [creating, setCreating] = useState(false)
   const svgContext = useContext(SVGContext)
-  const canvasRef = useRef()
-  svgContext.canvas = canvasRef.current
+  const canvasRef = useRef(null)
+  if (canvasRef.current !== null) {
+    svgContext.canvas = canvasRef.current
+  }
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js:58]: Now that the canvas ref is fixed in Firefox, in `SingleImageCanvas`, I don't know if these lines are still needed.

Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/InteractionLayer/InteractionLayer.js]: Removed in https://github.com/zooniverse/front-end-monorepo/pull/6887/commits/2d29d57284208ce837e1a6b461ade1392bba61a2.

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageCanvas.js [hunk 3]
```diff
@@ -34,14 +34,13 @@ function SingleImageCanvas({
...
-        <svg
-          ref={canvasLayer}
-        >
+        <svg>
           <g
             data-testid='single-image-canvas-visxzoom-transform-group'
             transform={transform}
           >
             <g
+              ref={canvasLayer}
```
[the remark this answers is not in the document]
Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/SingleImageViewer/SingleImageCanvas.js:43]: Prior to #6390, this ref was inside the SVG transforms that are applied to the subject and drawing marks. I've restored that behaviour here.

**Review by mcbouslog — APPROVED** [review]
Thank you @eatyourgreens ! I tested in Chrome, Firefox, and Safari; drawing in different viewers, rotating, moving drawn marks (including out of bounds), going back and forth between multiple steps - and all work as expected.
