### PR TITLE
Classifier tasks: Copy task.required for legacy dropdowns

### LINKED ISSUE #3639: Dropdown task marked as required, not required
## Package
- lib-classifier

## Describe the bug
A dropdown task set as required doesn't have to be answered to proceed with Done or Next in the classifier.

## To Reproduce
0. Create workflow with dropdown task that's required - (production test project - https://www.zooniverse.org/lab/4312/workflows/3852)
1. Go to production test project - https://frontend.preview.zooniverse.org/projects/markbouslog/test-project-mb/classify/workflow/3852
2. Note can click Done or Done & Talk

## Expected behavior
Done, Done & Talk, or Next is disabled for a required task until answered, production test project - https://www.zooniverse.org/projects/markbouslog/test-project-mb/classify?reload=0&workflow=3852

## Additional context
Staging test project:
- lab - https://master.pfe-preview.zooniverse.org/lab/1693/workflows/3504?env=staging
- PFE - https://www.zooniverse.org/projects/markb-panoptes/test-project-1-mb-fem-lab/classify?reload=0&workflow=3504&env=staging
- FEM - https://frontend.preview.zooniverse.org/projects/markb-panoptes/test-project-1-mb-fem-lab/classify/workflow/3504?env=staging

### PR DESCRIPTION
**Pull request by eatyourgreens**
Copy the `required` flag across when creating simple dropdown tasks from legacy dropdown tasks.

## Package
lib-classifier/src/plugins/tasks/simple-dropdown

## Linked Issue and/or Talk Post
- fixes #3639 

## How to Review
The dropdown task should require an answer now, on this test workflow.
https://frontend.preview.zooniverse.org/projects/markbouslog/test-project-mb/classify/workflow/3852

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [x] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [x] Can submit a classification
- [x] Can sign-in and sign-out
- [x] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [x] The PR creator has listed user actions to use when testing if bug is fixed
- [x] The bug is fixed
- [x] Unit tests are added or updated

### CODE REVIEW

File: packages/lib-classifier/src/plugins/tasks/dropdown-simple/models/helpers/legacyDropdownAdapter/legacyDropdownAdapter.js [hunk 1]
```diff
@@ -6,6 +6,7 @@ export function legacyDropdownAdapter(snapshot) {
     newSnapshot.allowCreate = menu.allowCreate
     newSnapshot.help = snapshot.help
     newSnapshot.instruction = snapshot.instruction
+    newSnapshot.required = snapshot.required
```
Comment (mcbouslog) [inline packages/lib-classifier/src/plugins/tasks/dropdown-simple/models/helpers/legacyDropdownAdapter/legacyDropdownAdapter.js:9]: It looks like the `required` property is stored in the individual `selects`. I think this line maybe should be `menu.required`, but I'm not entirely sure, will dig into more tomorrow.

Here's a screenshot from the linked workflow:
Screen Shot 2022-09-13 at 6 14 54 PM

Comment (eatyourgreens) [reply packages/lib-classifier/src/plugins/tasks/dropdown-simple/models/helpers/legacyDropdownAdapter/legacyDropdownAdapter.js:9]: Ohhhhhhh, that would explain it.

Comment (eatyourgreens) [reply packages/lib-classifier/src/plugins/tasks/dropdown-simple/models/helpers/legacyDropdownAdapter/legacyDropdownAdapter.js]: I've updated the dropdowns in the tests to match your screenshot, and I've updated the code to pass the tests. It should work now.

**Review by mcbouslog — APPROVED** [review]
LGTM, thanks! 

Tested on "Dropdown - Required" and "Dropdown - NOT Required" workflows here - https://local.zooniverse.org:8080/?project=markb-panoptes%2Ftest-project-1-mb-fem-lab&workflow=3504
