### PR TITLE
fix(lib-content): accessible sidebar links for screenreaders and keyboard users

### LINKED ISSUE #6289: About page: keyboard navigation is broken for internal links
## Describe the bug
When I tab through the About page from the links in the side menu, keyboard focus jumps back to the top of the page. This makes the internal links impossible to use either from the keyboard or in a screen reader.

## To Reproduce

1. Click on https://www.zooniverse.org/about
1. Click on Contact Us in the side menu, or tab through the page to it and press Enter.
1. Pressing Tab will now jump focus back to the top of the page.

## Screenshots

https://github.com/user-attachments/assets/23bdc73b-d596-49bb-b6ac-1734e93fbcf1

## Expected behavior
To see the expected behaviour, load https://www.zooniverse.org/about#contact and then press Tab. Focus should go to the first link within the Contact Us section.

## Additional Context

When you follow a link with a fragment identifier, like `#contact`, focus should go to the targeted element. This is particularly important for blind readers, who won't see that the page has scrolled down in the browser window and rely on reading focus being placed correctly.

https://www.tpgi.com/how-to-avoid-breaking-web-pages-for-keyboard-users/#videodemo

EDIT: this bug is present in the `fe-content-pages` app, but not in the `fe-root` app. That's weird, but I think it's still caused by using the client-side Next router for in-page links. I think the `Link` component for the pages router is overriding default browser behaviour, maybe by calling `event.preventDefault()`.

- You can reproduce it here: https://fe-content-pages.preview.zooniverse.org/about.
- But not here: https://fe-root.preview.zooniverse.org/about.

### PR DESCRIPTION
**Pull request by eatyourgreens**
- Remove `next/link` from sidebar links, so that the browser focuses the linked heading when you follow an in-page link on one of the About pages.
- Link the 'Our Mission' link to its corresponding heading on the About page, so that readers aren't sent back to the top of the page body.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
- lib-content

## Linked Issue and/or Talk Post
- closes #6289.

## How to Review
In a screenreader, like NVDA or VoiceOver, reading focus should now move to the linked heading when you follow a sidebar link. Similarly, focus should move logically through the page when you tab through the page and follow sidebar links from the keyboard. See [WCAG 2.4.3: Focus order](https://www.w3.org/WAI/WCAG22/Understanding/focus-order.html).

Testing this PR revealed some other WCAG failures on the About page. They aren't addressed here, so will also need to be fixed:
- no clear focus indicator on links within the How It Works section ([WCAG 2.4.7: Focus visible](https://www.w3.org/WAI/WCAG22/Understanding/focus-visible.html)).
- the Contact Us button opens a popup form that isn't accessible via the keyboard or with a screenreader ([WCAG 2.1.1: Keyboard](https://www.w3.org/WAI/WCAG22/Understanding/keyboard)).

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

File: packages/lib-content/src/components/Sidebar/Sidebar.js [hunk 1]
```diff
@@ -1,4 +1,3 @@
-import Link from 'next/link'
```
Comment (goplayoutside3) [inline packages/lib-content/src/components/Sidebar/Sidebar.js:1]: This component corresponds to DropdownNav which needs the same refactoring. I'll do that before merging.

**Review by goplayoutside3 — APPROVED** [review]

**Comment by goplayoutside3** [comment]
Thanks!
