### PR TITLE
Finished for day bug

### LINKED ISSUE #542: Styling bugs in `Finished for the day?` widget
**Package**

app-project

There are two minor styling bugs in this widget:

1. The project image doesn't resize to match the height of the text content (note the bottom of the cat image).

    Screenshot 2019-03-13 21 24 55

1. The buttons extend beyond the width of the container before hitting the narrow breakpoint.

    Screenshot 2019-03-13 21 25 11

### PR DESCRIPTION
**Pull request by wgranger**
Package:
app-project

Closes #542  .

Describe your changes:
This branch fixes the two styling bugs mentioned in the issue above. The second issue occurs because the [default](https://github.com/grommet/grommet/wiki/Grommet-v2-theming-documentation) `global.breakpoints.small.value` is 768, which cause the components to wrap too late. 

# Review Checklist

## General

- [x] Are the tests passing locally and on Travis?
- [x] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [x] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [x] Does it work on mobile?
- [x] Can you `rm -rf node_modules/ && npm install` and app works as expected?

### CODE REVIEW

File: packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/ProjectImage/ProjectImage.js [hunk 1]
```diff
@@ -19,7 +19,7 @@ function ProjectImage ({ imageSrc, projectName }) {
   return (
     <Media
       alt={alt}
-      height={200}
+      height={"auto"}
```
Comment (rogerhutchings) [inline packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/ProjectImage/ProjectImage.js]: This can just be `height='auto'`

Comment (wgranger) [reply packages/app-project/src/screens/ClassifyPage/components/FinishedForTheDay/components/ProjectImage/ProjectImage.js]: Whoops, don't know why I did this.
