### PR TITLE
Daily Classifications Chart: fix locale

### LINKED ISSUE #3463: Project: Daily Classifications Chart sets an invalid locale
https://github.com/zooniverse/front-end-monorepo/blob/630457d873e600acd003b995ec01a0c3c3055706/packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.js#L15-L20

`sanitizedLocale` is set to the `router` object here, not the current locale.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Set the sanitised locale to the router locale, or English.

## Linked Issue and/or Talk Post
- Fixes #3463.
- I've removed the mock router from tests, towards #3429.

## How to Review
Check the Daily Classifications Chart story with different locales, I think.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [x] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [x] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [x] Can submit a classification
- [x] Can sign-in and sign-out
- [x] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [x] The PR creator has listed user actions to use when testing if bug is fixed
- [x] The bug is fixed
- [x] Unit tests are added or updated

### CODE REVIEW

File: packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.js [hunk 1]
```diff
@@ -9,24 +8,18 @@ const defaultCounts = {
 
 function DailyClassificationsChartContainer({
   counts = defaultCounts,
+  locale='en',
```
Comment (goplayoutside3) [inline packages/app-project/src/screens/ClassifyPage/components/YourStats/components/DailyClassificationsChart/DailyClassificationsChartContainer.js:11]:
```suggestion
  locale = 'en',
```

**Review by goplayoutside3 — APPROVED** [review]
Looks good!
