### PR TITLE
Display Media images inline

### LINKED ISSUE #2462: Markdownz: Consecutive images can't render inline with each other
## Package
lib-react-components

## Describe the bug

- When using markdown in PFE, multiple, consecutive images can be rendered inline with each other if their widths are small enough:

PFE Galaxy Zoo Example:
pfe

- When viewing the same project with FEM, consecutive images stack on top of each other instead.

FEM Galaxy Zoo Example:
fem

The above example is a screenshot of FEM storybook related to PR #2463 .

In `remark-react`, react components are mapped to html elements, but the custom function mapped to markdown image strings is returning `Media` components inside a `<p>`. This means multiple images cannot be rendered inline with each other even if their widths are small enough.

Note: The current implementation of FEM `Markdownz` is using outdated `remark` packages, and upgrading to the latest may help solve this issue.

## To Reproduce
- Can compare PFE [Galaxy Zoo](https://www.zooniverse.org/projects/zookeeper/galaxy-zoo/about/research) research page and [FEM Galaxy Zoo research page](https://frontend.preview.zooniverse.org/projects/zookeeper/galaxy-zoo/about/research).

## Expected behavior
Consecutive images written in markdown should render side by side if their widths are small enough.

### PR DESCRIPTION
**Pull request by eatyourgreens**
- Display `Media` images with `inline-flex`, rather than `flex`, columns.
- Replace the container element with `span`, rather than `div`, so that media images can be displayed inside paragraphs.
- `Markdownz`: Convert line breaks to `<br>` with [`remark-breaks@2.02`](https://www.npmjs.com/package/remark-breaks/v/2.0.2).
- Bump `@zooniverse/react-components` to 1.6.2.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
lib-react-components

## Linked Issue and/or Talk Post
- Closes #2462.

## How to Review
Images on the Galaxy Zoo Research page now display inline, as expected.
Inline images of galaxies on the Galaxy Zoo Research page.

However, there could be project teams that have relied on the incorrect, block display for images in their field guides etc., so that needs checking.

Here's the Galaxy Zoo field guide on this branch. Images are displayed inline, within paragraphs, and line breaks are converted to `<br>`*.

The Galaxy Zoo field guide, demonstrating inline images and line breaks within paragraphs.

*this is non-standard markdown but matches how [`markdownz`](https://www.npmjs.com/package/markdownz) parses markdown to HTML. Standard markdown uses whitespace to represent line breaks, but this is controversial, quite hard to use in practice, and would mean converting all the non-standard markdown used by our projects.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [x] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

File: packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.js [hunk 1]
```diff
@@ -1,13 +1,21 @@
...
+import styled, { css } from 'styled-components'
+
 import getThumbnailSrc from '../../helpers/getThumbnailSrc.js'
 import { propTypes, defaultProps } from '../../helpers/mediaPropTypes.js'
 import useProgressiveImage from '../../../hooks/useProgressiveImage.js'
 
+const InlineBlock = styled(Box)`
+  display: inline-block;
+  ${props => props.height && css`max-height: ${props.height};`}
+  ${props => css`max-width: ${props.width || '100%'};`}
```
Comment (goplayoutside3) [inline packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.js:11]: I reviewed all storybooks on this branch and the changes are looking good so far. Before I move on to comparing FEM projects, I want to ask about handling of dimensions here.

On this branch, the Media story in lib-react-components shows an example of a Media component given only a custom height, and the behavior there is to crop the image. 
production

However, on this branch, the height-only image looks layered behind the next image or might be overflowing its container:
branch

Is there a way to handle height-only Media components with the changes to ThumbnailImage in this branch?

Comment (goplayoutside3) [reply packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.js:11]: Another related note is that the placeholder image used in the Media story shows up differently here than production. For instance, on this branch the placeholder is smaller than its containing Media component:
grey

But in production, the placeholder is teal and matches the dimensions of the Media component (200x200):
teal

I think we'd like to keep the placeholder the same size as the Media component when it's given a height and width - is that the correct assumption?

File: packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.js [hunk 2]
```diff
@@ -30,26 +38,21 @@ export default function ThumbnailImage({
...
   return (
     <>
       {loading ?
         <Placeholder height={cssHeight} flex={flex} width={cssWidth} {...rest}>{placeholder}</Placeholder> :
-        <Box
+        <InlineBlock
           animation={loading ? undefined : 'fadeIn'}
+          as='span'
           className='thumbnailImage'
-          flex={flex}
```
Comment (eatyourgreens) [inline packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.js:50]: `flex` has been removed by mistake here.

File: packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.js (hunk 1 above)
Comment (eatyourgreens) [reply packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.js:11]: I imagine we can handle those changes by reverting to flexbox. I didn't see any regressions on project pages, but I'm not sure where those might be using the placeholder, or height-only media.

Comment (eatyourgreens) [reply packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.js]: Yep, `inline-flex` fixes the storybook layout.

Comment (eatyourgreens) [reply packages/lib-react-components/src/Media/components/ThumbnailImage/ThumbnailImage.js]: The original changes here weren't passing through Grommet's style props to the `Box` component either. Hence the background colour vanishing, and so on. That's fixed now.

**Comment by goplayoutside3** [comment]
The placeholder and height styling look much better - thanks!

I compared several deployed FEM projects compared to running this branch locally and found two differences. I think the first one needs addressing, but the second may be fine as is.

1. The MultiFrameViewer's FrameCarousel thumbnails. In Davy Notebooks, the thumbnails are always square with the subject image as "cover", but on this branch the thumbnail looks "contain" and not square:
production
branch

---

2. Because of the change from block to inline, images now have the infamous extra padding on the bottom. It's only a few pixels, but noticeable in places where images stack one right after the other. I'm not sure it's a blocking change, but wanted to get your option on whether the extra space is noticeable and an easy fix. You can see the extra space in the Markdownz grid example too: http://localhost:6007/?path=/story/components-markdownz--grid-example. Example from TESS:
tess p
tess branch

**Comment by eatyourgreens** [comment]
Those preview thumbnails on Davy Notebooks haven’t been styled with [aspect-ratio](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio) so that might fix them.

**Comment by eatyourgreens** [comment]
Whitespace between images looks ok in mobile Safari. We might have to live with it if it’s a bug in Chrome. 

IMG_4885

**Comment by eatyourgreens** [comment]
The storybook example images are separated by a space and a line break. If you delete that, you should see the images run into each other.

Storybook example images displayed inline, with no space between them.

I think Galaxy Zoo's field guide and Research page have examples of markdown images with no whitespace between them in the mardown.

**Review by goplayoutside3 — APPROVED** [review]
Thanks for fixing the FrameCarousel UI!

Regarding the extra space on the bottom of an image, I was referring to the known browser behavior when displaying inline elements: https://stackoverflow.com/questions/5804256/image-inside-div-has-extra-space-below-the-image.

I don't think the extra few pixels of bottom padding is disruptive to project owners using markdown, but good to keep in mind in case there's confusion in the future.
