### PR TITLE
fix(lib-react-components): project card badge width in Safari

### LINKED ISSUE #6313: Classification count toast is squashed horizontally
## Package
_Choose from the list:_
- app-root

## Describe the bug

On the new home page, the classification count toast, on project cards, is squashed horizontally for small numbers. 

Project cards, showing that the classification count isn't a circle for small counts.

## Expected behavior
Circular toasts, like the old project cards, look a lot better. 

Old school project cards with circular classification count toasts in the top right.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Add a minimum width and a height to the project card badge.

>At least one of the box's sizes needs to be automatic in order for aspect-ratio to have any effect. If neither the width nor height is an automatic size, then the provided aspect ratio has no effect on the box's preferred sizes.

https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
- lib-react-components

## Linked Issue and/or Talk Post
- fixes #6313.

## How to Review
You can use the `ProjectCard` stories to test this. The badge should now be circular in Safari, even when the number is small.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

File: packages/lib-react-components/src/ProjectCard/ProjectCard.js [hunk 1]
```diff
@@ -52,6 +52,8 @@ const StyledBadge = styled(Text)`
   text-align: center;
   align-items: center;
   justify-content: center;
+  min-width: 1em;
```
Comment (eatyourgreens) [inline packages/lib-react-components/src/ProjectCard/ProjectCard.js:55]: Should this be `1rem`?

**Review by goplayoutside3 — APPROVED** [review]
Thanks!
