### PR TITLE
Background refresh project Talk recent subjects

### LINKED ISSUE #5589: Project home page: recent Talk subjects are out-of-order
## Package
_Choose from the list:_
- [ ] app-content-pages
- [x] app-project
- [ ] lib-classifier
- [ ] lib-panoptes-js
- [ ] lib-react-components
- [ ] unknown

## Describe the bug
Recent Talk subjects, on the project home page, aren't shown in the order that comments were made.

## To Reproduce
In this screen recording, from #5588, I add a new comment to a subject. The new subject is added to the middle of the list on the project home page.

https://github.com/zooniverse/front-end-monorepo/assets/59547/62e42e62-f31e-48a4-999c-21282e9272f9

## Expected behavior
New subject comments should be added to the beginning of the list.

## Additional context

`am.zooni` brought this up on Talk here:
- [sequence of subjects on project home pages](https://www.zooniverse.org/talk/14/3155388?page=1&scrollToLastComment=true).

You can compare the recent comments list on old and new home pages here:
- [PFE (subjects in expected order.)](https://master.pfe-preview.zooniverse.org/projects/eatyourgreens/-project-testing-ground/?env=staging)
- [Monorepo (subjects out-of-order.)](https://frontend.preview.zooniverse.org/projects/eatyourgreens/-project-testing-ground?env=staging)

### PR DESCRIPTION
**Pull request by eatyourgreens**
Refactor home page `RecentSubjects` to use `useSWR`. The `RecentSubjects` component, on the project home page, will now refresh in the background when the fetched API data is stale.

Preserve the subject comment order when fetching subjects from Panoptes.

- Closes #5589.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
- app-project

## How to Review
With a project home page open in a tab, the list of recent Talk subjects should now refresh in the background when recent subject comments change in Panoptes. Previously, you would have to reload the page to see new comments.

Here, I open the project home page in one tab, leave a new subject comment in another tab, then see the recent subjects update in the original tab.

https://github.com/zooniverse/front-end-monorepo/assets/59547/87194006-9ba0-44f3-8fc8-6b28352a7047

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Refactoring
- [ ] The PR creator has described the reason for refactoring
- [ ] The refactored component(s) continue to work as expected

### CODE REVIEW

File: packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/helpers/fetchRecentSubjects/fetchRecentSubjects.js [hunk 1]
```diff
@@ -2,14 +2,12 @@ import fetchSubjectData from './fetchSubjectData'
...
-async function fetchRecentSubjects (projectId) {
+async function fetchRecentSubjects ({ projectId }) {
   const talkData = await fetchTalkData(projectId)
 
   if (talkData.length > 0) {
     const subjectIds = getSubjectIdsFromTalkData(talkData)
-    const subjects = await fetchSubjectData(subjectIds)
-      .then(response => response.body.subjects)
-    return subjects
+    return await Promise.all(fetchSubjectData(subjectIds))
```
Comment (eatyourgreens) [inline packages/app-project/src/screens/ProjectHomePage/components/ZooniverseTalk/components/RecentSubjects/helpers/fetchRecentSubjects/fetchRecentSubjects.js:10]: This works, but breaks the tests.

**Review by goplayoutside3 — APPROVED** [review]
Looks good!
