### PR TITLE
Classifier storybook: Add `previousAnnotationValues` to Tasks

### LINKED ISSUE #2996: Classifier: 'Text task with suggestions' story doesn't show suggestions
## Package
lib-classifier

## Describe the bug
The 'Text task with suggestions' story shows a plain text task, without any suggested text.
https://zooniverse.github.io/front-end-monorepo/@zooniverse/classifier/index.html?path=/story/tasks-text--with-suggestions&globals=locale:en;locales.en:English;locales.test:Test+Language

## Expected behavior
There should be a dropdown menu with a list of previous lines to choose from.

### PR DESCRIPTION
**Pull request by eatyourgreens**
`previousAnnotationValues` is a map of previous annotations, by task key, which can be used to pass `subTaskPreviousAnnotationValues` down to individual tasks.

- Adds previous annotation values to the 'Text task with suggestions' story, so that suggestions work again.
- Removes the deprecated `Component.defaultProps` from text tasks.

To test this out, run the classifier storybook and check that the 'Text task with suggestions' story shows suggestions.
Screenshot of the text task suggestions story, with an open menu showing options for 'a', 'b' and 'c'.

## Package
lib-classifier

Closes #2996.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [x] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [x] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [x] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [x] Can submit a classification
- [x] Can sign-in and sign-out
- [x] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Bug Fix
- [x] The PR creator has listed user actions to use when testing if bug is fixed
- [x] The bug is fixed
- [ ] Unit tests are added or updated

## Refactoring
- [x] The PR creator has described the reason for refactoring
- [x] The refactored component(s) continue to work as expected

### CODE REVIEW

File: packages/lib-classifier/src/plugins/tasks/text/components/TextTask/TextTask.js [hunk 1]
```diff
@@ -9,9 +9,15 @@ Special case: literal insertion tags
...
-  const { annotation, autoFocus, disabled, subTaskPreviousAnnotationValues, task } = props
+function TextTask ({
+  annotation,
+  autoFocus = false,
+  disabled = false,
+  subTaskPreviousAnnotationValues = [],
+  task
+}) {
   const { value } = annotation
+  console.log({ subTaskPreviousAnnotationValues })
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/plugins/tasks/text/components/TextTask/TextTask.js:20]: Oops!

File: packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Task/Task.js [hunk 2]
```diff
@@ -54,6 +60,7 @@ function Task ({
         autoFocus={autoFocus}
         disabled={disabled}
         annotation={annotation}
+        subTaskPreviousAnnotationValues={subTaskPreviousAnnotationValues}
```
Comment (eatyourgreens) [inline packages/lib-classifier/src/components/Classifier/components/TaskArea/components/Tasks/components/Task/Task.js:63]: The name of this is a bit misleading. It isn't restricted to drawing sub-tasks.

**Review by mcbouslog — APPROVED** [review]
This LGTM, tested with Davy Notebooks and on [a staging project with a drawing task with multiple subtasks](https://local.zooniverse.org:3000/projects/markb-panoptes/fem-drawing-tools/classify/workflow/3405?env=staging) and tasks function as expected. Confirmed the storybook is updated and now shows suggestions.

I'll coordinate on Slack before merging, this PR or #3001 will likely need rebasing.
