### PR TITLE
Refactor ClassifierContainer to use snapshots and fix broken tests

### LINKED ISSUE #5073: Classifier errors when storing a project
## Package
app-project
lib-classifier

## Describe the bug
The Classify page is passing invalid project snapshots into the `Classifier` component. The classifier's `Project` model expects projects to have `project.display_name` but project snapshots have `project.strings.display_name`.

When the classifier loads, the store errors and doesn't store the project. The error is silently swallowed, but `classifierStore.projects.active` will be undefined.

## To Reproduce
Load any project and look for this error:
>Error: [mobx-state-tree] Error while converting `{"about_pages":[{"id":"9473","title":"Results","url_key":"results"},{"id":"9475","title":"FAQ","url_key":"faq"},{"id":"9471","title":"Research","url_key":"science_case"},{"id":"9472","title":"Team","url_key":"team"}],"avatar":{"id":"43301643","href":"/projects/7929/avata......":""}]}` to `ProjectResource`:
>
>    at path "/display_name" value `undefined` is not assignable to type: `string` (Value is not a string).

## Expected behavior
The project snapshot should be stored as `classifierStore.projects.active`, so that it can be referenced by other models that use the project.

## Additional context
Errors when storing resources are silently swallowed here, and logged to the console.
https://github.com/zooniverse/front-end-monorepo/blob/9245c1e6e48419f6e0caea76ec71d4020c4bd433/packages/lib-classifier/src/store/ResourceStore/ResourceStore.js#L76-L86

### PR DESCRIPTION
**Pull request by eatyourgreens**
- Refactor `ClassifierContainer` to apply new project and workflow data to the store state with `applySnapshot`.
- Add missing mocks for the Panoptes translations API to the tests.
- Fix a bug in the tests where the tests for French translations are looking for the English task answers.
- Fix a bug where project snapshots are not being stored for any projects (#5073.)

MobX State Tree has a built-in [snapshots API](https://mobx-state-tree.js.org/concepts/snapshots) for working with store state, so let's use that instead of our own homegrown API to initialise classifier state from Panoptes (or from local snapshots if we're returning to the page from Talk.)

- Closes #5073.

_Please request review from `@zooniverse/frontend` team or an individual member of that team._ 

## Package
lib-classifier

## How to Review
You can test workflow loading with the dev classifier and a project like Gravity Spy. Workflows should still load properly when you select a new workflow.
https://localhost:8080/?project=zooniverse/gravity-spy&env=production&workflow=1610

The `ClassifierContainer` tests for the `fr` locale should now correctly fail with English answer strings. I'm not sure how I missed that in #5038.

Other tests should now have mock English translations, which were also missed in #5038.

Invalid project snapshot errors should be fixed now, when the classifier is run inside the NextJS project app and the project is passed down as a snapshot from the project app store.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [ ] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [ ] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [ ] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [ ] FEM works in a mobile browser

## General UX
Example Staging Project: [i-fancy-cats](https://local.zooniverse.org:3000/projects/brooke/i-fancy-cats)
- [ ] All pages of a FEM project load: Home Page, Classify Page, and About Pages
- [ ] Can submit a classification
- [ ] Can sign-in and sign-out
- [ ] The component is accessible
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - It is passing accessibility checks in the storybook

## Refactoring
- [ ] The PR creator has described the reason for refactoring
- [ ] The refactored component(s) continue to work as expected

### CODE REVIEW

File: packages/lib-classifier/src/store/Project/Project.js [hunk 1]
```diff
@@ -17,7 +19,11 @@ const Project = types
         [singleActiveWorkflow] = self.links['active_workflows']
       }
       return singleActiveWorkflow
-    }
+    },
+
+    get display_name() {
+      return self.strings.get('display_name')
+    },
```
Comment (goplayoutside3) [inline packages/lib-classifier/src/store/Project/Project.js:26]: Why is `display_name` changed to a `get` function instead of the model property?

File: packages/lib-classifier/src/components/Classifier/ClassifierContainer.js [hunk 2]
```diff
@@ -115,27 +117,33 @@ export default function ClassifierContainer({
...
   */
- const storedWorkflow = classifierStore.workflows.resources.get(workflowID)
-
- if (workflowSnapshot?.id && workflowStrings) {
-   workflowSnapshot.strings = workflowStrings
-    if (!storedWorkflow) {
-      classifierStore.workflows.setResources([workflowSnapshot])
+  const storedWorkflow = classifierStore.workflows.resources.get(workflowID)
+  if (workflowIsReady && !storedWorkflow) {
+    const storedWorkflows = getSnapshot(classifierStore.workflows)
```
[the remark this answers is not in the document]
Comment (eatyourgreens) [reply packages/lib-classifier/src/components/Classifier/ClassifierContainer.js:136]: If the project has more than one workflow in the store, then this is grabbing a snapshot of those other workflows.

File: packages/lib-classifier/src/store/Project/Project.js (hunk 1 above)
Comment (eatyourgreens) [reply packages/lib-classifier/src/store/Project/Project.js:26]: The model property doesn't exist in the incoming snapshot, leading to the error in #5073. Since translations were added, the display name is stored in `project.strings.display_name`.

**Review by mcbouslog — APPROVED** [review]
Code changes LGTM; fixes project display_name issue, workflow store applySnapshot refactors, and related tests.

Tested on staging project and PH TESS for translations changes and a project with multiple workflows without issue.

🚀
