### PR TITLE
Project: ContentBox: remove client-side links

### LINKED ISSUE #2012: Routing to stats page for PH TESS is broken
## Expected Behavior
Clicking the "view more stats" button on project homepage take you to project stats view (classification and Talk histograms).

## Current Behavior
Clicking the "view more stats" button results in a "This page isn't built yet" error message.  

Screen Shot 2021-02-01 at 10 32 58 AM

I'll note that the message appears to imply that some piece of code is still in development mode -- seems out of the ordinary.

## To Reproduce
1. Go to https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/stats
2. Click on "view more stats" button

### Desktop (please complete the following information):
 - OS: Mac 10.14
 - Browser: Chrome 87.0.4280.141

cc: @srallen -- following up from morning stand-up

### PR DESCRIPTION
**Pull request by eatyourgreens**
We aren't linking to any client-side pages from the ContentBox component, so this replaces Link with Anchor, which will load a new page in the browser. It also adds tests and fixes a small typo (linkUrl should be linkProps.)

Further down the line, we may want logic that renders `Link` or `Anchor`, depending on whether the target page is part of the NextJS app.

Package:
app-project

Closes #2012.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

File: packages/app-project/src/shared/components/ContentBox/ContentBox.js [hunk 1]
```diff
@@ -53,13 +53,11 @@ function ContentBox (props) {
...
-            <Link {...linkProps} passHref>
-              <Anchor>
-                <SpacedText>
-                  {linkLabel}
-                </SpacedText>
-              </Anchor>
-            </Link>
+            <Anchor {...linkProps}>
+              <SpacedText>
+                {linkLabel}
```
Comment (eatyourgreens) [inline packages/app-project/src/shared/components/ContentBox/ContentBox.js:58]: Not related to this bug fix, but would it make more sense if the link text was part of the link props?
```js
linkProps = {
  href: '/projects/test/owner/stats',
  label: 'View more stats'
}
```
I'm guessing it's passed separately because `linkProps` was meant to represent a set of props for [`next/link`](https://nextjs.org/docs/api-reference/next/link), which are different from the props for Grommet's [Anchor](https://v2.grommet.io/anchor).

**Review by srallen — APPROVED** [review]

File: packages/app-project/src/shared/components/ContentBox/ContentBox.js (hunk 1 above)
Comment (eatyourgreens) [reply packages/app-project/src/shared/components/ContentBox/ContentBox.js:58]: True. I think `NavLink` does that, but the check will break with the new router API. #1973
