### PR TITLE
fix content pages pages when API data is unavailable

### LINKED ISSUE #1499: Local production builds of the content pages app give 500 errors
**Package**
app-content-pages

**Describe the bug**
Building and running the content pages app with `docker-compose build` and `docker-compose up` from the root of the monorepo gives 500 errors. The actual error is this (for the publications page):
```
TypeError: publicationsData.map is not a function
```
The team page gives a similar error, but `teamData` not `publicationsData`.

Running the app with docker-compose from `packages/app-content-pages` is fine. I think the problem might be that the Contentful environment is undefined for the top-level Docker build.

**To Reproduce**
Run `docker-compose build` and `docker-compose up` (or `docker-compose up --build`) from the root of the monorepo. Browse to http://localhost.zooniverse.org:3001/about/publications once the NextJS apps start up.

**Expected behavior**
You should be able to browse the publications page at
http://localhost.zooniverse.org:3001/about/publications
and the team page at
http://localhost.zooniverse.org:3001/about/team

### PR DESCRIPTION
**Pull request by camallen**
Package: app-content-pages

Closes #1499 

If the contentful API call errors (missing secret client setup) then the `teamData|publicationsData` are left undefined. This PR fixes this issue by adding a check for undefined values and replaces them with an empty array on props and adds default values to the API requests

For bonus points (and learnings), I added tests on the default props API calls to contentful API for team and publications data.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

File: packages/app-content-pages/src/screens/Team/TeamContainer.js [hunk 1]
```diff
@@ -30,8 +31,9 @@ function TeamContainer (props) {
 TeamContainer.getInitialProps = async ({ req }) => {
   const host = getHost(req)
   let error
-  const teamData = await request.get(host + '/api/team')
-    .then(res => res.body)
+  let teamData
```
Comment (eatyourgreens) [inline packages/app-content-pages/src/screens/Team/TeamContainer.js]:
```suggestion
  let teamData = []
```
It's good practice to set a default here.

File: packages/app-content-pages/src/screens/Team/TeamContainer.js [hunk 2]
```diff
@@ -30,8 +31,9 @@ function TeamContainer (props) {
...
+  await request.get(host + '/api/team')
+    .then(res => teamData = res.body)
```
Comment (eatyourgreens) [inline packages/app-content-pages/src/screens/Team/TeamContainer.js]: Not a blocking comment but the linter should be warning about returning assignment here. Good practice is to return an actual value or wrap your function so that it returns nothing.

File: packages/app-content-pages/src/screens/Team/TeamContainer.js (hunk 1 above)
Comment (camallen) [reply packages/app-content-pages/src/screens/Team/TeamContainer.js]: thanks - OOI what about the `let error` above, I assume as that will be undefined instead of used in the mapping functions it's ok to not have a default?

Comment (eatyourgreens) [reply packages/app-content-pages/src/screens/Team/TeamContainer.js]: Depends how consuming code is supposed to detect errors, I guess. It looks like you return both `teamData` and `error`. Will anything bad happen if both are defined at the same time?

Comment (camallen) [reply packages/app-content-pages/src/screens/Team/TeamContainer.js]: no - it handles the missing data (original error). I've added mappable default for teamData

File: packages/app-content-pages/src/screens/Team/TeamContainer.js (hunk 2 above)
Comment (camallen) [reply packages/app-content-pages/src/screens/Team/TeamContainer.js]: intruging - only linter errors I got from `yarn lint` were about return values from fat arrow functions.

Comment (camallen) [reply packages/app-content-pages/src/screens/Team/TeamContainer.js]: nope - i modified the code to remove that....master linter errors are there `Arrow function should not return assignment`

Comment (eatyourgreens) [reply packages/app-content-pages/src/screens/Team/TeamContainer.js]: That's the one. Here you are returning `teamData = res.body`.

**Comment by camallen** [comment]
> Looks good. I think the publications page will need the same changes.

Done - I think this is ready for another review

File: packages/app-content-pages/src/screens/Publications/PublicationsContainer.js [hunk 3]
```diff
@@ -10,7 +10,8 @@ import Publications from './Publications'
 counterpart.registerTranslations('en', en)
 
 function PublicationsContainer(props) {
-  const { error, publicationsData } = props
+  const error = props.error
+  const publicationsData = props.publicationsData || []
```
Comment (eatyourgreens) [inline packages/app-content-pages/src/screens/Publications/PublicationsContainer.js]: I somehow missed that this is a React component. You can set default values for props for the component in `PublicationsContainer.defaultProps`

File: packages/app-content-pages/src/screens/Team/TeamContainer.js [hunk 4]
```diff
@@ -10,7 +10,8 @@ import Team from './Team'
 counterpart.registerTranslations('en', en)
 
 function TeamContainer (props) {
-  const { error, teamData } = props
+  const error = props.error
+  const teamData = props.teamData || [];
```
Comment (eatyourgreens) [inline packages/app-content-pages/src/screens/Team/TeamContainer.js]: Same comment here about setting defaults in `TeamContainer.defaultProps`.

File: packages/app-content-pages/src/screens/Publications/PublicationsContainer.js (hunk 3 above)
Comment (camallen) [reply packages/app-content-pages/src/screens/Publications/PublicationsContainer.js]: Perfect :) will do

File: packages/app-content-pages/src/screens/Team/TeamContainer.js (hunk 4 above)
Comment (camallen) [reply packages/app-content-pages/src/screens/Team/TeamContainer.js]: Done - i think this is ready now.
