### PR TITLE
Image toolbar: use pointer events

### LINKED ISSUE #4314: Continuous zoom is broken with a pointing device (mouse, trackpad etc.)
## Package
lib-classifier
## Describe the bug
Zooming in and out only changes the zoom level by one step when you click the zoom in/out buttons. Continuous zoom from the keyboard with +/- isn't affected.

## To Reproduce
1. Go to https://frontend.preview.zooniverse.org/projects/pmlogan/poets-and-lovers/classify/workflow/21362/subject-set/104809
2. Click on the Zoom In button

## Expected behavior
Zooming in and out should be continuous while the pointer is down.

As a workaround, you can zoom with the +/- keys then pan the subject with the cursor keys.

### LINKED ISSUE #4351: Image Toolbar doesn’t support pointer events
https://github.com/zooniverse/front-end-monorepo/blob/29dcec1f867cc607295794efbd3f2f31ed3f8e41/packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/Button/Button.js#L65-L71

The mouse events here should be replaced by `onPointerOver` and `onPointerOut`. `onPointerDown` and `onPointerUp` should also be supported. 

See the discussion in #4315.

### PR DESCRIPTION
**Pull request by eatyourgreens**
- Add pointer events to the base `Button` component.
- Remove extra `span` elements from the zoom controls.
- Remove mouse events.
- Replace HOC's with hooks in the zoom buttons.

This reverts #4315 and fixes #4314 by adding pointer events to the image toolbar's base `Button` component.

Closes #4351.

## Package
lib-classifier

## How to Review
#4314 shouldn't regress here, so continuous zoom should still work while the pointer is down. This should also fix styling bugs that were caught by @goplayoutside3.

# Checklist
_PR Creator - Please cater the checklist to fit the review needed for your code changes._
_PR Reviewer - Use the checklist during your review. Each point should be checkmarked or discussed before PR approval._

## General
- [x] Tests are passing locally and on Github
- [ ] Documentation is up to date and changelog has been updated if appropriate
- [x] You can `yarn panic && yarn bootstrap` or `docker-compose up --build` and FEM works as expected
- [x] FEM works in all major desktop browsers: Firefox, Chrome, Edge, Safari (Use Browserstack account as needed)
- [x] FEM works in a mobile browser

## Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [x] The bug is fixed
- [ ] Unit tests are added or updated

## Refactoring
- [x] The PR creator has described the reason for refactoring
- [x] The refactored component(s) continue to work as expected

### CODE REVIEW

File: packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButtonContainer.js [hunk 1]
```diff
@@ -1,7 +1,8 @@
+import { observer } from 'mobx-react'
 import PropTypes from 'prop-types'
```
Comment (goplayoutside3) [inline packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomOutButton/ZoomOutButtonContainer.js:2]:
```suggestion
```

File: packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButtonContainer.js [hunk 2]
```diff
@@ -1,7 +1,8 @@
+import { observer } from 'mobx-react'
 import PropTypes from 'prop-types'
```
Comment (goplayoutside3) [inline packages/lib-classifier/src/components/Classifier/components/ImageToolbar/components/ZoomInButton/ZoomInButtonContainer.js:2]:
```suggestion
```

**Review by goplayoutside3 — APPROVED** [review]
Looks good! Non-blocking suggestion to convert ZoomInButton and ZoomOutButton unit tests to RTL in this refactor PR, but not required. For instance, their icon svg components don't really need spec files.

**Comment by eatyourgreens** [comment]
Agreed re. tests. #4314 could have been avoided if button behaviour was tested. I’ll circle back to those if I have time next week.
