### PR TITLE
Classifier: Set step.next for transcription tasks

### LINKED ISSUE #2102: Transcription Task workflows do not work with additional tasks
## To Reproduce
1. Go to the [Davy Notebooks Project lab page](https://www.zooniverse.org/lab/9006/workflows/18244) and activate Workflow #18244  
2. Then visit https://frontend.preview.zooniverse.org/projects/humphrydavy/davy-notebooks-project
3. Click on "Davy Notebooks Beta Test Workflow (2021)"
3. Respond to the Transcription Task prompts and click next
4. See error (does not move past Transcription Task screen to T2)

## Expected behavior
After the question task "Have all the volunteer-made underline marks turned grey?" the volunteer should click "Next" and be taken to the next Task in the workflow.

### Desktop (please complete the following information):
 - OS: Mac OS Catalina
 - Browser: Chrome
 - Version: 89

## Panoptes info
Project: 9006
Workflow: 18244

## Additional context
The team was hoping to go to beta on April 20, but I've told them we'd need to delay until April 27. Note that this bug may also be affecting any NEH institute teams using the Transcription Task (though I haven't had any additional bug reports other than the DNP team).

### PR DESCRIPTION
**Pull request by eatyourgreens**
Transcription workflows have steps defined, so they bypass `convertWorkflowToUseSteps`. However, the Next Task selector in the project builder still sets `task.next` to a task key for each task and single choice answer. This PR runs `convertWorkflowToUseSteps` on all incoming workflow snapshots. It checks `step.next` for each step, and tries to set it from `task.next` if it doesn't exist.

https://localhost:8080/?env=production&project=9006&workflow=18244&demo=true

Package:
lib-classifier

Closes #2102.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?

## Components
- [ ] Has a storybook story been created or updated?
- [ ] Is the component accessible? 
  - [ ] Can it be used with a screen reader? [BBC guide to testing with VoiceOver](https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html)
  - [ ] Can it be used from the keyboard? [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)
  - [ ] Is it passing accessibility checks in the storybook?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `yarn panic && yarn bootstrap` or `docker-compose up --build` and app works as expected?

## Publishing

- [ ] Is the changelog updated?
- [ ] Are the dependencies updated for apps and libraries that are using the newly published library?

## Post-merging

- [ ] Did the app deploy to https://frontend.preview.zooniverse.org/projects/:project-name/:owner or https://frontend.preview.zooniverse.org/about?
- [ ] Is the new feature working or bug now fixed?
  - [ ] Is there a Talk or blog post written to announce the new feature(s)?
- [ ] Is the design working across browsers (Firefox, Chrome, Edge, Safari) and mobile?
  - [ ] Is this approved by our designer?
- [ ] Is this ready for production deployment?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Looking at this again, maybe it would be better to put these fixes into `convertWorkflowToUseSteps` and run that across all workflows, even ones that do have `steps` defined.

**Review by srallen — CHANGES_REQUESTED** [review]
Blocking this because I think the fix should go into the lab. When the new lab page is built, would this be removed? I'd prefer not editing the classifier for a scenario of configuration that shouldn't exist to begin with.

**Comment by eatyourgreens** [comment]
I think the plan is to remove `convertWorkflowToUseSteps` eventually. It was originally part of the `WorkflowSteps` model and my understanding is it's only needed for workflows that are expected to work in PFE?

**Comment by srallen** [comment]
Ok, for posterity, after I got more fully caught up, the issue for #2102 isn't how the lab works, but with the slightly differing behavior between `AnnotatedSteps` and `WorkflowStepStore`. I've opened #2107 as an alternative fix to this because it addresses the differing behaviors and refactors `step.getNextStep` to derive the next step using the way `WorkflowStepStore` built it to do so.

**Comment by eatyourgreens** [comment]
I'm afraid #2107 introduces a regression that was fixed in #2097 for branching workflows. That bug isn't present on this branch. The missing piece in #2107 is a check on each step to see if it's the last step the workflow. Branching workflows can have more than one last step.

I started down the same route here, initially. The first version of this PR modified the `WorkflowSteps` model to check each step for a next step. However, I realised that I was duplicating code from the `Workflow` model, and the fix was simpler if I added ~5 new lines to `convertWorkflowToUseSteps`, so I rewrote this PR and went down that route instead.

File: packages/lib-classifier/src/store/helpers/convertWorkflowToUseSteps/convertWorkflowToUseSteps.js [hunk 1]
```diff
@@ -97,8 +97,21 @@ export default function convertWorkflowToUseSteps ({ first_task, tasks }) {
     }
   })
 
+  return steps
+}
+
+export default function convertWorkflowToUseSteps ({ first_task, steps = [], tasks }) {
+  steps = steps.length > 0 ? steps :createStepsFromTasks(first_task, tasks)
```
Comment (srallen) [inline packages/lib-classifier/src/store/helpers/convertWorkflowToUseSteps/convertWorkflowToUseSteps.js:104]:
```suggestion
  steps = steps.length > 0 ? steps : createStepsFromTasks(first_task, tasks)
```

**Review by srallen — APPROVED** [review]
There's a typo, but it doesn't seem to be breaking anything.
