### PR TITLE
Fix LCV not loading next subject

### LINKED ISSUE #238: TESS LCV - cannot fetch next Subject
## Major Issue

Package: lib-classifier
Project: Light Curve Viewer / Planet Hunters TESS

Issue: After successfully submitting the Classification for a Planet Hunters TESS Subject, the whole app crashes when the next Subject is fetched.

Noted on localhost+OSX+Chrome (use `http://localhost:8080/?project=1862` to test on Planet Hunters TESS)

### Analysis

- This only occurs when submitting data from the Planet Hunters TESS project; the default I Like Cats project submits Classifications and fetches the next Subject normally.
- This is likely with the LightCurveViewer component (or its container, maybe?), as I've been able to trace that the code works fine _at least_ until `LightCurveViewer.componentDidUpdate()`
- When I say "the app crashes", I mean that we see a vague error - `Uncaught Error: [mobx-state-tree][error] You are trying to read or write to an object that is no longer part of a state tree. (Object type was 'SubjectResource'). Either detach nodes first, or don't use objects after removing / replacing them in the tree.` - and the `<div id="root">` node _becomes empty,_ turning the whole page blank.

### Dev Notes

While this isn't likely to be the cause of the problem, it's worth examining:

```
//LightCurveViewer.js
  componentDidUpdate (prevProps) {
    const isFirstDraw = !prevProps.points.length && this.props.points.length
    if (isFirstDraw) {
      const container = this.svgContainer.current
      const height = container.offsetHeight || 0
      const width = container.offsetWidth || 0
      this.drawChart(width, height, isFirstDraw)
    }
  }
```

The logic implied by `isFirstDraw` needs reexamining, as it will only trigger when the first Subject is loaded to the LightCurveViewer, since subsequent Subjects may (and it the case of TESS, often do) have the same number of data points.

### Status
Major Issue, but localised to a single project for the time being.

### PR DESCRIPTION
**Pull request by rogerhutchings**
Package: lib-classifier

Closes #238 

Ensures a new subject is plotted on the chart, adds a placeholder drawing task for the tasks area.

# Review Checklist

## General

- [ ] Are the tests passing locally and on Travis?
- [ ] Is the documentation up to date?
- [ ] Is the changelog updated?

## Apps

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?

### CODE REVIEW

File: packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js [hunk 1]
```diff
@@ -28,9 +28,9 @@ class LightCurveViewerContainer extends Component {
   }
 
   componentDidUpdate (prevProps) {
-    const prevSubject = prevProps.subject
-    const { subject } = this.props
-
+    const prevSubject = prevProps.subject.toJSON()
+    const subject = this.props.subject.toJSON()
```
Comment (srallen) [inline packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js]: The MST `toJSON()` method is meant for debugging according to their docs. I've been using the MobX `toJS()` for conversion instead which also gives us a configurable option about what to do with maps: https://mobx.js.org/refguide/tojson.html

I might suggest adding a getter to the store's view methods that returns the vanilla JS as needed.

Comment (rogerhutchings) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js]: Unfortunately, that isn't working here, since the object referred to by `prevProps` has already been removed from the store. What I did instead was pass `subject.id` as an additional prop to the current `Viewer` component, which works as it's a primitive.

Comment (srallen) [reply packages/lib-classifier/src/components/Classifier/components/SubjectViewer/components/LightCurveViewer/LightCurveViewerContainer.js]: Ah right, that makes sense.
